### ISSUE TITLE
Add caching strategy to parametric TypeIOs

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#102]
For https://github.com/phetsims/tandem/issues/100. It could look like this:

```js
function createParametricTypeIO( outerTypeName, parameterTypes ) {

  const typeName = getUniqueTypeName( outerTypeName, parameterTypes ); // TODO: also use this in phetioInherit for assembling typeName

  if ( cache[ typeName ] ) {
    return cache[ typeName ];
  }
  else {

    // cache miss, create a new one
    cache[ typeName ] = outerTypeName.apply( parameterTypes );
  }
  return cache[ parameterType.typeName ];
}
```

We can remove the cache from Action with this change. We need to make sure that this strategy doesn't overwrite other phet-io TypeIOs.

**Comment by chrisklus** [comment]
This could help performance in https://github.com/phetsims/phet-io/issues/1542

**Comment by zepumph** [comment]
I think we shouldn't lose steam on this. It seems like it would be a really good performance improvement.

**Comment by zepumph** [comment]
In a discussion with @samreid last week, we thought that perhaps we could make a cache that could be used by composition in each parametric type. The key is having a mapping function that can get the typeName of an IO type without creating the IO type (key for garbage collection performance at least).

**Comment by zepumph** [comment]
- [ ] Once this is implemented, we should remove the cache set up specifically for Action.js

**Comment by zepumph** [comment]
This is causing other issues to be on hold, elevating priority.

**Comment by samreid** [comment]
I prototyped this for Property and tested in Graphing Quadratics.  I saw: 43.1MB (cache) and 45.3MB (no cache).  That's a savings of 2.2MB or nearly 5%.  That was 11 cache misses and 360 cache hits.  I'll commit and if we agree this pattern looks OK we can apply it to other parametric types.

**Comment by samreid** [comment]
@zepumph does this pattern look OK to you?

**Comment by samreid** [comment]
We discussed it today, we agreed the pattern is appropriate and we should apply it to all of the parametric types.

**Comment by zepumph** [comment]
I added this for ActionIO and EmitterIO, and removed the cache in Action. I didn't see any noticeable heap change, but that is expected since things were already cached.

**Comment by zepumph** [comment]
Implemented above. @samreid will you please review.

**Comment by samreid** [comment]
I added delimiters for the cache keys (so that HouseBoat could be distinguished from House,Boat) and updated the JSDoc to clarify that all of the caches should be maintained together.  @zepumph want to double check these changes before we close?

**Comment by zepumph** [comment]
We forgot NullableIO()

**Comment by zepumph** [comment]
@chrisklus, @samreid, and I implemented it above, and didn't find any others. Closing
