### ISSUE TITLE
Create mixin for stateObjectToArgs

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#105]
From https://github.com/phetsims/phet-io/issues/1454 and https://github.com/phetsims/charges-and-fields/issues/170.

For any Group member types, it would be nice to have a mixin for the method `stateObjectToArgs`. This would allow us to have this method on Group members only, and not accidentally call it on an IO type that is not part of a Group.

@zepumph will take the lead on this and report back to @samreid when ready. We think this does not necessarily need to be worked on soon.

**Comment by samreid** [comment]
After discussion today, we thought something like this may be possible:

```js
class ElectricPotentialLineIO extends mixin(ModelElementIO,MemberObjectIO) {
```
But it would be an insufficient gain for the amount of work, and not a sufficiently improved end product.  Closing.
