### ISSUE TITLE
create general.model and general.view?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#108]
From https://github.com/phetsims/tandem/issues/96

@kathy-phet and @arouinfar felt good about this model/view separation for global things, but for general @kathy-phet said:

>I'm wondering for general, if it is going to make it harder to find things? Right now we have a "Navigation Bar" there which makes it easy to find the stuff in the navigation bar. But if that was first model and then view it would be harder to find. That is my only concern with this path - the instructional designer looking for stuff. What would it look like in "general" if it were to change?

Let's discuss it further here!

**Comment by zepumph** [comment]
Here is a first pass at categorizing the items I see when running GFL from master:

model
  * activeProperty
  * browserTabVisibleProperty
  * focusProperty
  * phetioCommandProcessor
  * resizeAction
  * screenIndexProperty
  * soundEnabledProperty
  * stepSimulationAction

view
  * utteranceQueue (I think this belongs in the view, even though currently the event type is "MODEL" we should change that)
  * barrierRectangle
  * navigationBar   (because it is all Nodes)

controller (arguably this should be in it's own category for MVC)


This is just to help visualize what this may look like. I'm not saying we should execute it.

**Comment by samreid** [comment]
That division looks appropriate to me.  I don't think we need a category for "controller", most of those things would make sense in the view, at least with our current architecture.

**Comment by samreid** [comment]
@zepumph volunteered to take a first look at this, then bring it back to design meeting.

**Comment by zepumph** [comment]
I will bring back to design phet-io meeting with a first pass for review.

**Comment by chrisklus** [comment]
In the above commits I moved `general` elements to `general.model` and `general.view` and updated wrapper usages of `phetio.PhetioIDUtils.getGeneralID` to include the correct `model` or `view` prefix.

I wasn't sure of the best way to proceed for the latter, so @samreid and I discussed some options, see https://github.com/phetsims/tandem/issues/151.

Marking for phet-io meeting to discuss how we like `general.model` and `general.view`.

**Comment by chrisklus** [comment]
Notes from 03/05/20 meeting:

* Why is `focusProperty` in sims without accessible features? See https://github.com/phetsims/scenery/issues/1037
For now we are okay with featuring `focusProperty` and `soundManager` Properties generally and updating their documentation to indicate that it doesn't apply to some sims.

* `resizeAction` docs: 'Values are in CSS pixels' -> 'Values are the sim dimensions in CSS pixels.`

* instrument soundManager.js,  extend with PhetioObject, move it to view, pass tandem to it

**Comment by zepumph** [comment]
All focusProperty work has been completed over in https://github.com/phetsims/scenery/issues/1037, but I didn't do the soundManager update.

**Comment by chrisklus** [comment]
@chrisklus and @zepumph addressed design changes from https://github.com/phetsims/tandem/issues/108#issuecomment-595405282. @zepumph can you do a quick review please? Relevant commits are https://github.com/phetsims/joist/commit/0a9c159c6861ca3e4014bbfeb34dae7a7bd56091 and https://github.com/phetsims/tambo/commit/9d0e251d42b22a31bfb3730618a83f6ff33befab.

**Comment by zepumph** [comment]
All these changes look really nice. Did we want to phetioFeature the enhancedSoundEnabledProperty too? Otherwise looks excellent, and I trust you can feature one element.

**Comment by chrisklus** [comment]
Thanks @zepumph! Right - I'll unfeature `soundManager` and feature `enhancedSoundEnabledProperty` so both of its Properties are featured.

@arouinfar would you mind taking a look and closing if this looks good in Studio or pass back to me? Our design meeting notes are in https://github.com/phetsims/tandem/issues/108#issuecomment-595405282.

**Comment by arouinfar** [comment]
@chrisklus this is all looking good in studio on master. It looks like I don't have the appropriate privileges in this repo to reassign or close issues, so I'll ping the phet-io slack channel that this is ready to be closed.

**Comment by pixelzoom** [comment]
@chrisklus  @arouinfar @samreid reopening.

@chrisklus I see that you added doc soundManager and its Properties, and the new doc is:

```
soundManager:  "Controls the simulation's sound. Note that this only applies to  sims that support sound."
soundManager.enabledProperty: "Controls the simulation's sound. Note that this only applies to sims that support sound."
soundManager.enhancedSoundEnabledProperty:  "'If the sim contains sound, then this Property will toggle whether "enhanced" sound is enabled or disabled. Note that not all simulations that support sound also support enhanced sound."
```

A few things...

(1) It's not clear from the doc how `enabledProperty` and `enhancedSoundEnabledProperty` are related.  I'm assuming that if `enabledProperty` is false, then the value of `enhancedSoundEnabledProperty` is irrelevant? 

(2) My understanding from the 3/5/20 phet-io meeting was that one of the reasons for instrumenting soundManager was so that we didn't need to add a note about relevancy to each of its Properties.  We could say that once for soundManager, not have to repeat ourselves for its Properties, and (more importantly) not have to remember to repeat ourselves if we add new Properties.  So something like:

```js
phetioDocumentation: 'Controls the simulation\'s sound. For sims that do not contain sound, you can ignore this element and its children." 
```

(3) If we do want to repeat ourselves for each Property, then I don't find the doc for enhancedSoundEnabledProperty to be very useful.  It doesn't tell me what enhanced sound is, which is the most important thing that I (as a designer) would need to know.  So maybe something like:

> If the sim contains enhanced sound, then this Property will toggle it's enabled or disabled. Enhanced sound is <DESCRIBE HERE>.

(4) We agreed to do something similar for `soundManager` and `focusProperty`.  You and @zepumph handled these separately, and the style of your doc differs considerably.   @zepumph's style is to describe the Property, followed by a note about it's relevance:

```
  phetioDocumentation: 'Stores the current focus in the simulation, null if there is nothing focused. This is not updated ' +
                       'based on mouse or touch input, only keyboard and other alternative inputs. Note that this only ' +
                       'applies to simulations that support alternative input.',
```

Your style is to different:

```
      phetioDocumentation: 'If the sim contains sound, then this Property will toggle whether sound is enabled or ' +
                           'disabled.'
```

If we're interested in having consistency in the documentation (which I think is desirable for a good Studio UX), then you might consider changing your doc to be more like @zepumph's -- describe the Property, then add a note about its relevancy:

```js
    this.enabledProperty = new BooleanProperty( phet.chipper.queryParameters.sound === 'enabled', {
      tandem: tandem.createTandem( 'enabledProperty' ),
      phetioFeatured: true,
      phetioDocumentation: 'Determines whether sound is enabled. You can ignore this for sims that do not support sound.'
    } );

    this.enhancedSoundEnabledProperty = new BooleanProperty( phet.chipper.queryParameters.sound === 'enabled', {
      tandem: tandem.createTandem( 'enabledProperty' ),
      phetioFeatured: true,
      phetioDocumentation: 'Determines whether enhanced sound is enabled, and is relevant only if enabledProperty is true. Enhanced sound is <DESCRIBE HERE>. You can ignore this for sims that do not support enhanced sound.'
    } );
```

**Comment by pixelzoom** [comment]
... and feel free to ignore any or all of the above input.  It's just my 2¢.

**Comment by chrisklus** [comment]
Thanks for the input @pixelzoom.

>(1) It's not clear from the doc how `enabledProperty` and `enhancedSoundEnabledProperty` are related.  I'm assuming that if `enabledProperty` is false, then the value of `enhancedSoundEnabledProperty` is irrelevant? 

Right, that appears to be accurate based on the behavior in GFL. I updated the doc of `enhancedSoundEnabledProperty` to include this relationship.

>(2) My understanding from the 3/5/20 phet-io meeting was that one of the reasons for instrumenting soundManager was so that we didn't need to add a note about relevancy to each of its Properties.  We could say that once for soundManager, not have to repeat ourselves for its Properties, and (more importantly) not have to remember to repeat ourselves if we add new Properties.

Agreed - I updated the doc for `soundManager` and removed the redundancies in its children.

>(3) If we do want to repeat ourselves for each Property, then I don't find the doc for enhancedSoundEnabledProperty to be very useful.  It doesn't tell me what enhanced sound is, which is the most important thing that I (as a designer) would need to know.  So maybe something like:

Right - I got a definition from @jbphet and added it to the doc.

>(4) We agreed to do something similar for `soundManager` and `focusProperty`.  You and @zepumph handled these separately, and the style of your doc differs considerably.   @zepumph's style is to describe the Property, followed by a note about it's relevance ... If we're interested in having consistency in the documentation (which I think is desirable for a good Studio UX), then you might consider changing your doc to be more like @zepumph's -- describe the Property, then add a note about its relevancy

Agreed, I updated the docs to match that style.

@arouinfar please review these additional changes.

**Comment by arouinfar** [comment]
@chrisklus I reviewed GFL on master, and the updated documentation is looking really nice.
