### ISSUE TITLE
Factor out `validate` calls from toStateObject/setValue to usage sites

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#110]
@samreid, @chrisklus, and I wish that it would be simpler if we validated at the usage sites instead of needing to add it to each implementation (so each IO Type).

For `setValue` this is very straight forward, as there is only two usages. One in the state engine and one in NumberProperty.setValue for the parent.

`toStateObject` on the other hand has 60 usages, and they are called all over the place. The places where we serialize parater types, for example here when emitting an event to the data stream in ObservableArray:

```

 // @private called when an item is removed.
    _fireItemRemoved: function( item ) {
      const self = this;
      this.phetioStartEvent( 'itemRemoved', function() {
        return self.phetioType.parameterType.toStateObject( item );
      } );
```

I don't think that we should force these usages into also validating. @samreid do you think we should just give up on this? Maybe we can implement `setValue` but not `toStateObject`, but would that lack of parallel validation in IO type implementations be confusing?

**Comment by samreid** [comment]
Validation was centralized in #211 in IOType, closing.
