### ISSUE TITLE
Rename Group

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#111]
from https://github.com/phetsims/phet-io/issues/1454#issuecomment-538128286

I agree, it would be nice to have something that conveyed better that "phet-io registry" feel that it is taking on.

I don't think this is top priority, we don't even know for certain if `Group` is the final implementation. See https://github.com/phetsims/phet-io/issues/1454 and sub issues before spending too much time on this.

**Comment by zepumph** [comment]
Some ideas from phet-io dev meeting today:

* PhetioDyanamicGroup
* PhetioGroup
* PhetioSet
* PhetioCollection
* DynamicGroup
* PhetioPool(party)
* DyanmicElementGroup
* DynamicElementContainer

* We really like a name that communicates its unordered, set-like qualities. 
* We like "Group" because we have been using it so far and it makes sense. Other terms seem only like a side step, not an improvement

**Comment by chrisklus** [comment]
@samreid, @zepumph and @chrisklus quickly agreed on `PhetioGroup` to be the new name. How nice!

@samreid volunteered to take this on.

**Comment by samreid** [comment]
Renamed in preceding commits, @zepumph can you please review?

**Comment by zepumph** [comment]
Looks great thanks!
