### ISSUE TITLE
Group should be homogeneous

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#113]
From https://github.com/phetsims/phet-io/issues/1454, in order to maintain generality, Group was originally developed to support heterogeneous value types.  However, this leads to an awkward API, so we considered changing to homogeneous only. From yesterday's discussion:

> @samreid: Should Group be homogeneous (exact same type only)? Then interleaving would be done via ObservableArray?
> @pixelzoom: That sound preferable.

Further discussion from today from https://github.com/phetsims/phet-io/issues/1454#issuecomment-541141057

From discussion today between @chrisklus @zepumph and @samreid: That would add an extra level of indirection in studio.  For instance, in studio, you would see a dogsAndPeopleObservableArray.  Then to access the first dog, you would have to click dogsAndPeopleObservableArray.character[0] to see its phetioID, then interact through a "coupon cutout" or click to go to its definition in the group.

@zepumph says we shouldn't limit our ability to improve/optimize Group based on current limitations in the UI.  We could improve the UI later if necessary.

**Comment by samreid** [comment]
This could be a simple job if it is limited to:

* Remove the *heterogeneous methods
* Pop up the `prototypeSchema` to top level, so the 2nd arg would be the create function.  The default arguments would go in the options.  Or maybe a required arg?  I don't know.  Let's try it as a required arg, since it seems it will appear frequently.
```js
new PhetioGroup('things',tandem=>new Thing(tandem), [],{tandem:tandem.createTandem('group'})
new PhetioGroup('things',tandem=>new Thing(tandem), {tandem:tandem.createTandem('group'})

new PhetioGroup('things',tandem=>new Thing(tandem), [true],{tandem:tandem.createTandem('group'})
new PhetioGroup('things',tandem=>new Thing(tandem), {defaultArguments: [true], tandem:tandem.createTandem('group'})
```

**Comment by samreid** [comment]
This is mostly complete in my working copy, but I'll hold off pushing until I can monitor CT more closely.

**Comment by samreid** [comment]
I converted Group to homogeneous in the preceding commits, @zepumph can you please review?  Also note I renamed `addNextGroupMember` to `addNextMember` (not tracked in an issue).

**Comment by zepumph** [comment]
Things look really good to me. I see that we made defaultArguments as a required param. That sounds good to me. I'm about to take this for a test drive over in https://github.com/phetsims/projectile-motion/issues/177 and will report any problems in a new issue. Anything else here?

**Comment by samreid** [comment]
That's all for now, thanks!  Closing.
