### ISSUE TITLE
Updates to Group API

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#114]
Here are some micro adjustments that should be done before too long.
- [x] rename `groupMemberCreatedEmitter`  -> `memberCreatedEmitter` and same for `disposed`
- [x] make those private
- [x] add Group methods for adding/removing; addMemberCreatedListener/removeMemberCreatedListener and addMemberDisposedListener/removeMemberDisposedListener
- [x] add es5 getter for array? We decided no not right now, no need.

**Comment by zepumph** [comment]
Tagging @chrisklus too.

**Comment by samreid** [comment]
All parts fixed as prescribed, @zepumph want to review?

**Comment by zepumph** [comment]
I like these changes. I especially like that the emitters are private now. Not like anyone was going to call `emit` outside of the Group, but still, if feels good to me.
