### ISSUE TITLE
PhetioGroup should have collections-like interface.

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#115]
In usage of PhetioGroup in Circuit Construction Kit, there are:

* 12 usages of `vertexGroup.array.indexOf`
* 5 usages of `vertexGroup.array.forEach`
* 2 usages of `vertexGroup.array.filter`
* 1 usage of `vertexGroup.array.map`

It seems we should change these to `vertexGroup.indexOf`, etc.  We could also do the same in ObservableArray if we proceed with https://github.com/phetsims/axon/issues/265#issuecomment-541334742

@zepumph sound OK to you?

**Comment by samreid** [comment]
Marking high as it pertains to Group interface

**Comment by zepumph** [comment]
To me indexOf is array specific. I would prefer 'contains' because phetioGroup is more set-like than ordered. If there is code depending on an ordering of group members then I think we have a problem.  Another reason for trying to hide the array in group completely.

**Comment by samreid** [comment]
I added collections-like methods above.  I agree PhetioGroup is more set-like than array-like, but I have many occurrences of `vertexGroup.array.indexOf` in CCK.  It would be good to discuss them and see if there's a better way.  I'll assign to @zepumph for review of what's there and I'll note in Wednesday's agenda for possible discussion.

**Comment by zepumph** [comment]
I like all of these changes. I would say there is little value in having these methods, and still having `array` be public read-only. Can we make it private? 

>but I have many occurrences of vertexGroup.array.indexOf in CCK.

Many usages I've see were for iterating through or just a `contains` check. Perhaps we can decouple the array-like implementation.

That said, this may increase the load to convert from ObservableArray to PhetioGroup. Still I think I'd prefer making `array` private. Especially since this middle ground we have found ourselves in seems like the worst of both worlds.

**Comment by samreid** [comment]
Imagine for the sake of argument that (a) we have a method that computes metrics based on an array of Electrons, something like `computeMetrics(electronArray)` and (b) it is a performance-limited application, so we cannot clone/copy the array but rather we should provide read-only access to it and (c) this method needs to be called on the contents of an ObservableArray of selectedElectrons as well as the PhetioGroup of all electrons.  How can this be accomplished?

**Comment by zepumph** [comment]
I'm not sure I agree with this personally, but channeling my logical argument, it seems like that means that you have a PhetioGroup that wants to act like an array, not a group, and so you should have a PhetioGroup which manages the creation/registration/disposal of these elements from the sim, and then you can have an array of electrons that can be treated like an array, and can have `computeMetrics` called on it.

**Comment by samreid** [comment]
Let's say I have a made-up case where I need to assign indices to 2 elements in a PhetioGroup.  Are you saying rather than doing this:

```js
electronGroup.indexOf( electronA )
```

it would be better to do:
```
const indexedListOfElectrons = new ObservableArray();
electronsGroup.forEach(electron => indexedListOfElectrons.map())
electronsGroup.addMemberAddedListener(electron => indexedListOfElectrons.push(electron));
electronsGroup.addMemberRemovedListener(electron => indexedListOfElectrons.push(electron));
indexedListOfElectrons.indexOf( electronA );
```

I understand philosophically we described PhetioGroup as an unordered set/pool.  But I'm having trouble understanding the practical advantages.

On the other hand, if we decide to continue with the "set" philosophy, why not go all in and back it with a  `Set`? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set  Is there a reason elements in our pool *shouldn't* be indexed?

Also, for the 10 occurrences of `vertexGroup.array.indexOf(` in CCK, is there a better pattern I could use?

**Comment by samreid** [comment]
Also, I want to make sure we aren't just stuck on the name, for instance, what if we had named it `PhetioArray` instead of `PhetioGroup`?

**Comment by zepumph** [comment]
>Are you saying rather than doing this: . . . it would be better to do . . .


No not at all. I seem to have an unsubstantiated feeling that it will be good to untie this from the implementation. 

To use `indexOf` on a group is fundamentally flawed, it is making an assumption that I don't feel like we will want to keep forever. I see that in CCKC, there is a lot of code making assumption of the ordering of these lists, like how ModifiedNodalAnalysisCircuitElement takes numbers to access  the list later. 

I see two options:
1. I shut up, and we just expose the array
2. We dive in and design a pattern here that doesn't leak out the array.

I think I prefer the 1st option, so long as we recognize that that legitimately ties us to using an array as the implementation for PhetioGroup forever. Perhaps with that in mind we call it `PhetioArray`?

**Comment by samreid** [comment]
I feel like our decision should hinge on the majority of client cases.  If most clients will need indexing functionality, we should probably include that.  If most clients will not need that, perhaps we should aim toward set-like functionality.  But if there are even a few cases that require indexing, it would be nice if there is a convenient way to do it.  I'd like to explore how that can be done for circuit construction kit.

Also, https://www.frontendmayhem.com/javascript-arrays-vs-sets/ told me that JS Set returns `values` according to the order they were added to the set, so maybe indexing based on order added to the group isn't totally off-base?

**Comment by samreid** [comment]
@chrisklus and @zepumph and I explored using `Vertex.index` instead of `vertexGroup.array.indexOf` and it seems like it will work.  For some reason the charges aren't showing on the capacitor plates, but I should figure that out.

**Comment by samreid** [comment]
I experimented with this again, leveraging the existing `Vertex.index` which was introduced for debugging.  I'm concerned that if index is mapped to matrix row/column, then we could end up with very large matrices.  I did not verify this, but even if it is not a problem now, how could we guarantee that it never becomes a problem?  Also, there is existing code where a for loop seems appropriate:

```js
        // if something else is already snapping to candidateVertex, then we cannot snap to it as well.
        // check the neighbor vertices
        for ( let i = 0; i < this.vertexGroup.length; i++ ) {
          const circuitVertex = this.vertexGroup.array[ i ];
          const adjacent = this.isVertexAdjacent( circuitVertex, vertex );

          // If the adjacent vertex has the same position as the candidate vertex, that means it is already "snapped"
          // there and hence another vertex should not snap there at the same time.
          if ( adjacent && circuitVertex.positionProperty.get().equals( candidateVertex.positionProperty.get() ) ) {
            return false;
          }
        }
```

I'm not sure that any of the collections-style methods would have as clear of an implementation.  Or we would just end up using forEach to build an array anyways.

I recommend scheduling collaboration time where @zepumph and I can investigate this further, to come up with a recommendation.

I'll also tag this for https://github.com/phetsims/circuit-construction-kit-common/issues/528 since it would be nice to have a vision for this before publishing CCK AC.

**Comment by zepumph** [comment]
>I'm not sure that any of the collections-style methods would have as clear of an implementation. Or we would just end up using forEach to build an array anyways.

Hiding the actual array has been working well so far. PhetioGroup has a forEach method that could be changed if we change the underlying array. Thus far I haven't seen a need for a set or map instead. I recommend closing this issue. If you disagree, I recommend we meet to discuss the particular CCK example, and why the current PhetioGroup wasn't working as desired.

**Comment by samreid** [comment]
This seems OK to close for now, closing.
