### ISSUE TITLE
PhetioGroup.createNextMember is named very similarly to createGroupMember

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#116]
From https://github.com/phetsims/tandem/issues/113#issuecomment-541332807

While working on Projectile Motion, I noticed how easy it would be to accidentally call createGroupMember (the "implementation" function) instead of createNextMember. `createGroupMember` is marked as public, though only for PhetioGroupIO. Should we rename `createGroupMember` to something like `createGroupMemberImplementation` or something internal sounding, or at least more verbose since it is only used inside group?

@samreid if you think nothing needs to change here, feel free to close.

**Comment by samreid** [comment]
How about `createIndexedMember` and add JSDoc that says it is primarily for internal use, and that most clients will use `createNextMember`?

**Comment by samreid** [comment]
Fixed above, @zepumph can you please review?

**Comment by zepumph** [comment]
Excellent. Thanks!
