### ISSUE TITLE
Should PhetioGroup.memberPrototype instances be disposed after baseline printed and validation completed?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#117]
I noticed in Circuit Construction Kit that if I use the PhetioGroup to create vertices, then I get a bunch of incorrect VertexNodes at the center of the screen corresponding to the `memberPrototype` instances.  Should these be disposed after validation completes, perhaps right after `phetioAPIValidation.onSimStarted( this );` in `phetioEngine.js`?

I'm also thinking there may be a better solution for CCK in particular, which I would be happy to hear about, but this issue is more generally interested in whether PhetioGroup should clean up after its memberPrototypes by disposing them.

**Comment by zepumph** [comment]
This sounds like something that should be handled by PhetioDynamicElementContainer over in https://github.com/phetsims/phet-io/issues/1594

**Comment by samreid** [comment]
Tagging for https://github.com/phetsims/phet-io/issues/1648

**Comment by zepumph** [comment]
I feel like this would likely be helpful in reducing memory in Studio, but in every other use case where archetypes are created, it probably doesn't matter too much.

**Comment by zepumph** [comment]
Thus far, we have not encountered any memory concerns with this. There are likely only a handful or two archetypes, and I'm not worried about them sticking around. If in the future we want to optimize that when we notice it to be a problem, then that sounds great! Closing
