### ISSUE TITLE
Set phetioBaselineMetadata to null after startup

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#118]
From https://github.com/phetsims/tasks/issues/1013.

After the sim is finished constructing, it no longer needs `phetioBaselineMetadata`, since validation is complete. We tried setting this to null for every `phetioObject` in the `phetioObjectMap` and found that it saves 0.1 MB in Graphing Quadratics. We like this change and will commit it.

**Comment by zepumph** [comment]
@chrisklus what is next for this issue?

**Comment by chrisklus** [comment]
I think we can close, do you agree?
