### ISSUE TITLE
customizing and resetting initial state via Studio

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#123]
Client requirements for Natural Selection PhET-iO include:

> Ability to have the restart button reset to our initial preset sim conditions. 

... where "the restart button" is the Reset All button, and "preset sim conditions" means configuration in Studio.  

We discussed this requirement in 11/5/19 Natural Selection design meeting, and I outlined the 3 approaches that I'm vaguely aware of:

(1) The client writes a custom listener for the Reset All button, and sets their desired state there. 

(2) Launch template creates its own Reset All listener automatically. @samreid pointed me to https://github.com/phetsims/phet-io-wrappers/commit/bbad898bd3bda6d37a4f2c98c4168d17496a034a as an example.

(3) When Launch sets state, it changes the initial values of Properties. According to @samreid via Slack, this feature is new as of Friday 11/1/19, it is "working for Properties, but not for PhetioGroups", and it may not be "iron clad" yet.

According to @kathy-phet, having to write a custom Reset All listener (approach 1) is not an option for this sim, and approach (3) is the future.  It also likely needs to work for `PhetioGroup`.  In Natural Selection, bunnies will be dynamic elements.  Clients will be able to specify an initial population of bunnies and their genotypes. And the initial population needs to be resettable without requiring a custom Reset All listener. 

Finally... There should be nothing sim-specific required to meet this client requirement.  It should be general and applicable to all sims. 

Relevant deadlines for Natural Selection:
* 12/1/19 - PhET-iO design completed
* 6/1/20 - "preview" dev version delivered to client with full PhET-iO support
* 8/1/20 - 1.0.0 published with `--brands=phet,phet-io`

**Comment by pixelzoom** [comment]
11/6/19 phet-io dev meeting, @samreid @zepumph @chrisklus @pixelzoom 

We discussed the approaches, and clarified that there are 3 approaches. I edited the description above.

We may need to go back to approach (2) for `PhetioGroup`.  But will investigate approach (3).

**Comment by pixelzoom** [comment]
Note that this also needs to address customization via query parameters, like https://github.com/phetsims/natural-selection/issues/9 (specify the initial population of bunnies) and https://github.com/phetsims/natural-selection/issues/24 (hide the concept of alleles).

**Comment by zepumph** [comment]
@pixelzoom note that currently, when a Property's state is set, its initial value is set to that value too. This way if the reset all button calls "myProperty.reset()", it will go back to the value set by the most recent state, instead of to the arbitrary value for normal PhET Brand. This was implemented with @samreid and helped greatly for GAO IIRC.

**Comment by zepumph** [comment]
Paper trail at the end of https://github.com/phetsims/phet-io-wrappers/issues/296.

**Comment by zepumph** [comment]
>It also likely needs to work for PhetioGroup. In Natural Selection, bunnies will be dynamic elements. Clients will be able to specify an initial population of bunnies and their genotypes. And the initial population needs to be resettable without requiring a custom Reset All listener.

I just want to note that I don't think that this should be dealt with by a "reset" function of `PhetioGroup`, at least not just yet. I am hopeful that Properties can control the PhetioGroup for bunnies appropriately, and we don't need to add the complexity to the dynamic element container. If this isn't working, then we should reevaluate and prototype that functionality into the PhetioGroup, but likely that will end up running on an internal Property anyways, so I hope it doesn't need to come to that.

**Comment by zepumph** [comment]
This is a very outdated issue, with the main, automatic solution implemented in https://github.com/phetsims/studio/issues/35, and improved upon since. PhetioStateEngine is now well setup to keep track of the most recently set state so that it can be reapplied as needed (for resetting screens or scenes).

Closing
