### ISSUE TITLE
Should PhetioGroup member tandems be customizable?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#124]
There was a TODO marked in PhetioGroup:

```js
* // TODO: do we need [individualized sub tandem names]? why now something consistent like `element_0`
```

@chrisklus @zepumph and I discussed this today and considered the following possibilities:

```
sim.screen1.model.electronGroup[0]
sim.screen1.model.electronGroup.0
sim.screen1.model.electronGroup.electron_0
sim.screen1.model.electronGroup.member_0
sim.screen1.model.electronGroup.element_0
```

However, to maximize readability in the data stream and studio, we would like to stick with the custom name, like `electron_0`.

**Comment by zepumph** [comment]
Since 2 hours ago, here are some thoughts:

Over in #1567 @samreid @chrisklus and @zepumph though it appropriate to name the "member" of PhetioSingleton to instance. But over here we still have a customizable prefix. We thought this deserved an issue to make sure there is a reason to have these different.

I don't think that element_0 as a consistent name is offensive, especially because now we support only homogenous groups. Should we make this change?

@samreid @chrisklus do we still agree with our original findings? Even if they mean that they differ from what we do in PhetioSingleton?

**Comment by zepumph** [comment]
I think I prefer calling them `element_0` right now.

**Comment by samreid** [comment]
I'm not sure one way or the other, but some thoughts:

* I like that calling them `element_0` cleans up the call sites for `new PhetioGroup()` a little bit, since you don't need to specify or maintain the element names.
* Do we need to run this kind of change past the PhET-iO design team?
* Do we need to be consistent between terminology between "member" vs "element"?  For instance, if we go with "element" perhaps all of the "member" terminology in PhetioGroup should be change to element.

**Comment by samreid** [comment]
After implementing https://github.com/phetsims/phet-io/issues/1567 I think we should go ahead and rename as "element_0" or equivalent.  @zepumph what do you think about the 3rd bullet point above?

**Comment by zepumph** [comment]
"Element" is public facing, and I think will look better studio and the data stream than "member". I have fine keeping PhetioGroup methods and fields as "member" but agree that it is probably clearer to have it also be element. 

Is there any reason why "element" is worst PhetioGroup? For example, is it more vague? Perhaps I'm just used to "member."

I still think that we should go with `element_0` no matter what.

**Comment by chrisklus** [comment]
We discussed this more today and decided that it was a micro-optimization to unify all names to "element" or "member", but we don't think it's that big of a deal to pass in a name for the members when creating a group. In general, it's better to go with the PhET way of being verbose and clear, and allowing Group-specific element names seems to align with that mindset. Closing.

**Comment by samreid** [comment]
Should the aforementioned decision be applied to PhetioCapsule?  For instance, should we change `aboutDialogCapsule.instance` to `aboutDialogCapsule.aboutDialog`?

**Comment by chrisklus** [comment]
Yes, I think I prefer `aboutDialogCapsule.aboutDialog` and having consistency between PhetioGroup and PhetioCapsule, but I don't feel too strongly.

**Comment by zepumph** [comment]
It is the most clear. Sounds good to me!

**Comment by samreid** [comment]
@chrisklus is this something you could do within the next couple of weeks?

**Comment by chrisklus** [comment]
@samreid yes i do - is the only action item to change PhetioCapsule `instance` to a customizable name?

**Comment by samreid** [comment]
Also to iterate through `new PhetioCapsule` and choose the names.

**Comment by chrisklus** [comment]
Changes pushed. I momentarily forgot that these changes don't affect the API, so grunt update shows no differences - sorta spooky.

Also, in all 8 cases, it was very clear that the instance name should be the capsule tandem name minus "Capsule". Should the instance name just be derived from the capsule's tandem? One of the bullets from https://github.com/phetsims/tandem/issues/124#issuecomment-552446138 was:

> * I like that calling them `element_0` cleans up the call sites for `new PhetioGroup()` a little bit, since you don't need to specify or maintain the element names.

Deriving the name would simplify the call site but still allow for an instance name unique to a particular capsule. It would also help prevent accidentally breaking the API - as mentioned above, these changes aren't validated. Another thing to note - 26 of 28 `new PhetioGroup` sites also exactly duplicate the Group tandem name with the member (27th case was a typo, 28th was legitimate in CCK). So if we wanted to be consistent, this could be a possibility in PhetioGroup, too, perhaps with an option to override if needed, like in CCK.

Here's a patch of what that would look like in EFAC:

<details>

```diff
Index: energy-forms-and-changes/js/intro/view/EFACIntroScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- energy-forms-and-changes/js/intro/view/EFACIntroScreenView.js	(revision 5b8e4f8b3954e30eee7b9d6e02a00d8760b1e5a2)
+++ energy-forms-and-changes/js/intro/view/EFACIntroScreenView.js	(date 1576131502000)
@@ -372,7 +372,7 @@
         return viewAndModelConstrainedPosition;
       };
 
-      const blockNodes = new PhetioGroup( 'blockNode', ( tandem, block ) => {
+      const blockNodes = new PhetioGroup( ( tandem, block ) => {
           return new BlockNode(
             block,
             modelViewTransform,
@@ -408,7 +408,7 @@
       model.blocks.addMemberCreatedListener( blockListener );
 
       // @private {PhetioGroup.<BeakerContainerView>}
-      this.beakerViews = new PhetioGroup( 'beakerProxyNode', ( tandem, beaker ) => {
+      this.beakerViews = new PhetioGroup( ( tandem, beaker ) => {
           const label = beaker.beakerType === BeakerType.WATER ? waterString : oliveOilString;
           return new BeakerContainerView(
             beaker,
@@ -708,7 +708,7 @@
         font: new PhetFont( 20 ),
         maxWidth: EFACConstants.ENERGY_SYMBOLS_PANEL_TEXT_MAX_WIDTH
       } );
-      const linkHeatersCheckboxCapsule = new PhetioCapsule( 'linkHeatersCheckbox', tandem => {
+      const linkHeatersCheckboxCapsule = new PhetioCapsule( tandem => {
         return new Checkbox( new HBox( {
             children: [ linkHeatersText, flameNode ],
             spacing: 5
Index: energy-forms-and-changes/js/intro/model/EFACIntroModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- energy-forms-and-changes/js/intro/model/EFACIntroModel.js	(revision 5b8e4f8b3954e30eee7b9d6e02a00d8760b1e5a2)
+++ energy-forms-and-changes/js/intro/model/EFACIntroModel.js	(date 1576131948000)
@@ -134,7 +134,7 @@
       this.rightBurner = null;
 
       // @private
-      this.rightBurnerCapsule = new PhetioCapsule( 'rightBurner', ( tandem, xPosition ) => {
+      this.rightBurnerCapsule = new PhetioCapsule( ( tandem, xPosition ) => {
         return new Burner(
           new Vector2( xPosition, 0 ),
           this.energyChunksVisibleProperty, {
@@ -154,7 +154,7 @@
       }
 
       // @public {PhetioGroup.<Block>}
-      this.blocks = new PhetioGroup( 'block', ( tandem, blockType, initialXPosition ) => {
+      this.blocks = new PhetioGroup( ( tandem, blockType, initialXPosition ) => {
           return new Block(
             new Vector2( initialXPosition, 0 ),
             this.energyChunksVisibleProperty,
@@ -180,7 +180,7 @@
         );
 
       // @public {PhetioGroup.<BeakerContainer>}
-      this.beakers = new PhetioGroup( 'beaker', ( tandem, beakerType, initialXPosition ) => {
+      this.beakers = new PhetioGroup( ( tandem, beakerType, initialXPosition ) => {
           return new BeakerContainer(
             new Vector2( initialXPosition, 0 ),
             BEAKER_WIDTH,
Index: tandem/js/PhetioCapsule.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/PhetioCapsule.js	(revision a4d97f5e2e7cbfac5faabaf3a99d109053ef2045)
+++ tandem/js/PhetioCapsule.js	(date 1576131415000)
@@ -23,15 +23,17 @@
   const Tandem = require( 'TANDEM/Tandem' );
   const tandemNamespace = require( 'TANDEM/tandemNamespace' );
 
+  // strings
+  const capsuleString = 'Capsule';
+
   class PhetioCapsule extends PhetioObject {
 
     /**
-     * @param {string} instanceTandemName - name of the instance
      * @param {function(tandem, ...):PhetioObject} createInstance - function that creates the encapsulated instance
      * @param {Array.<*>|function.<[],Array.<*>>} defaultArguments - arguments passed to createInstance during API baseline generation
      * @param {Object} [options]
      */
-    constructor( instanceTandemName, createInstance, defaultArguments, options ) {
+    constructor( createInstance, defaultArguments, options ) {
 
       assert && assert( typeof createInstance === 'function', 'createInstance should be a function' );
       assert && assert( Array.isArray( defaultArguments ) || typeof defaultArguments === 'function', 'defaultArguments should be an array or a function' );
@@ -55,7 +57,7 @@
       assert && assert( !!options.phetioType.parameterTypes, 'PhetioCapsuleIO must supply its parameter types' );
       assert && assert( options.phetioType.parameterTypes.length === 1, 'PhetioCapsuleIO must have exactly one parameter type' );
       assert && assert( !!options.phetioType.parameterTypes[ 0 ], 'PhetioCapsuleIO parameterType must be truthy' );
-      assert && assert( options.tandem.name.endsWith( 'Capsule' ), 'PhetioCapsule tandems should end with Capsule suffix' );
+      assert && assert( options.tandem.name.endsWith( capsuleString ), 'PhetioCapsule tandems should end with Capsule suffix' );
 
       super( options );
 
@@ -69,8 +71,8 @@
       // @public (read-only)
       this.instance = null;
 
-      // @private {string}
-      this.instanceTandemName = instanceTandemName;
+      // @private {string} - the PhetioCapsule tandem name without the "Group" suffix
+      this.instanceTandemName = options.tandem.name.slice( 0, options.tandem.name.length - capsuleString.length );
 
       // @public (read-only) {PhetioObject|null} Can be used as an argument to create other archetypes
       this.archetype = PhetioDynamicUtil.createArchetype( this.tandem, createInstance, defaultArguments );
Index: tandem/js/PhetioGroup.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/PhetioGroup.js	(revision a4d97f5e2e7cbfac5faabaf3a99d109053ef2045)
+++ tandem/js/PhetioGroup.js	(date 1576131415000)
@@ -20,15 +20,17 @@
   const Tandem = require( 'TANDEM/Tandem' );
   const tandemNamespace = require( 'TANDEM/tandemNamespace' );
 
+  // strings
+  const groupString = 'Group';
+
   class PhetioGroup extends PhetioObject {
 
     /**
-     * @param {string} prefix - like "particle" or "person" or "electron", and will be suffixed like "particle_0"
      * @param {function} createMember - function that creates a group member
      * @param {Array.<*>|function.<[],Array.<*>>} defaultArguments arguments passed to create during API harvest
      * @param {Object} [options] - describe the Group itself
      */
-    constructor( prefix, createMember, defaultArguments, options ) {
+    constructor( createMember, defaultArguments, options ) {
 
       assert && assert( typeof createMember === 'function', 'createMember should be a function' );
       assert && assert( Array.isArray( defaultArguments ) || typeof defaultArguments === 'function', 'defaultArguments should be an array or a function' );
@@ -52,7 +54,7 @@
       assert && assert( !!options.phetioType.parameterTypes, 'PhetioGroupIO must supply its parameter types' );
       assert && assert( options.phetioType.parameterTypes.length === 1, 'PhetioGroupIO must have exactly one parameter type' );
       assert && assert( !!options.phetioType.parameterTypes[ 0 ], 'PhetioGroupIO parameterType must be truthy' );
-      assert && assert( options.tandem.name.endsWith( 'Group' ), 'PhetioGroup tandems should end with Group suffix' );
+      assert && assert( options.tandem.name.endsWith( groupString ), 'PhetioGroup tandems should end with Group suffix' );
 
       super( options );
 
@@ -69,8 +71,8 @@
       // @public (only for PhetioGroupIO) - for generating indices from a pool
       this.groupMemberIndex = 0;
 
-      // @private
-      this.prefix = prefix;
+      // @private {string} - the PhetioGroup tandem name without the "Group" suffix
+      this.prefix = options.tandem.name.slice( 0, options.tandem.name.length - groupString.length );
 
       // @public (read-only) {PhetioObject|null} Can be used as an argument to create other archetypes
       this.archetype = PhetioDynamicUtil.createArchetype( this.tandem, createMember, defaultArguments );
Index: joist/js/PhetMenu.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- joist/js/PhetMenu.js	(revision e37a77da76e3e9d661111e308f04ee34d12f8752)
+++ joist/js/PhetMenu.js	(date 1576131628000)
@@ -123,7 +123,7 @@
     const self = this;
     Node.call( this );
 
-    const aboutDialogCapsule = new PhetioCapsule( 'aboutDialog', tandem => {
+    const aboutDialogCapsule = new PhetioCapsule( tandem => {
       return new AboutDialog( sim.name, sim.version, sim.credits, Brand, sim.locale, phetButton, tandem );
     }, [], {
       tandem: tandem.createTandem( 'aboutDialogCapsule' ),
@@ -133,7 +133,7 @@
     // only create the singleton if there is options dialog content
     let optionsDialogCapsule = null;
     if ( sim.options.createOptionsDialogContent ) {
-      optionsDialogCapsule = new PhetioCapsule( 'optionsDialog', tandem => {
+      optionsDialogCapsule = new PhetioCapsule( tandem => {
         return new OptionsDialog( sim.options.createOptionsDialogContent, {
           tandem: tandem
         } );
```

</details

**Comment by chrisklus** [comment]
@samreid, @zepumph, and I decided to go ahead with the change proposed in https://github.com/phetsims/tandem/issues/124#issuecomment-564869311.

When converting usages, I found two sites for the new option `phetioDynamicElementName` that I missed in my above search. @zepumph would you like to review? The most notable change to sign off on is for the ChargedParticleGroup in charges-and-fields. Except now I'm noticing there's a discrepancy between `particle` and `chargedParticleNode`. Thoughts?

**Comment by zepumph** [comment]
phetioDynamicElementName looks really awesome. This is great work. I'm happy with the direction we are heading in simplifying the dynamic element containers constructor signature. 

For the ChargedParticleGroup, I decided to just inline the PhetioGroup creation, as it seemed better. It was much simpler for using `phetioDynamicElementName`.

I'm unsure why we prefer `particle` to `chargedParticle`, but if we do then I think we should also prefer `particleNode` to `chargedParticleNode`. I'll leave it up to you!

Even if we remove `phetioDynamicElementName`, I still prefer the group to be created in the model, instead of a static in ChargedParticleGroup.

**Comment by zepumph** [comment]
>I'm unsure why we prefer particle to chargedParticle, but if we do then I think we should also prefer particleNode to chargedParticleNode.

This minor discrepancy is more trouble than its worth to fix at this point.

>Even if we remove phetioDynamicElementName, I still prefer the group to be created in the model, instead of a static in ChargedParticleGroup.

Sounds good past Michael!

I think we should close this issue
