### ISSUE TITLE
Call fromStateObject on argument passed to stateObjectToArgs

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#129]
While working on https://github.com/phetsims/projectile-motion/issues/198, @samreid and I thought that was a bit better of an API. Right now I am calling `fromStateObject` as the first line of `DataPointIO.stateObjectToArgs`. This feels like it should be done by the api.

**Comment by samreid** [comment]
@zepumph thanks for recommending this improvement, it feels like the right direction to go.  I committed an initial draft, and confirmed it is working in the state wrapper for John Travoltage, Charges and Fields, Circuit Construction Kit: AC.  I ran projectile-motion, but received an error--not sure if it was the error you described in the projectile motion issue.

I also marked on TODO with this issue URL in the PhetioStateEngine, please take a look and let me know your thoughts.

**Comment by zepumph** [comment]
* I think that we should name all the parameters the same across usages, like we do for toStateObject and fromStateObject. To me is seems clearest to call it `serializedState`, but that is a bit verbose. I did also like `state` that I saw in projectile motion, even though it is a bit vague. I don't think it should be called `stateObject`, because that doesn't intuitively communicate that the param has gone through `fromStateObject`.
* https://github.com/phetsims/phet-io/commit/f4cab3e2083858069597edb0d6b4ecbfb0269558 arguable doesn't belong in this issue, but I think it looks acceptable. I did a similar thing for PM in https://github.com/phetsims/phet-io/issues/1570. 

Thanks for implementing this.

**Comment by zepumph** [comment]
- [ ] There are TODOs pointing to this issue that I think have been reviewed, but not deleted.

**Comment by zepumph** [comment]
> There are TODOs pointing to this issue that I think have been reviewed, but not deleted.

I think we can delete both of the TODOs pointing to this issue from `getState`, so I'm going to do that now. @samreid please let me know if you disagree.

**Comment by samreid** [comment]
The following parameter names are most prevalent in the code and sound reasonable to me, and aren't too verbose:

```js
fromStateObject( stateObject ) {}
stateToArgsForConstructor( state ) {}
```

After the above commits, I revised the remaining usages to use this new standard.  @zepumph can you please review?

**Comment by zepumph** [comment]
Looks great. I will also be looking at many of these methods in https://github.com/phetsims/phet-io/issues/1685 when I revert the original commits in the issue (lol). Your names look great though. I will keep that naming over there.
