### ISSUE TITLE
PhetioCapsule: move defaultArguments to options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#130]
Noted during review of https://github.com/phetsims/phet-io-wrappers/issues/288.

The constructor signature for `PhetioSingleton` (EDIT: now `PhetioCapsule`) is:

```js
  class PhetioSingleton extends PhetioObject {

    /**
     * @param {function(tandem, ...):PhetioObject} createInstance - function that creates a group member
     * @param {Array.<*>|function.<[],Array.<*>>} defaultArguments arguments passed to create during API harvest
     * @param {Object} [options] - describe the Singleton itself
     */
    constructor( createInstance, defaultArguments, options ) {
```

There are currently 5 occurrences of `new PhetioSingleton`.  4 of them use `[]` for the `defaultArguments` argument.  If this is typical....

Recommended  to move `defaultArguments`  to `options`, and set its default value to `[]`.  It will improve readability of call sites.

**Comment by pixelzoom** [comment]
After discussing with @chrisklus on Slack, I clarified `defaultArguments` doc in the above commit.  But we still have a ways to go, and I think some examples are needed.  This type expression is incomprehensible to me:

`@param {Array.<*>|function.<[],Array.<*>>} defaultArguments - arguments passed to createInstance during API baseline generation`

So if `defaultArguments` is a function, then it's first arg must be an empty array? Why?

**Comment by zepumph** [comment]
I think the type doc should be `{Array.<*>|function():Array.<*>}`, does that make more sense to you @pixelzoom?

**Comment by pixelzoom** [comment]
Yes, that makes much more sense - an array, or a function that returns an array.

**Comment by zepumph** [comment]
@samreid @chrisklus I agree here. I think that default arguments should be an option. I know I have said this previously, and we decided it was nice as  a parameter because even when blank, it is good to think through what args need to be passed to the parameter.

Perhaps it is better in the options these days since so many of the usages are `[]`, and we now have assertions keeping us from omitting defaultArguments, like 

```js
        assert && assert( create.length === defaultArgs.length + 1, 'mismatched number of arguments' );

```

**Comment by pixelzoom** [comment]
Fine with closing this. But if it's going to be a required parameter, could we get the type expression corrected in all places where it appears?

It still looks incorrect to me in `PhetioDynamicElementContainer`:

`@param {Array.<*>|function.<[],Array.<*>>} defaultArguments arguments passed to create during API harvest`

It was changed to this in the subclasses:

`{Array.<*>|function():Array.<*>} defaultArguments - arguments passed to createElement when creating the archetype`

**Comment by samreid** [comment]
I revised the JSDoc, ready for re-review.

**Comment by pixelzoom** [comment]
👍🏻 closing
