### ISSUE TITLE
rename phetioDynamicElementArchetype -> phetioArchetype?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#131]
The first one is a bit more clear and verbose, but this question came up while working on a few dynamic element issues and I wanted to see if anyone thought it would  be substantially better.

**Comment by samreid** [comment]
I prefer `phetioArchetype`, thanks!

**Comment by chrisklus** [comment]
as do I!

**Comment by zepumph** [comment]
I feel like we haven't done a very good job of conveying the "boolean" nature of many of our phetio options from their names. How about instead `phetioIsArchetype`?

**Comment by chrisklus** [comment]
Ah, that's nicer, yes. I think I remember discussing in a dev meeting a while ago that adding "is" to a boolean value for clarity is a plus.

**Comment by samreid** [comment]
Yes, `phetioIsArchetype` sounds good, thanks!

**Comment by chrisklus** [comment]
Rename complete, assigning to @samreid or @zepumph to review and close if appropriate.

**Comment by samreid** [comment]
I did a spot check and didn't see any trouble.  Well, I couldn't figure out why the "before" commit in https://github.com/phetsims/circuit-construction-kit-ac/commit/e8b2873921ccaa66d2b7db6d1bdb823a30cb4e08 had `phetioIsArchetype` in the wrong alphabetical order, but that's all.  Closing.

**Comment by zepumph** [comment]
The find replace didn't change the ordering of the key in the baseline file, so I will run grunt update now.

**Comment by chrisklus** [comment]
Nice catch @zepumph, thanks!
