### ISSUE TITLE
Opt out of state for dynamic elements

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#132]
Found while working on https://github.com/phetsims/energy-forms-and-changes/issues/294 and https://github.com/phetsims/phet-io/issues/1584.

Since we are using PhetioGroups as an API validatable way for startup customization (like query parameters), there are now cases where all group members are created on startup, and don't need to be cleared out by PhetioGroup during setState. This use-case also applies to PhetioCapsule.

PhetioGroup and PhetioCapsule are both `phetioState: false` by default, because as PhetioObjects themselves, they have no stateful properties since they are just containers. So since `phetioState: false` is already in use and doesn't apply to its children, we needed a way to indicate that state should be ignored for the children, which simply meant telling the phetioStateEngine to not clear them during setState. @zepumph, @samreid, and I came up with the option `supportsDynamicState`.

**Comment by chrisklus** [comment]
Assigning to @zepumph for review.

**Comment by zepumph** [comment]
This is all looking really nice. I think we will continue discussion in https://github.com/phetsims/phet-io/issues/1590.  I updated some documentation. Anything else here? Feel free to close.

**Comment by chrisklus** [comment]
Thanks @zepumph, closing.
