### ISSUE TITLE
unsafe merge in PhetioObject.LinkedElement constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#133]
PhetioObject.LinkedElement constructor has this call to `merge`:

```js
      super( merge( {
        phetioType: LinkedElementIO,
        phetioReadOnly: true, // References cannot be changed

        // By default, this linked element's baseline value is the overridden value of the coreElement. This allows
        // the them to be in sync by default, but also allows the linked element to be overridden in studio.
        phetioFeatured: coreElement.phetioFeatured
      }, options ) );
```

This makes it possible for the caller to change `phetioType`, `phetioReadOnly` -- which I suspect would result in badness -- as well as `phetioFeatured`.  

Please add assertions that these options are not set by the client.

**Comment by zepumph** [comment]
Agreed! Nice catch. Please review and close if good.

**Comment by pixelzoom** [comment]
I said:
> This makes it possible for the caller to change `phetioType`, `phetioReadOnly` -- which I suspect would result in badness -- as well as `phetioFeatured`.

Reviewing https://github.com/phetsims/tandem/commit/e767521b5b36f1ed23be0b84f7d0a2ee103eb38b, I see that `phetioReadOnly` and `phetioFeatured` are now controlled by LinkedElement.  Why is this not also the case for `phetioType`?  Is there a use case for allowing the client to set something other than `phetioType: LinkedElementIO`?  Should that use case be documented?

**Comment by zepumph** [comment]
I see this as no different as any usage of `phetioType`. It supports you passing in your own LinkedElementIO and screwing things up if you do it wrong. Pulling that out of options would disallow the ability for future subtyping of `LinkedElementIO`. If you disagree please assign @samreid for comment and discussion.

**Comment by pixelzoom** [comment]
Thanks for the clarification - that wasn't apparent from your comments or commit.  Closing.
