### ISSUE TITLE
LinkedElement: incorrect type expression for param coreElement

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#134]
In PhetioObject.LinkedElement,  I suspect an incorrect type expression for param `coreElement`.  The type expression is `{Object}`, but the assertion requires `{PhetioObject}`.

```js
    /**
     * @param {Object} coreElement
     * @param {Object} [options]
     */
    constructor( coreElement, options ) {
      assert && assert( !!coreElement, 'coreElement should be defined' );
      assert && assert( coreElement instanceof PhetioObject, 'coreElement should be PhetioObject' );
```

**Comment by pixelzoom** [comment]
Ditto for param `object` of PhetioObject.metaData:

```js
@param {Object} object - used to get metadata keys
```

There's no assertion this time, but the implementation sure looks like this needs to be `{PhetioObject}`.

**Comment by zepumph** [comment]
Does this documentation help the groking?

**Comment by pixelzoom** [comment]
👍
