### ISSUE TITLE
Convert all IOTypes to es6

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#137]
From https://github.com/phetsims/phet-io/issues/1371, we are pretty close, but there are still a few functions that could be arrow functions and perhaps other things. @chrisklus does this seem like something you could take care of at a low priority? 

Recently I ran into this in NodeIO.

**Comment by samreid** [comment]
This can be addressed while we work on the proposal in https://github.com/phetsims/tandem/issues/211.  On hold until that issue is further along.

**Comment by zepumph** [comment]
https://github.com/phetsims/tandem/issues/211 is closed. I think we can close this issue. Thanks for all that work @samreid.
