### ISSUE TITLE
PhetioObject.phetioStartEvent should not overload `data` parameter type

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#138]
Promoting TODO from @samreid.

@samreid instead of letting data be an object or a function or null, what about providing it through options?

```
options = merge( {

  // {Object|null} - the data
  data: null,

  // {function():Object|null} - function that, when called get's the data.
  getData: null

} );
```

There are only 12 usages of `phetioStartEvent` with that second arg, so I don't really care either way. @samreid does this feel better than overloading the second arg?

Honestly I think it is fine the way it is. Feel free to close, implement, or assign back to me to do. I'm happy any way!

**Comment by samreid** [comment]
Our team is moving more towards providing options for this kind of pattern, perhaps we can also `assertMutuallyExclusiveOptions` on them.  

> // {function():Object|null} - function that, when called get's the data.

I think it's important to add documentation that the function is only called when the item is instrumented, and this an attempt to improve performance by avoiding work for uninstrumented instances.

Could we get an additional boost in PhET brand by stripping out lines of code with `phetioStartEvent` and `phetioEndEvent` (like we do with `assert`?)

**Comment by zepumph** [comment]
Alright we will move forward with providing two different, mutually exclusive options. (though they aren't really mutually exclusive because you can always just omit both).

>Could we get an additional boost in PhET brand by stripping out lines of code with phetioStartEvent and phetioEndEvent (like we do with assert?)

see https://github.com/phetsims/phet-io/issues/1600

**Comment by zepumph** [comment]
@chrisklus can you please review this change. I think the key thing here is to triple check (because I already double checked) that I got every usage site, because otherwise what used to be data would be silently coerced into the options. That would be less than ideal. Thanks!

**Comment by zepumph** [comment]
I forgot one that had broken the mirror inputs wrapper for the last week. Like I said above. . . very finicky and hard to catch! @chrisklus please see if there are any more.

**Comment by chrisklus** [comment]
Looks good @zepumph. I double checked all usage sites as well and couldn't find any that didn't conform to the new signature. Back to you if there's anything before closing.
