### ISSUE TITLE
assert static IO type functions aren't prototype functions

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#142]
This is a sloppy error that @samreid @chrisklus and @zepumph found on `NumberProperty`. We think it wise to add validation to make sure this doesn't happen again.

**Comment by zepumph** [comment]
@samreid does this feel good to you? Are there any others that need assertions. I don't think so.

**Comment by samreid** [comment]
These changes look great, do you think `stateToArgsForConstructor` should be checked?  After we decide on that, this issue can be closed.

**Comment by zepumph** [comment]
I originally thought no, but your comment caused me to search for the number of usages, and there are already 12. So I think that certainly it is a valuable check to do too.
