### ISSUE TITLE
Guard all of phetioStartEvent and phetioEndEvent with phetio checks

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#143]
@samreid and I noticed that `if ( PHET_IO_ENABLED && this.isPhetioInstrumented() ) {` was only being used in `phetioStartEvent` and `phetioEndEvent` to guard on `dataStream.start` and `dataStream.end` calls, but the rest of the code in those functions is running in phet brand. In `phetioStartEvent`, this means at least an unnecessary object allocation and merge call.

**Comment by chrisklus** [comment]
We went ahead and pushed some changes that moved the checks to guard the whole function, and took a few performance measurements.

Over three tests, we measured an average increase between garbage collections of ~80 ms (with a total garbage collection cycle of ~1000 ms). @zepumph what do you think?

**Comment by zepumph** [comment]
So if I understand, there are two things happening right now. The first is that we think the PhetioObject methods should be no ops if an instance is uninstrumented, or if we aren't running in phet-io brand. This sounds really really nice.

The second thing that I'm seeing is more guarding on Action and Property events to prevent the noop function from even running. I do not think that this is needed, and I would be surprised if that was contributing much to the speed up, am I wrong? If so I'm happy to leave it as is and close.

Everything else looks good.

**Comment by samreid** [comment]
We didn't measure the exact impact of the extra guard, but it seems like a nice thing to do since Property and Action are called many times, and it saves unnecessary object allocations.

**Comment by zepumph** [comment]
Agreed! Especially in those locations, which are passing data to the no-op each time. I have switched teams. I'm all team-optimization! YAY. Closing
