### ISSUE TITLE
ReferenceIO is violating API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#145]
ReferenceIO is violating the API for `toStateObject`.   It's supposed to return `{Object}` but is returning `{string}`:

```js
    /**
     * Return the json that ReferenceIO is wrapping.  This can be overridden by subclasses, or types can use ReferenceIO type
     * directly to use this implementation.
     * @param {Object} o
     * @returns {Object}
     * @public
     */
    static toStateObject( o ) {
      validate( o, this.validator );
      return o.tandem.phetioID;
    }
```

Also recommended to add an assertion somewhere to catch this type of problem.

**Comment by zepumph** [comment]
I think this is a failure of api documentation, and not a failure of ReferenceIO. That serialization has been working well for us thus far, so I updated the ObjectIO docs. @samreid will you please review.

**Comment by pixelzoom** [comment]
ReferenceIO fromStateObject is also violating the API.  It's expecting `{string}` for `stateObject`. And `phetioEngine.hasPhetioObject` takes a string.

```js
    /**
     * Decodes the object from a state, used in PhetioStateEngine.setState.  This can be overridden by subclasses, or types can
     * use ReferenceIO type directly to use this implementation.
     * @param {Object} stateObject
     * @returns {Object}
     * @throws CouldNotYetDeserializeError
     * @public
     */
    static fromStateObject( stateObject ) {
      if ( phetioEngine.hasPhetioObject( stateObject ) ) {
        const phetioObject = phetioEngine.getPhetioObject( stateObject );
        validate( phetioObject, this.validator );
        return phetioObject;
      }
      else {
        throw new CouldNotYetDeserializeError();
      }
    }
```

**Comment by pixelzoom** [comment]
@zepumph said:
> ... I updated the ObjectIO docs

You update the doc for ObjectIO.  It's still incorrect in ReferenceIO and most of the IO subtype definitions that I spot checked.

**Comment by pixelzoom** [comment]
First param for ReferenceIO toStateObject is still wrong:

`@param {Object} o`

should be:

`@param {PhetioObject} o`

... according to ObjectIO doc.  Similar error in many IO type definitions.

**Comment by zepumph** [comment]
I updated a few more doc places. Sorry about that.

**Comment by pixelzoom** [comment]
ObjectIO doc is now:

```js
 /**
     * Return the json that ObjectIO is wrapping.  This can be overridden by subclasses, or types can use ObjectIO type
     * directly to use this implementation.
     * @param {PhetioObject} o
     * @returns {*} - most of the time it is an Object with data inside, but there are some other cases like NullableIO and ReferenceIO
     * @public
     */
    static toStateObject( o ) {
```

If the return type is `{*}`, then "Return the json" is incorrect.

**Comment by pixelzoom** [comment]
This ObjectIO doc looks incorrect too.  Should return type be `{PhetioObject}`?

```js
    /**
     * Decodes the object from a state, used in PhetioStateEngine.setState.  This can be overridden by subclasses, or types can
     * use ObjectIO type directly to use this implementation.
     * @param {*} o - whatever was returned from the toStateObject method
     * @returns {Object}
     * @public
     */
    static fromStateObject( o ) {
      return o;
    }
```

**Comment by samreid** [comment]
The changes look good so far, reassigning @zepumph to please continue on @pixelzoom requests.

**Comment by pixelzoom** [comment]
My understanding after working in BLL and Natural Selection, and talking with @zepumph, is that `fromStateObject` is overloaded.  Sometimes it returns a PhetioObject.  Sometimes (like in BunnyIO) it returns {Object}, and object literal.  It would be nice if `fromStateObject` were not overloaded in this way.  If that's not possible, it should be clearly documented (and verified) what is returned, and when.

**Comment by zepumph** [comment]
I updated ObjectIO documentation further above. Short of rewriting these methods, I feel like the best documentation is in the phet-io-instrumentation-guide. Please review.

**Comment by pixelzoom** [comment]
👍 Closing.
