### ISSUE TITLE
how to create tandem names for collections > 1D

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#146]
In https://github.com/phetsims/normal-modes/issues/17, I ran into a problem with creating tandem names for a 2D array of items.    The code looks like this, in  TwoDimensionsModel.js:

```js
      // @public {NumberProperty[][]}
      this.modeXAmplitudeProperty = new Array( NormalModesConstants.MAX_MASSES_ROW_LEN );
...
          this.modeXAmplitudeProperty[ i ][ j ] = new NumberProperty( TwoDimensionsConstants.INIT_MODE_AMPLITUDE, {
            tandem: tandem.createTandem( 'modeXAmplitudeProperty' + i + '_' + j ),
            range: new Range( TwoDimensionsConstants.MIN_MODE_AMPLITUDE, Number.POSITIVE_INFINITY )
          } );
```

This fails in Tandem.js with this assertion:

```
assert.js?bust=1581129817087:22 Uncaught Error: Assertion failed: name should match the regex pattern: modeXAmplitudeProperty0_0
    at window.assertions.assertFunction (assert.js?bust=1581129817087:22)
    at new Tandem (Tandem.js?bust=1581129817174:57)
    at Tandem.createTandem (Tandem.js?bust=1581129817174:201)
    at new TwoDimensionsModel (TwoDimensionsModel.js?bust=1581129817174:80)
    at TwoDimensionsScreen.createModel (TwoDimensionsScreen.js?bust=1581129817174:35)
    at TwoDimensionsScreen.initializeModel (Screen.js?bust=1581129817174:254)
    at Array.<anonymous> (Sim.js?bust=1581129817174:863)
    at Sim.js?bust=1581129817174:874
```

Relevant code in Tandem.js:

```js
   /**
     * Returns the regular expression which can be used to test each term. The term must consist only of alpha-numeric
     * characters or tildes.
     * @returns {RegExp}
     * @protected
     */
    getTermRegex() {
      return /^[a-zA-Z0-9~]+$/; // TODO: eliminate ~ once GroupTandem has been deleted, see https://github.com/phetsims/tandem/issues/87
    }
```

After Slack discussion with @chrisklus, the conclusion is that:
* creating tandem names like this has been considered for the 1D case
* it has not been considered for the > 1D, and we need to address this

**Comment by samreid** [comment]
My instinct is that we can reintroduce `_` as a legal tandem token once we have eliminated all of the legacy pattern.

**Comment by zepumph** [comment]
I think that `_` has been conventionally reserved for PhET-iO dynamic elements long enough that I would like to discuss the possibility of using another character. Would `x` work, like `2x3` or maybe a hyphen `-2-3`?

**Comment by samreid** [comment]
Good point, `_` is still in use for `PhetioGroup` so we should use `x` or `-`.  @pixelzoom does that sound OK?

**Comment by pixelzoom** [comment]
I'm not really clear on how or where you're using underscore.  But hypen sounds better that 'x' to me.

**Comment by samreid** [comment]
The underscore is used here:

https://github.com/phetsims/tandem/blob/f7b8ba03a15c0f46693090023b8488847c83f0e8/js/PhetioGroup.js#L206

**Comment by pixelzoom** [comment]
If phetio.PhetioIDUtils.GROUP_SEPARATOR is reserved for that usage in PhetioGroup, shouldn't 
Tandem `getTermRegex` have something that prevents it from being used there?  If I had been trying to make this change without the benefit of your collective knowledge, I probably would have just added '_' to `getTermRegex`, and would have had no idea that it was reserved for use elsewhere.

**Comment by zepumph** [comment]
So perhaps it would be helpful to have a note in Tandem.getTermRegex that says (even though it is already excluded from the regex itself) to not add an underscore here, and to see `DynamicTandem.getTermRegex` (a subtype), for details?

**Comment by pixelzoom** [comment]
A note is only useful if you see it, it cannot prevent programming errors.  How about a validator for the tandem name, that can be overridden by subclasses?

**Comment by zepumph** [comment]
>A note is only useful if you see it, it cannot prevent programming errors. How about a validator for the tandem name, that can be overridden by subclasses?

Thanks for the `@override` annotation. I feel like we have that with `getTermRegex`. I am trying to figure out what more you feel like is needed here? Will you please explain?

**Comment by pixelzoom** [comment]
`getTermRegex` is not a validator.  It's getting something that's used by an assertion in Tandem constructor.  Why is it not appropriate to use the same Validator pattern used elsewhere (in Property, etc) for params and options?

**Comment by zepumph** [comment]
So you recommend replacing this line:

```
assert && assert( this.getTermRegex().test( name ), `name should match the regex pattern: ${name}` );
```

With this one?

```
      validate( name, { isValidValue: v => this.getTermRegex().test( v ) } );

```

That is totally fine with me, it feels like the exact same thing save that we don't get a custom assertion message. 

Besides that is there anything else for this issue?

**Comment by pixelzoom** [comment]
> So you recommend replacing this line: ...

Nah... I agree, the assertion is better.  I had suggested that it would be good to prevent chars that are reserved for use elsewhere from being introduced where they shouldn't be, but apparently that's not possible.  So I guess we have to rely on documentation.  

> Besides that is there anything else for this issue?

I don't see any commit that address the reported problem.  @samreid proposed some possibilities in https://github.com/phetsims/tandem/issues/146#issuecomment-584700595, but I don't see any indication that a decision was made or implemented.

**Comment by zepumph** [comment]
@samreid which of these do you think would be better as a convention (or your own thoughts)

1. `modeXAmplitudeProperty-2x3`
2. `modeXAmplitudeProperty2x3`
3. `modeXAmplitudeProperty-2-3`
4. `modeXAmplitudeProperty2-3`
5. ?????

I think I like (1) best myself. The "x" feels very idiomatic as a replacement for "by", as in "two by three".

**Comment by pixelzoom** [comment]
"2x3" looks like a dimension, not an index into a multidimensional array. 

Is this crazy?  `modeXAmplitudeProperty[2,3]`

**Comment by zepumph** [comment]
I'm also wondering if reserving `_` for dynamic tandems is too strict. Originally we were only reserving them for groups (like this use case), and then groups morphed into our dynamic element strategy. Another option is to investigate what it would take to support "static groups" that could potentially use an underscore. This was mentioned above too.

**Comment by samreid** [comment]
`modeXAmplitudeProperty[2,3]` seems reasonable to me.  @zepumph what do you think?

**Comment by zepumph** [comment]
Sounds great! Go for it @pixelzoom. This should probably be documented somewhere in the "how-to" docs as a convention for how to name items that are N dimensional in a grid.

**Comment by zepumph** [comment]
How's that @samreid?

**Comment by pixelzoom** [comment]
Verified by using this to address https://github.com/phetsims/normal-modes/issues/17.   Thanks!

Feel free to close after this is addressed in the "How to" doc.

**Comment by zepumph** [comment]
Updated in https://github.com/phetsims/phet-io/commit/93367037719708d83180e3225cd1073d1160b92c

**Comment by pixelzoom** [comment]
Reopening.  Your example in phetsims/phet-io@9336703 made me wonder...  Should there be some statement about whether numbering is 0-based or 1-based?   In normal-modes, it's 0-based.  In your example, it's 1-based.

**Comment by zepumph** [comment]
Right. What do you think the convention should be? Should we ask designers?

**Comment by pixelzoom** [comment]
I will defer to the designers.  But if they don't have a strong preference, my vote would be for 0-based indexing for collections, primarily so we don't have continually remember to add `+1` in code.   If we use 1-based indexing, then some way to automatically identify uses of `0` index would be nice.

**Comment by samreid** [comment]
Even though we chose to go with "1 based" in query strings, that is a substantially different case for a different population, and we should choose 0-based indexing here.

**Comment by zepumph** [comment]
* Clearly document whether or not it is 0-based or 1-based
* For this normal modes case it makes sense to be 1-based because this sim uses that visually too:
![image](https://user-images.githubusercontent.com/6856943/77096308-05cc4100-69c4-11ea-8c8f-7caa2fff8216.png)

* PhetioGroups are currently always 0-based indexed, but @pixelzoom mentioned that potentially that could be problematic in cases (like if normal-modes were dynamic).


We think that by default, 0-based makes sense, but we noted that there will be some usages that will be 1-based, and no matter each should be clearly documented as to which it is. This will make Studio more clear.

Places where we use 1-based:
* screen query parameters
* in this normal-modes case
* Potentially in games we may need to this to make it clearer to clients, but currently it is 0-based. (like in https://github.com/phetsims/reactants-products-and-leftovers/issues/57)

@pixelzoom currently in normal-modes is it 1-based in the code? @ariel-phet made it seem like these should be 1-based.

I will update documentation in the "how-to" doc.

**Comment by pixelzoom** [comment]
> @pixelzoom currently in normal-modes is it 1-based in the code? @ariel-phet made it seem like these should be 1-based.

Tracking in https://github.com/phetsims/normal-modes/issues/55.

**Comment by zepumph** [comment]
Documentation updated above. Closing
