### ISSUE TITLE
Node.prototype.tandem should never be null

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#148]
Right now you can encounter cases were a Node never passes in options, and never mutates, and thus tandem is never defined. I think that for flexibility we should make tandem always defined.

**Comment by zepumph** [comment]
@samreid does this feel like an appropriate solution. During a slack discussion, @pixelzoom mentioned that potentially we may want to fill in all defaults in the constructor. This is because of the `Node` case where you pass no options to the constructor and don't call `mutate`. Do you think that is warranted? To me the only item that seems valuable to provide here (and to take up space in all brands) is `this.tandem`. What do you think?

**Comment by zepumph** [comment]
This was brought up because of instrumentation of ABSwitch in https://github.com/phetsims/sun/issues/559. Ideally we could use any Node instance's `tandem`, to create substructure.

**Comment by pixelzoom** [comment]
Setting  `this.tandem = DEFAULTS.tandem` does get me past the problem that I encountered. But what about all of the other fields?  Doesn't `DEFAULTS` imply that these will be the default values used? If I don't call `super(..., options )` or `this.mutate( options )`, then I don't I have a malformed PhetioObject?

**Comment by zepumph** [comment]
@samreid, the best I remember about the reason why things are this way is to conserve memory, since we assumed when creating PhetioObject that it was only needed in phet-io brand (maybe even with instrumented items?!?!). We are now finding that to be different. Should we populate the constructor initializations with default values instead of making them `null`?

**Comment by samreid** [comment]
At one point, did we have an assertion that either `options` are passed in to the constructor or that `mutate(options)` is called?  Should we have something like that?  Then we never have to assign incorrect values (which may be read at the wrong time), and we can guarantee that attributes are assigned at some point?

**Comment by pixelzoom** [comment]
I'm not sure how you could pull that off with an assertion. Where would such an assertion live?

**Comment by zepumph** [comment]
After discussing with @samreid and @chrisklus, we decided that defaults should be propagated to PhetioObject all fields for options in the constructor. We found that this didn't take up any more memory.

@samreid mentioned that this will now cause an "incorrect" state for PhetioObject fields in the following case for Node:
```js
Node.call( this );

if( this.phetioFeatured ){ //do something
}

this.mutate( { tandem: tandem.createTandem('fdsa'), phetioFeatured: true } );

```

But we decided it was alright because this is the same behavior (potential inconsistency) as all Node option keys like in:


https://github.com/phetsims/scenery/blob/master/js/nodes/Node.js#L362-L380


@pixelzoom will you please review.

**Comment by pixelzoom** [comment]
There's still one difference here.  If either `super( options )` or `this.mutate( options )` is called then `phetioComponentOptions` will be:

```js
320 this.phetioComponentOptions = options.phetioComponentOptions || EMPTY_OBJECT;
```

If neither is called, then it will be `null`:

```js
160    this.phetioComponentOptions = DEFAULTS.phetioComponentOptions;
```

Can we change DEFAULTS.phetioComponentOptions to `EMPTY_OBJECT`?   That would ensure that the behavior is the same in all cases, and also eliminate the logic on line 320.

**Comment by zepumph** [comment]
That is excellent. Done above.
