### ISSUE TITLE
improve doc and robustness of PhetioGroup createMember

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#149]
In https://github.com/phetsims/beers-law-lab/issues/244, I was having trouble with mismatched number of arguments when creating a PhetioGroup.   Digging into PhetioGroup superclass PhetioDynamicElementContainer, I found this:

```
        // createElement expects a Tandem as the first arg
        assert && assert( createElement.length === defaultArguments.length + 1, 'mismatched number of arguments' );
```

`PhetioGroup` first parameter is:

```js
@param {function} createMember - function that creates a group member
```

Apparently that function must have `{Tandem} tandem` as its first parameter.  That's not indicated in the JSdoc, and there doesn't seem to be anything that checks the type of the first parameter.  It just blows up I the above assertion.   

Let's improve the doc and robustness of this.

**Comment by samreid** [comment]
I improved the JSDoc type docs in the commit.

> That's not indicated in the JSdoc, and there doesn't seem to be anything that checks the type of the first parameter.

In JavaScript, it is possible to check the number of declared parameters to a function via `function.length`, but there is no way to check the declared types of the parameters.

@pixelzoom this issue is ready for review.

**Comment by pixelzoom** [comment]
> but there is no way to check the declared types of the parameters.

I don't follow.  What's wrong with this? 

);

```diff
    if ( Array.isArray( defaultArguments ) ) {

      // createElement expects a Tandem as the first arg
      assert && assert( createElement.length === defaultArguments.length + 1, 'mismatched number of arguments' );
+     assert && assert( defaultArguments[ 0 ] instance of Tandem, 'first argument must be a Tandem' );
    }
```

**Comment by samreid** [comment]
The `defaultArguments` does not include the `Tandem`.  The `Tandem` is automatically created later by the `PhetioDynamicElementContainer`.  For instance:

```js
    // defaultArguments, passed to createElement during API harvest
    const defaultArguments = [ {} ];

    super( createElement, defaultArguments, options );
```

**Comment by pixelzoom** [comment]
OK, got it. Client defines the `createElement` function, so client would need to handle validation of the `tandem` arg therein.  

Doc improvements look good. 

Closing.
