### ISSUE TITLE
clean up terminology in PhetioGroup class hierarchy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#150]
It would be nice to clean up terminology.   E.g. PhetioGroup `createMember` vs PhetioDynamicElementContainer `createElement` for the same constructor arg.

**Comment by samreid** [comment]
We renamed PhetioGroup.member => PhetioGroup.element in https://github.com/phetsims/tandem/issues/170.  Ready for review.

**Comment by zepumph** [comment]
I think @samreid meant to assign the creator of this issue here.

**Comment by pixelzoom** [comment]
👍🏻 closing
