### ISSUE TITLE
Preferred way to get a general phetioID

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#151]
From https://github.com/phetsims/tandem/issues/108.

The way to get a `general` phetioID is with `phetio.PhetioIDUtils.getGeneralID`. These examples show getting `screenProperty` in Studio.js line 30:

```js
const screenPropertyID = window.phetio.PhetioIDUtils.getGeneralID( phetio.Client, 'screenProperty' );
```

Now, since `general` has been split into `general.model`, `general.view`, and `general.controller`, it looks a little more awkward:

```js
const screenPropertyID = window.phetio.PhetioIDUtils.getGeneralID( phetio.Client, 'model', 'screenProperty' );
// or
const screenPropertyID = window.phetio.PhetioIDUtils.getGeneralID( phetio.Client, 'model.screenProperty' );
```

During that refactor, I considered omitting `PhetioIDUtils.getGeneralID` and adding `PhetioIDUtils.getGeneralModelID`, `PhetioIDUtils.getGeneralViewID`, and `PhetioIDUtils.getGeneralControllerID`, but that felt like a step in the wrong direction.

In discussion with @samreid, we came up with a few alternatives. All usages have `phetio.PhetioIDUtils` and `phetio.Client`, so instead of passing in `Client` to `PhetioIDUtils`, we could move the method(s) to Client.js:

```js
const screenPropertyID = phetio.Client.getGeneralModelID( 'screenProperty' );
const screenPropertyID = phetio.Client.getGeneralID( 'model.screenProperty' );
```

The pro of using something like these methods is that it doesn't duplicate `general`, and in the first case doesn't duplicate `model`.

All `getGeneralID` does is get the sim name from `Client` and add `general`, so a phet-io client could also get the sim name directly from `Client`. This option looks the most like a phetioID but duplicates `general` and `model`. It's currently called `CAMEL_CASE_SIMULATION_NAME` but we could rename it to something nicer:

```js
const screenPropertyID = `${phetio.Client.CAMEL_CASE_SIMULATION_NAME}.general.model.screenProperty`;
const screenPropertyID = `${phetio.Client.ROOT_ID}.general.model.screenProperty`;
```

Assigning @zepumph and @pixelzoom for some more opinions.

**Comment by samreid** [comment]
In my opinion, the current pattern is unclear and obfuscates what is happening:

```js
window.phetio.PhetioIDUtils.getGeneralID( phetio.Client, 'model', 'screenProperty' )
```

And it would be clearer to use string interpolation like so:
```js
`${phetio.Client.ROOT_ID}.general.model.screenProperty`
```

The tandem names are not an "implementation detail" to be shielded behind methods and abstraction, but rather an "API feature" which should be leveraged.

**Comment by pixelzoom** [comment]
Why are you not using `Tandem.GENERAL`? 

Imo, string interpolation is incorrect and lazy, and this is preferable:

`Tandem.GENERAL.createTandem( 'model' ).createTandem( 'screenProperty' )`

**Comment by samreid** [comment]
We are discussing how clients should construct `phetioIDs` on the wrapper-side, not how simulations construct `Tandems` in the simulation-side.

**Comment by pixelzoom** [comment]
I have no experience with the client side. Unassigning.

**Comment by zepumph** [comment]
>>`${phetio.Client.ROOT_ID}.general.model.screenProperty`

That sounds really nice to me! It is easy enough to just use `Client.CAMEL_CASE_SIMULATION_NAME` in the cases where we have multiple sims, but in general our clients aren't going to use that function, and will just hard code it, so why don't we!

**Comment by samreid** [comment]
I addressed the cases I could easily discover.  The old pattern doesn't appear in the wrapper template, so that didn't need to be updated.  I was able to delete `PhetioIDUtils.getGeneralID`.  Ready for review, please close if all is well.

**Comment by zepumph** [comment]
Excellent! Thanks
