### ISSUE TITLE
make PHET_IO_ENABLED more robust

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#152]
This was discussed at 3/12/2020 phet-io meeting.

In Tandem.js:

```js
21 const PHET_IO_ENABLED = _.hasIn( window, 'phet.phetio' );

430 Tandem.PHET_IO_ENABLED = PHET_IO_ENABLED;
```

This assumes that global `window.phet.phetio` will only exist in PhET-iO branded sims.  That assumption is not verified, and while currently true, could easily change in the future. 

Please cross-check with the brand in case “phet.phetio” gets introduced for non-PhET-iO brands.

**Comment by zepumph** [comment]
Let's cover this over in https://github.com/phetsims/tandem/issues/153. Closing
