### ISSUE TITLE
incorrect type expression for @param listener

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#155]
In PhetioObject, there are incorrect type expressions for `addMemberCreatedListener`, `removeMemberCreatedListener`, `addMemberDisposedListener`, and `removeMemberDisposedListener`:

`* @param {function} listener`

All of these listeners apparently have 1 parameter, which is the member.

**Comment by pixelzoom** [comment]
PhetioGroup `forEach` doc is also incorrect.  `param {function} action` takes one parameter.

**Comment by zepumph** [comment]
Implemented above. Note though that potentially some of these will be removed as part of https://github.com/phetsims/charges-and-fields/issues/177 (still out for discussion). I added parameter when appropriate to all function parameters to PhetioGroup methods. Closing

**Comment by pixelzoom** [comment]
Reopening. Now we have a terminology problem, see https://github.com/phetsims/tandem/issues/156#issuecomment-603977930.  PhetioGroup deals with "member" and you've described the callback parameter as "element".   I'd like to see PhetioGroup use "element" terminology, but that's still up for discussion in #156.  So in the meantime, I've changed "element" to "member" so that PhetioGroup is at least internally consistent.  @zepumph please review.
