### ISSUE TITLE
change PhetioGroup API to refer to "element" ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#156]
I'm not wild about different terminology in `PhetioGroup` vs its superclass `PhetioDynamicElementContainer`, especially in method and parameter names.  PhetioGroup refers to "member", PhetioDynamicElementContainer refers to "element".  I find that my brain has to keep jumping between "element" and "member".

I understand that "groups" have "members", but all PhetioGroup members are "elements".  So I don't see a problem with using "element" in PhetioGroup.  But I do see a problem with using "member" - the (unnecessary) cognitive load of having to switch between terminology.

**Comment by pixelzoom** [comment]
To further demonstrate my point, this doc was added for all multiple methods in https://github.com/phetsims/tandem/commit/4c54d48739d76c1ea06bc6dc687cc0c99238af9d for #55:

```js
  /**
   * @param {function(PhetioObject)} listener - this has a single parameter: the dynamic element being created.
   * @public
   */
  addMemberCreatedListener( listener ) {
    this.memberCreatedEmitter.addListener( listener );
  }
```

So the callback param for `addMemberCreatedListener` is described as an element.

**Comment by zepumph** [comment]
I think we purposefully chose member to be different from (PhET-iO) element because we thought that may be clearer. That said. . ..

> the (unnecessary) cognitive load of having to switch between terminology.

I am totally up for switching to only use element. @samreid and @chrisklus what do you think?

**Comment by pixelzoom** [comment]
Another argumentsfor using "element" everywhere...  In discussing with designers, it will be easier to just say "element", and not have to describe "member" or the relationship between element and member. 

I'm writing a lot of comments in Natural Selection, and I'd like to be able to stop having to use "member" in comments, or worry about having to go back and change.

**Comment by zepumph** [comment]
I think we thought that `PhetioCapsule.addElementAddedEmitter` was a little weird since it only has one element, but if we can get past that, I would love to have one set of created/disposed Emitters in the supertype for PhetioCapsule and PhetioGroup. Then `PhetioDynamicElementContainer` will define the set of emitters and it will simplify the hierarchy. 

I an happy to implement as long as @chrisklus and @samreid agree. Will you two please comment on what you think.

**Comment by zepumph** [comment]
There is a good change that this is blocking https://github.com/phetsims/phet-io/issues/1634, so I would love comment sooner rather than later, raising priority.

**Comment by samreid** [comment]
Yes, please.  Let's unify around `element` and implement as much as possible in `PhetioDynamicElementContainer`.  Thanks!

**Comment by zepumph** [comment]
I think it is simplest to have a single issue for work being done in PhetioGroup. I added the work to be done here over to https://github.com/phetsims/tandem/issues/170#issuecomment-614952533. If there is anything I missed please comment over there. Closing.
