### ISSUE TITLE
instrumentation pattern for "Property takes a dynamically-created value"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#158]
This seems like a very general scenario:  Some instrumented Property takes a value that is dynamically created.  We want to provide meaningful type information and documentation for that Property, while supporting save/restore.  

Over in Natural Selection, I discovered that this scenario is not well-supported by PhET-iO.

I had this nice set of classes for dynamic Bunny instances:

```js
class Bunny extends Sprite extends PhetioObject

class BunnyIO extends SpriteIO extends ReferenceIO

class BunnyGroup extends PhetioGroup
```

Then I needed to add a Property for the selected Bunny (note the `XXX` here):

```js
    // @public {Property.<Bunny|null>}
    this.selectedBunnyProperty = new Property( null, {
      tandem: tandem.createTandem( 'selectedBunnyProperty' ),
      phetioType: PropertyIO( NullableIO( XXX ) ),
      phetioDocumentation: 'bunny selected in environmentNode, whose pedigree is displayed by pedigreeNode'
    } );
```

If I replace `XXX` with BunnyIO, then the State Wrapper attempts to create a dynamic Bunny when `selectedBunnyProperty` is restored.  State Wrapper fails with "value failed phetioType validator: [object Object]".  Inspecting the restored value, it's not a Bunny instance, it's an object literal that looks like the value returned by BunnyIO `fromStateObject`.

If I replace `XXX` with ReferenceIO, then the error goes away. Restoring state does the right thing, which is to set `selectedBunnyProperty` value to one of the dynamic Bunny instances that's restored to the BunnyGroup. (And this will apparently work even if the Bunny instance doesn't exist yet.)  But then there's no validation of the Property's value, and the type metadata in Studio looks like this:

`IO Type: PropertyIO<NullableIO<ReferenceIO>>`

How will designers know that this Property's value is `{Bunny|null}`?  They won't from this.

So ReferenceIO may generally describe the value correctly ("a reference to some element"). But is does not adequately describe the value type ("a Bunny").

For lack of any convention for addressing this, I decided to create 2 IO types: 
* `BunnyDynamicIO` for dynamic Bunny instances
* `BunnyReferenceIO` for references to Bunny instances  (dynamic or static) 

So now things are starting to get complicated, and I'm not liking this direction:

```js
class Bunny extends Sprite extends PhetioObject

class BunnyDynamicIO extends SpriteIO extends ReferenceIO

class BunnyReferenceIO extends ReferenceIO

class BunnyGroup extends PhetioGroup
```

I need to move forward with Natural Selection, and this is not blocking me.  But I'm not at all happy with where this is at, and it's the foundation of the sim. 

Assigned to the PhET-iO team to prioritize.

**Comment by pixelzoom** [comment]
Based on the naming "convention" I described about, I'm wondering if I should also rename `BunnyNodeIO` to `BunnyNodeReferenceIO`.

**Comment by pixelzoom** [comment]
There was a long-ish discussion in the Slack phet-io channel.  Here are a few of the more important comments (sorry they're out of context):

Michael Kauzmann:octopus:  4:22 PM
we don't have a solution for that besides (a) creating a subtype called BunnyReferenceIO, or adding documentation string to solve it.

Michael Kauzmann:octopus:  4:32 PM
I also think that it is annoything that it feels like we are leaking state implementation into the public IO Type

Sam Reid  4:56 PM
Should ReferenceIO ultimately become a parametric type?

Michael Kauzmann:octopus:  4:56 PM
That would fix things eh, what about optionally parametric?

**Comment by zepumph** [comment]
After discussing with the phet-io subteam, we decided that it made the most sense to just have one IO type, `BunnyIO` and to make `ReferenceIO` parametric to accept BunnyIO when it was appropriate to use that type as a reference instead of using BunnyIO's serialization logic itself. 

Most of this change was implemented and committed to https://github.com/phetsims/tandem/issues/159. I took the liberty of refactoring natural selection to follow the pattern decided on by the phet-io team. @pixelzoom please review and tell us what you think. The natural selection specific commit is above.

I tested with the launch feature of Studio, and also saw that `selectedBunnyProperty` was serializing correctly in studio:

![image](https://user-images.githubusercontent.com/6856943/78193658-7f821700-7427-11ea-9a25-bc7514fabec2.png)



@pixelzoom what do you think of this new way to handle reference serialization? If you approve the next step will be to update documentation accordingly.

**Comment by pixelzoom** [comment]
Nice, this looks much better, and feels like a good direction.

But this issue has not been addressed:

> the type metadata in Studio looks like this:
> 
> `IO Type: PropertyIO<NullableIO<ReferenceIO>>`
> 
> How will designers know that this Property's value is {Bunny|null}? They won't from this.

Here's what is displayed in Studio:

<img width="679" alt="screenshot_239" src="https://user-images.githubusercontent.com/3046552/78277038-18b93800-74d1-11ea-9283-9fb03efc7364.png">

**Comment by zepumph** [comment]
Right! This was handled over in https://github.com/phetsims/tandem/issues/159, and you already signed off on it there. I will go ahead and close this issue. Please reopen if you feel differently.

![image](https://user-images.githubusercontent.com/6856943/79511380-ab86c600-7feb-11ea-86e1-d1331466974b.png)
