### ISSUE TITLE
ReferenceIO should be parametric

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#159]
To help solving the problem over in https://github.com/phetsims/tandem/issues/158, the phet-io subteam decided that the best way to proceed was to make ReferenceIO parametric. Looking at the current implementation, the validation thus far has only ever been validating that something is an `Object`. Making things parametric will add better validation, as well as providing a way to actually document through the phet-io api what the IO Type for something is. i.e. before we may have had `screenProperty` of type, `PropertyIO( ReferenceIO )`, but now it can be `PropertyIO( ReferenceIO( ScreenIO ) )`. 

In addition to this refactor, we have looked over usages of `ReferenceIO` and how found many spots where we are simply using it instead of providing a more correct type. This issue will give us the opportunity to fix those spots.

This addition will add validation and documentation.

The proposed patterns for using ReferenceIO will be as follows:

If you have an IO Type that you always want to use reference serialization, then you can extend it when declaring the IO Type class. Like so:

        class MyReferenceTypeIO extends ReferenceIO( ObjectIO ) {

If you have a type that may support other serialization, but sometimes should be used as a reference, you can just call the parametric type in the usage site:

        phetioType: PropertyIO( ReferenceIO( MyTypeThatIsSometimesAReferenceTypeIO ) )

I have a fair number of working copy changes and will commit on this shortly. Tagging @samreid and @chrisklus.

**Comment by zepumph** [comment]
https://github.com/phetsims/tandem/issues/158 is out for review. I think it would also be good to get @samreid to review this one. Especially `ReferenceIO.js`.

**Comment by pixelzoom** [comment]
It's nice that ReferenceIO is now parametric.  Here's an example of how I'm using it in natural-selection `EnvironmentModel`:

```js
    // @public {Property.<Bunny|null>} a reference to a Bunny instance in bunnyGroup, null if no selection
    this.selectedBunnyProperty = new Property( null, {
      tandem: tandem.createTandem( 'selectedBunnyProperty' ),
      phetioType: PropertyIO( NullableIO( ReferenceIO( BunnyIO ) ) ),
      phetioDocumentation: 'bunny selected in environmentNode, whose pedigree is displayed by pedigreeNode'
    } );
```

But the parameterization is not showing up in Studio.  Here's the above example in Studio:

<img width="567" alt="screenshot_245" src="https://user-images.githubusercontent.com/3046552/78915807-b8cf0e00-7a49-11ea-8b20-878983095418.png">

@zepumph is it possible to change Studio to show the parameterized type?

**Comment by zepumph** [comment]
Ahh yes! I didn't change the `typeName` when changing everything else. One batch grunt update coming in hot!

**Comment by zepumph** [comment]
Implemented above. I also got rid of using IO Type methods in public documentation (oops). 

Anything else for this issue?

**Comment by pixelzoom** [comment]
`naturalSelection.labScreen.model.environmentModel.selectedBunnyProperty` IO Type now looks good in Studio:

> PropertyIO<NullableIO<ReferenceIO<BunnyIO>>>

But when I select the "Selected" radio button for IO Type Documentation, I'm not seeing the documentation for `BunnyIO`.   Shouldn't that be included?

**Comment by zepumph** [comment]
Great catch! That is an annoying gotcha, so I added an assertion to catch all other cases like this. Turns out ArrayIO was not supplying `parameterTypes` as expected either. Thanks for the solid review. Anything else here?

**Comment by pixelzoom** [comment]
👍 closing.
