### ISSUE TITLE
TandemRectangle constructor is missing parameters

### ISSUE THREAD

**Issue by andrewadare** [phetsims/tandem#16]
The constructor in TandemRectangle.js calls out to Rectangle like this,
```js
 function TandemRectangle( x, y, width, height, options ) {
    Tandem.validateOptions( options ); // The tandem is required when brand==='phet-io'
    Rectangle.call( this, x, y, width, height, options );
//...
}
```
which is the signature for the Dot version. The Scenery constructor is this:
```js
  function Rectangle( x, y, width, height, cornerXRadius, cornerYRadius, options ) 
```

I'll fix it.

**Comment by andrewadare** [comment]
The following will need updates for this change:
 - ComboBox.js
 - ItemToolboxNode.js in FAMB

**Comment by samreid** [comment]
We should support all permutations of query parameters support by scenery rectangle, hopefully this will just work if we pass through args as they appear.

**Comment by andrewadare** [comment]
Changes should be complete. Lint and load tests pass. It would be a good idea to test the parts of FAMB related to ItemToolboxNode.

**Comment by samreid** [comment]
@andrewadare and I worked together to make sure TandemRectangle supports all of the signatures of Node Rectangle.  Closing.
