### ISSUE TITLE
clean up PhetioDynamicElementContainer containerSuffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#160]
It's not obvious how a PhetioDynamicElementContainer gets the base tandem name for the elements in the container.  I figured out that it takes its tandem name, and strips off the value of `options.containerSuffix`.

`containerSuffix` needs better documentation, and the default values need to be factored out into constants with consistent names (like `DEFAULT_CONTAINER_SUFFIX`).

**Comment by pixelzoom** [comment]
Done in the above commit. @chrisklus randomly selected from the IO team to review.

**Comment by chrisklus** [comment]
Looks great @pixelzoom, thanks for doing this. Ready to close if you are.
