### ISSUE TITLE
clean up documentation and naming of IO Type parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#162]
Parameter names and type expressions for IO types is confusing, and in many cases incorrect.  

For example, ObjectIO.js:

```js
  /**
   * Return the json that ObjectIO is wrapping.  This can be overridden by subclasses, or types can use ObjectIO type
   * directly to use this implementation.
   * @param {PhetioObject} o
   * @returns {*} - most of the time it is an Object with data inside, but there are some other cases like NullableIO and ReferenceIO
   * @public
   */
  static toStateObject( o ) {
```

But looking at NumberIO.js:

```js
  /**
   * Encodes a number to a state (which also happens to be a number).
   * @param {Object} value
   * @returns {Object}
   * @override
   */
  static toStateObject( value ) {
    assert && assert( typeof value === 'number', 'value should be number' );
```

So `{PhetioObject} o` and `{Object} value` are both incorrect, because it's a "number" in NumberIO.  The correct expression is in ObjectIO is `{*}`, and in NumberIO `{number}`.

Does anyone mind if I take a stab at cleaning this up across common-code IO types?  If I get 1 "go for it", I'll go for it.

**Comment by zepumph** [comment]
go for it!

**Comment by pixelzoom** [comment]
I've cleaned up my sims, but I don't have time to address this for common code or other instrumented sims.  

Common-code IO types should be prioritized, especially the ObjectIO and ReferenceIO base classes.

It would be nice if sim-specific IO types were cleaned up sooner rather than later -- since a lot of PhET-iO instrumentation currently involves looking at examples, bad examples tend to result in more bad examples. 

Assigning to @ariel-phet to prioritize and assign.

**Comment by samreid** [comment]
This issue overlaps with https://github.com/phetsims/phet-io/issues/1646

**Comment by ariel-phet** [comment]
It sounds like some effort should be put towards a determined effort to improve iO documentation. Marking for iO meeting to discuss priority, but it seems although perhaps not an enviable task, it is an important one for maintainability.

**Comment by pixelzoom** [comment]
There's a similar problem with annotations.  IO Type methods `toStateObject` , `fromStateObject`, `setValue` (and others?) should be `@public @override`.  Many (most?) are missing one or both of those annotations.

**Comment by samreid** [comment]
We agreed this should be higher priority, ObjectIO and ReferenceIO being somewhat more important.

**Comment by samreid** [comment]
We are adjusting how IO types are implemented and documented in https://github.com/phetsims/tandem/issues/188#issuecomment-688356582, putting on hold until that issue is further along.

**Comment by zepumph** [comment]
Marking off hold as #188 is complete. I think this issue is handled, here is the current doc for some state methods:

```

      // {function(coreObject:*):*)} Serialize the core object. Most often this looks like an object literal that holds
      // data about the PhetioObject instance.
      toStateObject: supertype && supertype.toStateObject,

      // {function(stateObject:*):*} For Data Type Deserialization. Decodes the object from a state (see toStateObject)
      // into an instance.
      fromStateObject: supertype && supertype.fromStateObject,

```

@samreid is there more here?

**Comment by samreid** [comment]
Looks good to me, @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
👍🏻
