### ISSUE TITLE
revise documentation for IO Types related to JavaScript primitive types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#165]
Current documentation for IO Types related to JavaScript primitive types:

```js
// NumberIO
NumberIO.documentation = 'Wrapper for the built-in JS number type (floating point, but also represents integers)';

// StringIO
StringIO.documentation = 'Wrapper for the built-in JS string type';

// BooleanIO
BooleanIO.documentation = 'Wrapper for the built-in JS boolean type (true/false)';
```

Observations:

* I don't believe that we call these "wrappers" anymore.
* For designers, "JS" is probably less meaningful than "JavaScript".
* The correct term for these is "primitive types".

So proposal to replace the above with:

```js
// NumberIO
NumberIO.documentation = 'IO type for Javascript\'s number primitive type';

// StringIO
StringIO.documentation = 'IO type for Javascript\'s string primitive type';

// BooleanIO
BooleanIO.documentation = 'IO type for Javascript\'s boolean primitive type';
```

Any objections? If not, I'll do this.

**Comment by zepumph** [comment]
In lots of documentation I have capitalized "IO Type".  I would be happy to do that here too if you agree.

**Comment by pixelzoom** [comment]
"IO Types" sounds great.

**Comment by pixelzoom** [comment]
"IO Type" sounds great. So:

```js
// NumberIO
NumberIO.documentation = 'IO Type for Javascript\'s number primitive type';

// StringIO
StringIO.documentation = 'IO Type for Javascript\'s string primitive type';

// BooleanIO
BooleanIO.documentation = 'IO Type for Javascript\'s boolean primitive type';
```

**Comment by pixelzoom** [comment]
Doc changes have been made, and all API files updated.    Since this was trivial change, and the iO team is very busy, I'm going to go ahead and close this.  If anyone objects to the changes, please reopen.

**Comment by zepumph** [comment]
The above looks great. @pixelzoom my understanding is that to make this change you changed the `phetioDocumentation` in the code, and then ran `grunt update` in all phet-io repos. This totally works, and you should continue to do it if it makes you feel more comfortable.

Another way to handle these metadata-related changes that don't add/remove elements or rename phetioIDs is to just to a find/replace on the project. Basically this only works when you are changing a unique phetioDocumentation string that you feel confident about. That may save you time in the future if you are interested! You can also double check that the generated file looks the same as the manually edited on by running `grunt update` in one repo just to make sure.
