### ISSUE TITLE
Hide general and global Tandems

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#166]
From phet-io meeting today. We should only allow exposing:

```
GLOBAL_VIEW
GLOBAL_MODEL

GENERAL_VIEW
GENERAL_MODEL
GENERAL_CONTROLLER

```

This way we won't have confusion across sims. @chrisklus is this something you can take on?

**Comment by samreid** [comment]
Many usages of `Tandem.ROOT` are in unit tests. For this I'll introduced `Tandem.ROOT_TEST`.

**Comment by samreid** [comment]
Some issues inadvertently got referenced to https://github.com/phetsims/joist/issues/672, I'll link them back to here.

**Comment by samreid** [comment]
OK, I've got some erroneous commit messages but I think everything is ready to review for this issue.

The commit messages with "Use GLOBAL and GENERAL sub-tandems, see phetsims/joist#672 " should be carefully checked, since they change sim-specific API tandems that used to be GLOBAL/GENERAL, I took my best guess on putting things under model/view.

https://github.com/phetsims/tandem/commit/c97e6699ce35eb0cb37d19a6166e4d0dbcba3130 had an incorrect commit message, should have said "Fix tandems in tests ..."

**Comment by pixelzoom** [comment]
@samreid:

About https://github.com/phetsims/gas-properties/commit/fe48d489299ca1bb02ed45e58fe5df0c1544304f: 

The change you made looks totally buggy. Did you look at this in Studio?

<img width="358" alt="screenshot_849" src="https://user-images.githubusercontent.com/3046552/106805185-9daa3c00-6623-11eb-9850-bf1219eb6fd3.png">

About https://github.com/phetsims/gas-properties/commit/fe48d489299ca1bb02ed45e58fe5df0c1544304f and  https://github.com/phetsims/gas-properties/commit/fe48d489299ca1bb02ed45e58fe5df0c1544304f:

If you're going to make a change to a sim, please create an issue in that sim's repo.  Or assign this issue to me. I now have no way to track this change for these sims, and wouldn't have even known about it if I hadn't registered for commit notifications.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/ph-scale/commit/840da2c9f0cb0e05187e015a6b03d2a5f1a9cbbe is also buggy, bad Studio structure now in ph-scale.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/ph-scale/commit/840da2c9f0cb0e05187e015a6b03d2a5f1a9cbbe is also buggy, bad Studio structure now in ph-scale.

I haven't looked at the sims that I'm not responsible for. But I suggest that you take a look at all of the sims that you changed in Studio.

**Comment by pixelzoom** [comment]
Raising priority to high because at least 2 sims are now broken.

**Comment by pixelzoom** [comment]
natural-selection and ph-scale were fixed in the above commits.

**Comment by samreid** [comment]
I reviewed the other commits and did not see other blocking changes, ready for review.

**Comment by zepumph** [comment]
Looks great to me. Good work. Anything else here?

**Comment by samreid** [comment]
All set, thanks!  Closing.
