### ISSUE TITLE
All IO Type static functions should assert with a validator

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#167]
From https://github.com/phetsims/tandem/issues/163#issuecomment-612242592 @pixelzoom mentioned that many static IO Type functions like `toStateObject` and `setValue` that don't validate using `this.validator`.

We should make sure we are consistent. This means converting `assert` to use `validate`, and adding `validate` if it isn't there.

**Comment by samreid** [comment]
This will be addressed by the proposal in https://github.com/phetsims/tandem/issues/211 which automatically validates.  On hold until that issue is further along.

**Comment by samreid** [comment]
The project has been converted to use `new IOType` which automatically validates values in `toStateObject` and `applyState`.  Closing.
