### ISSUE TITLE
Assert that all IO Types call `ObjectIO.validateSubtype`

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#168]
While poking around in https://github.com/phetsims/phet-core/issues/79, I was wondering if it would be easy to do this. More and more developers will be creating IO Types, and it would be nice to have as many assertions as possible. 

Here is an idea:

What if we define a field on ObjectIO called `hasBeenValidated`, set to false, and then in `ObjectIO.validateSubtype` we set it to true. Then in PhetioObject we can assert that the phetioType has been validated. 

This would be a minor enhancement. I'm not sure when I'll get to it.

**Comment by zepumph** [comment]
@samreid is this something that we can do in your new `createIOType` pattern?

**Comment by samreid** [comment]
I should note that more than just validation is happening in `validateIOType`, and in https://github.com/phetsims/tandem/issues/188 we are introducing a new initialization-style method for IO Types.

> Then in PhetioObject we can assert that the phetioType has been validated.

That would test many scenarios.  But there are IO types that are not associated with PhetioObjects (such as StringIO)--would be nice to find a way to test them all.

**Comment by samreid** [comment]
The proposal in https://github.com/phetsims/tandem/issues/168 automatically validates.  On hold until that is addressed.

**Comment by samreid** [comment]
This issue has been addressed in master, but we will need to revisit this if we merge IO Types with core types (discussed in part in #211).  Leaving on hold for now.

**Comment by samreid** [comment]
We have converted the project to use `new IOType` which does not require a separate validation step.  Closing.
