### ISSUE TITLE
Parametric types should use a Map for their cache

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#169]
Related to https://github.com/phetsims/phet-core/issues/79 where we did this in PropertyIO.js and EnumerationIO.js. We should use Map instead of an Object so that we can use actual Objects as keys for the cache.

This is on hold until we sort out https://github.com/phetsims/phet-core/issues/79

**Comment by samreid** [comment]
> This is on hold until we sort out phetsims/phet-core#79

Work in phetsims/phet-core#79 completed, so I removed the hold.

**Comment by zepumph** [comment]
@samreid and I just realized that when there are multiple parameterTypes, we don't think that an Array will work for a `Map`. For example in Action and Emitter.

**Comment by zepumph** [comment]
I converted things above. The only IOTypes that didn't take well to an Object as a key were FunctionIO, ActionIO, and EmitterIO. @samreid please review. Anything else here?

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
