### ISSUE TITLE
Tandem.createTandem() should assert that the name exists

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#17]
Today @jbphet and I added an assert to Tandem.createTandem that checks that the tandem exists.

However, this is failing a bunch of PhET-branded sims:

![image](https://cloud.githubusercontent.com/assets/679486/21162489/d83f7772-c14a-11e6-8de0-4933ad2961d5.png)
```js
assert && assert( typeof id === 'string' && id.length > 0, 'id must be defined' );
```

**Comment by samreid** [comment]
I've removed the assert for now, we will have to think about how to re-enable it.  One possibility would be to require RadioButtonGroup items to pass tandems (even for uninstrumented sims).

**Comment by samreid** [comment]
Fixed in above commits, closing.

**Comment by samreid** [comment]
@pixelzoom identified a problem where this was erroring out for combo boxes.  Reopening.

**Comment by pixelzoom** [comment]
Looks like the bug is in ComboBox:

```js
158 var itemNodeOptions = items[ j ].options || {};
...
167 itemNodeTandem = options.tandem.createTandem( itemNodeOptions.tandemName );
```

` itemNodeOptions` is the options associated with the constructor's `items` argument. Perhaps this is something new that was added, because I don't recall `items` having their own options.  In any case, if they are not provided, then `itemNodeOptions` defaults to `{}` and `itemNodeOptions.tandemName` is `null` -- which causes failure of the assertion in `Tandem`.

**Comment by samreid** [comment]
I think the solution we settled on for RadioButton was to fall back to a default tandem name like so:

```js
      var radioButton = new RadioButtonGroupMember( property, contentArray[ i ].value, _.extend( {
        content: contentArray[ i ].node,
        xMargin: xMargin,
        yMargin: yMargin,

        // Pass through the tandem given the tandemName, but also support uninstrumented simulations
        tandem: options.tandem.createTandem( contentArray[ i ].tandemName || ('radioButtonGroupMember' + i) ),
        accessibleLabel: contentArray[ i ].accessibleLabel
      }, buttonOptions ) );
```

That seems like it would also work for ComboBox.  Thoughts before I proceed?

**Comment by pixelzoom** [comment]
This looks like another potential form in ComboBox:

```js
422     options = _.extend( {}, options );
423
424    TandemRectangle.call( this, 0, 0, width, height, {
425      tandem: options.tandem.createSupertypeTandem()
426    } );
```

`options.tandem` may very well be `null`, which will cause line 425 to fail.

**Comment by pixelzoom** [comment]
... and line 437:

```js
options.tandem.addInstance( this, TComboBoxItemNode( options.phetioValueType ) );
```

**Comment by samreid** [comment]
@pixelzoom and I agreed to add the RadioButton-like pattern on line 167 of ComboBox.

**Comment by samreid** [comment]
@pixelzoom and I worked on this, committed above, tested, closing.
