### ISSUE TITLE
Updates to PhetioGroup API

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#170]
Some of this may only apply to PhetioGroup, and some may apply to the parent type.

- [x] Create a `countProperty` that is instrumented
- [x] Make the Emitters public, and get rid of convenience functions

This should be done with the same priority as https://github.com/phetsims/tandem/issues/156.

@pixelzoom mentioned that much of this work would simplify his implementation of `BunnyGroup.js`.

**Comment by zepumph** [comment]
I think it is easiest to combine this issue with #156. From https://github.com/phetsims/tandem/issues/156:

- [ ] Rename many usages of "member" to "element"
- [ ] Unify API of `PhetioGroup` and `PhetioCapsule` and try to move that logic to `PhetioDynamicElementContainer`

**Comment by zepumph** [comment]
I did quite a bit last night and this morning. One question about renaming from instance/member -> element:
- [ ] Can/ should we factor out a super IO Type?
- [ ] Can PhetioCapsule.create and PhetioGroup.createIndexedElement be factored out in the supertype at all? They are both the methods that their IO Types call to set state.

**Comment by zepumph** [comment]
- [ ] For PhetioCapsule, it isn't immediately obvious if changing `this.instance` to be `this.element` is actually better, but it will align with the Emitter terminology and potentially lead to more that code that can be shared by the super type. I need to think about this a bit more.

**Comment by pixelzoom** [comment]
I like `this.element` in PhetioCapsule.  A capsule managed exactly 1 dynamic element.

**Comment by pixelzoom** [comment]
@zepumph it looks like you removed the add*Listener and remove*Listener functions, made the emitters public, and renamed "member" to "element".   Is it safe for me to revise BunnyGroup, so that I don't have redundant emitters?

**Comment by zepumph** [comment]
Yes please! There is still more work to be done in this issue, but that is safe to do.

**Comment by pixelzoom** [comment]
Hmmm... I guess my emitters in BunnyGroup are not redundant.   After the PhetioGroup creates a bunny, there's other "work" that has to be done before notifying that a bunny has been created.  Maybe I should be BunnyGroup should use PhetioGroup via composition instead of inheritance.

**Comment by zepumph** [comment]
From https://github.com/phetsims/tandem/issues/172#issuecomment-617335616: 

> As noted in https://github.com/phetsims/axon/issues/283#issuecomment-617334011...  I would like to see `forEach` deleted from the API of both PhetioGroup and ObservableArray, and replaced with `getArray` and `getArrayCopy`.  That would make it crystal clear on whether you're operating on the array itself or a copy.  Examples:

```js
myObservableArray.getArray().forEach( .... );
myObservableArray.getArrayCopy().forEach( .... );

myPhetioGroup.getArray().forEach( .... );
myPhetioGroup.getArrayCopy().forEach( .... );
```

I don't think I'm a fan of having array exposed. Let's discuss ways to make PhetioGroup more collection-like and flexible.

**Comment by pixelzoom** [comment]
We have (at least temporarily) add `getArray` and `getArrayCopy` to both PhetioGroup and ObservableArray.  See https://github.com/phetsims/tandem/issues/180 and https://github.com/phetsims/axon/issues/283#issuecomment-620151143 respectively.

**Comment by zepumph** [comment]
- [ ] When calling disposeElement, there are three operations, remove the reference from the data stream (like the array for PhetioGroup), emit disposal, and dispose the element. What order is best? Right now I'm going with the order listed above.

**Comment by zepumph** [comment]
- [ ] I want to move `elementCreatedEmitter.emit( createdElement )` up to PhetioDynamicElementContainer, but that would mean for PhetioGroup that we would emit before that object has been populated into the array. Is that acceptable?

**Comment by zepumph** [comment]
PhetioGroup.countProperty was added above. 

- [ ] @arouinfar should this be phetioFeatured?

**Comment by zepumph** [comment]
When I added countProperty, I also added a listener that would assert that this._array was the same length as the count. This ended up being challenging just like in the state order dependencies we worked on for gas properties, except that the countProperty would need a dependency on every single group element. This felt less than ideal. 
- [ ] We could (and probably should) still add that assertion back in, and code around the case in the state engine. It feels very valuable to have in place.

I went through all the above, and made a bunch more commits. @chrisklus can you please go through the above comments with checkboxes in them, review code, and discuss how we should proceed for each (checked ones will be easier). Thanks!

**Comment by pixelzoom** [comment]
>  - [ ] I want to move elementCreatedEmitter.emit( createdElement ) up to PhetioDynamicElementContainer, but that would mean for PhetioGroup that we would emit before that object has been populated into the array. Is that acceptable?

That feels wrong to me.  Create should create the element, add the element to the array, then fire `elementCreatedEmitter`.  Dispose should remove the element from the array (so that the array doesn't contain a disposed element), then dispose the element, then fire `elementDisposedEmitter`.

**Comment by pixelzoom** [comment]
A bit of a nit, and definitely subjective... But why not increment and decrement `countPropert` like this?

```diff
Index: js/PhetioGroup.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/PhetioGroup.js	(revision 2caf79dc416397c3603e99594f30ff4e2e46ae58)
+++ js/PhetioGroup.js	(date 1588301942090)
@@ -73,7 +73,7 @@
   disposeElement( element ) {
     super.disposeElement( element );
     arrayRemove( this._array, element );
-    this.countProperty.value -= 1;
+    this.countProperty.value--;
   }
 
   /**
@@ -209,7 +209,7 @@
 
     this._array.push( groupElement );
 
-    this.countProperty.value += 1;
+    this.countProperty.value++;
 
     // TODO: move to parent, https://github.com/phetsims/tandem/issues/170#issuecomment-622189798
     this.elementCreatedEmitter.emit( groupElement );

```

**Comment by pixelzoom** [comment]
As I mentioned in https://github.com/phetsims/tandem/issues/170#issuecomment-622224002, this is (imo) all backwards:

```js
// PhetioGroup.js
  disposeElement( element ) {
    super.disposeElement( element );
    arrayRemove( this._array, element );
    this.countProperty.value -= 1;
  }

// In PhetioDynamicElementContainer.js:
  disposeElement( element ) {
    this.elementDisposedEmitter.emit( element );
    element.dispose();
  }
```

The emitter is called "Disposed" not "WillBeDisposed".  And if it's disposed, why is it still a member of the group?   I.e., firing `this.elementDisposedEmitter` before disposing fails these 2 basic assumptions. 

```js
myGroup.elementDisposedEmitter( element => 
  assert && assert( element.isDisposed, 'element is not actually disposed' );
  assert && assert( !myGroup.contains( element ), 'element is still in the group' ); 
} );
```

This doesn't fit with your subclassing plan, but here's what I think is correct:

```js
// PhetioGroup.js
disposeElement( element ) {

  // remove from array, so that array never contains disposed elements
  arrayRemove( this._array, element );
  this.countProperty.value -= 1;

  // dispose of the element
  element.dispose();

  // notify that dispose has been done
  this.elementDisposedEmitter.emit( element );
}
```

And the current order of `createIndexedElement` looks correct.  That is, create the element, add it to the array, update `countProperty`, fire `elementCreatedEmitter`.

**Comment by pixelzoom** [comment]
The current implement of `disposeElement` was actually causing a bad count in Natural Selection, because I assumed that the element was actually disposed and had been removed from the array.  See my workaround in the above commit.   

Note that I'm planning to delete BunnyCollection `totalNumberOfBunniesProperty` once PhetioGroup `countProperty` is finalized, and the behavior of create/dispose is well-defined.

**Comment by zepumph** [comment]
I like your ordering. I'll change it up.

**Comment by pixelzoom** [comment]
Cool. And I'll be happy to review, if that helps.

**Comment by zepumph** [comment]
I updated countProperty updates. 

Should PhetioGroup.length run on countProperty? I don't care either way.

I also updated the disposal order as you suggested. It makes much more sense.

I prefer the current implementation of PhetioCapsule.disposeElement, to the following:

```js
  disposeElement() {
    const disposedElement = this.element;
    this.element = null;
    super.disposeElement( disposedElement );
  }
```

What do you think?

**Comment by arouinfar** [comment]
@zepumph said:
> PhetioGroup.countProperty was added above.
>
> @arouinfar should this be phetioFeatured?

I took a look at `countProperty` in Projectile Motion and Charges and Fields. It's looking nice!

I think this is something we'll want to be phetioFeatured. Back to @zepumph.

**Comment by pixelzoom** [comment]
> I updated countProperty updates. 
> Should PhetioGroup.length run on countProperty? I don't care either way.

Yeah....  The most useful convenience method would be getting the count without having to do `group.countProperty.value`.  So I would change `get length` to `get count`, and  make it return`this.countProperty.value`.   If someone needs "length", then they're dealing with the array and have already called `getArray`.

> I also updated the disposal order as you suggested. It makes much more sense.

Looking good! I added some doc to `disposeElement` and `createIndexedElement`, and removed the TODO from `createIndexedElement`. Please review.

> I prefer the current implementation of `PhetioCapsule.disposeElement`, to the following: ...

I could go either way on that. The listener is already getting a referent to `element` in the callback, so I doubt that they'd attempt to (or need to) access PhetioCapsule.element.

**Comment by zepumph** [comment]
I renamed PhetioGroup.length -> PhetioGroup.count, made `countProperty` `phetioFeatured:true` and tweaked some documentation. 

>We could (and probably should) still add that assertion back in, and code around the case in the state engine. It feels very valuable to have in place.

I don't think it is worth the complexity at this point, but let me know if you feel differently.

@pixelzoom please give things a spot check.  Anything else here?

**Comment by zepumph** [comment]
Making count run on `get count` run on `countProperty` broke NaturalSelection's assertion in `BunnyCollection.assertValidCounts` in the state wrapper. This is because the ObservableArray has its listeners firing immediately during state set, but Properties do not. I will create an issue to investigate deferring ObservableArray listeners.

**Comment by pixelzoom** [comment]
I made a couple of documentation changes in the 2 commits above, @zepumph feel free to take a peek.

@zepumph said:
>> We could (and probably should) still add that assertion back in, and code around the case in the state engine. It feels very valuable to have in place.
> 
> I don't think it is worth the complexity at this point, but let me know if you feel differently.

@zepumph I don't see the "add assertion back in" comment anywhere in this issue.  Can you clarify what you're talking about here?

**Comment by zepumph** [comment]
You changes look great. Thank you.

>@zepumph I don't see the "add assertion back in" comment anywhere in this issue. Can you clarify what you're talking about here?

Yes sorry! To be clear about what I wanted to add for validation, here is the patch:

```diff
Index: js/PhetioGroup.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/PhetioGroup.js	(revision 48cf7e3aa38f1bf6384f8cb056cf5cb026260e33)
+++ js/PhetioGroup.js	(date 1588957302909)
@@ -57,6 +57,8 @@
       phetioFeatured: true,
       numberType: 'Integer'
     } );
+
+    assert && this.countProperty.link( count => assert( count === this._array.length, 'countProperty should match array length.' ) )
   }
 
   /**

```

This issue with this is in the state engine. Basically this means that the countProperty now has an order dependency on every dynamic element getting created before it gets notified. Now that I'm writing this out, it feels pretty reasonable, and like something I should add. 

I think I will wait until https://github.com/phetsims/phet-io/issues/1634#issuecomment-625515116 is sorted out, because that is going to change the place/behavior of dynamic element creation within the state setting lifecycle.

I'll keep myself assigned to this to look into adding that assertion when the time feels right.

**Comment by pixelzoom** [comment]
Thanks for the clarification.  Yes, I agree that is a "reasonable" and valuable assertion.

**Comment by zepumph** [comment]
The assertion was successfully added above, we needed to make sure that the countProperty wasn't updated while setting state, since the countProperty itself is stateful. I'll keep this open and come back after looking at CT in the morning. 

Note that the Natural selection specific problems will be discussed and reviewed over in https://github.com/phetsims/natural-selection/issues/74, but I wanted to link them here too for completeness.

**Comment by zepumph** [comment]
Just to be clear, Natural Selection and CAF were both fuzzing state successfully after this commit, so I feel confident enough to add this assertion in now.

**Comment by pixelzoom** [comment]
CT is reporting a problem with `countProperty` in Concentration:

```
concentration : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/phet-io-wrappers/state/?sim=concentration&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22concentration%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589428317359%7D
Uncaught Error: Assertion failed: countProperty should match array length.
Error: Assertion failed: countProperty should match array length.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/tandem/js/PhetioGroup.js:61:49
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/TinyEmitter.js:69:53)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Property.js:270:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Property.js:320:47)
at PhetioStateEngine.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/phet-io/js/PhetioStateEngine.js:337:41)
at PhetioStateEngine.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/phet-io/js/PhetioStateEngine.js:269:12)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/phet-io/js/PhetioStateEngine.js:205:10)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/phet-io/js/PhetioEngineIO.js:221:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/phet-io/js/phetioCommandProcessor.js:267:51)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM
```

**Comment by zepumph** [comment]
Indeed! The issue was very similar to https://github.com/phetsims/natural-selection/issues/74, in that the state setting was actually buggy, but and relied on being set twice in those cases, because on the second time a Property wouldn't change and first the listeners again. This particular fix is above. Please review.

In general, I am really loving this assertion. It has exclusively caught bugs that differed from how we expected state to be working. I'll keep working on this sort of bug I see on CT. I believe that Projectile Motion is having this sort of bug now too. 


Investigating these bugs is very tricky btw, Though I'm unsure how to make it easier. It involves a lot of nuance and understanding in the lifecycle of how PhetioGroups have their state set.  The BLL bug maybe took about 40 minutes to track down. I hope to get better at this type of gotcha the longer we use PhetioGroup.

**Comment by zepumph** [comment]
In https://github.com/phetsims/tandem/commit/e4dbfb10c017c6613b46bdd5b41801177a5b134d and https://github.com/phetsims/phet-io/commit/db74308d6b87dbd54bb97caca209148e65c6252b

I worked a bit more on making countProperty and its length validation work with phet-io state. This commit (a) removes a workaround in PhetioGroup that I thought was a fix but was actually causing bugs in Projectile Motion, and (b) fixes that underlying problem that is exposed via Natural Selection. 

I will keep checking CT, and if it is clear, I'm tempted to close this issue after the BLL review, and take this up in other state-setting errors in https://github.com/phetsims/phet-io/issues/1666 and other side issues. Over to @pixelzoom to look at https://github.com/phetsims/beers-law-lab/commit/8ddebac6096d440b573f1688de5dca577768a2a1

**Comment by pixelzoom** [comment]
@zepumph and I reviewed https://github.com/phetsims/beers-law-lab/commit/8ddebac6096d440b573f1688de5dca577768a2a1 via Zoom.  I think I understand the underlying problem now.  But it seems like this fix should also be applied to `Precipitate.removeAllParticles`.  So I've added that in the above commit, and will monitor CT.

**Comment by pixelzoom** [comment]
No problems in BLL after 3 cycles of CT.   Sounds like the intention was to close this after BLL review, so closing.

**Comment by zepumph** [comment]
CT is looking good to me!
