### ISSUE TITLE
LinkedElementIO should copy methods from its linked TypeIO

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#171]
From https://github.com/phetsims/scenery/issues/1046:

>* We set up logic [in Node.js] that will add a LinkedElement to point to the passed in `visibleProperty`. We think it makes sense to add support to LinkedElement to "forward" client requests to its core type. That way you could still setValue on any LinkedElement. This may not be too important for Studio (since it shows the UI of the core element in a cut out), but it is likely that for `invoke` calls that we should support this. I'll create a new issue.

This is a systemic issue, and I can see the value of this. i.e.:

```js
phetioClient.invoke( 'sim.screen.slider.property', 'setValue', [ 123 ] );
```

This feels like a nice enhancement to me!

Possible ways to implement:
* Have phetioCommandProcessor manually forward for LinkedElement instances
* Make LinkedElementIO parametric and copy methods of its linked IO Type. This feels a bit sneaky.
* Something else?

@chrisklus and @samreid what do you think? What is best to pursue first?

**Comment by samreid** [comment]
> Have phetioCommandProcessor manually forward for LinkedElement instances

That sounds the most robust.

**Comment by zepumph** [comment]
In the above commit, @samreid and I added LinkedElement method forwarding build into the command processor that listens to commands from the wrapper frame.

This is hard coded for only LinkedElement, but I don't feel too bad about that, as it is quite special behavior that I don't feel like would apply anywhere else. 

I ended up committing because I was able to successfully test by:
* going to the sun demo in studio, 
* components screen
* going to the HSlider which creates the needed slider
* typing `window.phetio.phetioClient.invoke( 'sun.general.demoSlider.enabledProperty', 'setValue', [false]);` in the console which is acting on a LinkedElementIO. 
* See that the slider gets disabled, and the actual value of the underlying enabledProperty was changed.

@samreid please review.

**Comment by samreid** [comment]
The code change looks good, and I tested with this property in Gravity and Orbits:

```js
window.phetio.phetioClient.invoke('gravityAndOrbits.modelScreen.view.controlPanel.checkboxPanel.gravityForceCheckbox.property','setValue',[false]);
```

It worked great and I think this is good for now, I can't think of anything else we would need to do to make LinkedElements act like their core elements at the moment.  Closing.
