### ISSUE TITLE
design a proper "collection" API for PhetioGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#172]
PhetioGroup is starting to be used like a collection, similar to ObservableArray.  Their `forEach` methods are currently very different:

```
// PhetioGroup
forEach( action ) { this.array.forEach( action ); }

// ObservableArray
forEach: function( callback ) {

  // TODO: don't slice on forEach, see https://github.com/phetsims/axon/issues/283
  this._array.slice().forEach( callback ); // do this on a copy of the array, in case callbacks involve array modification
}
```

First, I had no idea that there was a plan to remove `slice` from `ObservableArray.forEach`, and was relying on it.  Second, I guessed that `PhetioGroup.forEach` would behave the same as ObservableArray, but was wrong and got bit hard.  Third, the iO team recommended that I use `PhetioGroup.forEach`, and I'm skeptical about the scalability of that recommendation. 

It would be good to clean this up "soon", and provide consistent/performant iterators for collections.

**Comment by pixelzoom** [comment]
PhetioGroup also makes `this.array` public, while ObservableArray makes it private.  It should be private in both. 

As noted in https://github.com/phetsims/axon/issues/283#issuecomment-617334011...  I would like to see `forEach` deleted from the API of both PhetioGroup and ObservableArray, and replaced with `getArray` and `getArrayCopy`.  That would make it crystal clear on whether you're operating on the array itself or a copy.  Examples:

```js
myObservableArray.getArray().forEach( .... );
myObservableArray.getArrayCopy().forEach( .... );

myPhetioGroup.getArray().forEach( .... );
myPhetioGroup.getArrayCopy().forEach( .... );
```

**Comment by pixelzoom** [comment]
Regarding the `getArray` and `getArrayCopy` proposal... In https://github.com/phetsims/tandem/issues/170#issuecomment-617339885, @zepumph said:

> I don't think I'm a fan of having array exposed. Let's discuss ways to make PhetioGroup more collection-like and flexible.

**Comment by pixelzoom** [comment]
As a user of these APIs, I would be perfectly fine with not having the array exposed.  But as I'm trying to use the current API in Natural Selection, it appears as though iteration (particularly encapsulation and performance) was not considered in the design of this API.  The seems like a significant oversight for something whose secondary responsibility is to act as a collection. 

The other issue is that there doesn't seem to have been any concern for or testing of scalability for PhetioGroup.  And when I've asked questions about performance (e.g. "should I use forEach?" in Slack) the response has been that I shouldn't prematurely worry about performance.  

So... Shall we try to design a proper API for this, or shall we continue to let the problems that we encounter drive what the API looks like?

**Comment by zepumph** [comment]
>Shall we try to design a proper API for this

Recommendations would be very welcome. You are thus far the only user of this outside the PhET-iO team.

**Comment by pixelzoom** [comment]
As with any collection, the most fundamental API requirements are:
* hide the details of how members of the collection are stored
* provide useful, performant iterators 

PhetioGroup and ObservableArray satisfy neither of those requirements.  That's why I've avoided ObservableArray whenever possible.  I don't have that option with PhetioGroup.

**Comment by pixelzoom** [comment]
Since this issue has become more about the fact that PhetioGroup doesn't have a proper "collection" API, I've changed the issue title to reflect that.

**Comment by samreid** [comment]
Focusing our attention on PhetioGroup for the moment, let's talk about these objectives:

> hide the details of how members of the collection are stored

It seems like this could be accomplished by making PhetioGroup.array private.

> provide good iterators (useful, consistent, performant,..,)

Here are the current collections-style methods provided by PhetioGroup at the time of this writing:

```js

  /**
   * Returns the element at the specified index
   * @param {number} index
   * @returns {Object}
   */
  get( index ) {
    return this.array[ index ];
  }

  /**
   * Get number of Group elements
   * @returns {number}
   * @public
   */
  get length() { return this.array.length; }

  /**
   * Returns an array with elements that pass the filter predicate.
   * @param {function(PhetioObject)} predicate
   * @returns {Object[]}
   * @public
   */
  filter( predicate ) { return this.array.filter( predicate ); }

  /**
   * Returns true if the group contains the specified object.
   * @param {Object} element
   * @returns {boolean}
   * @public
   */
  contains( element ) { return this.array.indexOf( element ) >= 0; }

  /**
   * Runs the function on each element of the group.
   * @param {function(PhetioObject)} action - a function with a single parameter: the current element
   * @public
   */
  forEach( action ) { this.array.forEach( action ); }

  /**
   * Returns an array with every element mapped to a new one.
   * @param {function(PhetioObject)} f
   * @returns {Object[]}
   * @public
   */
  map( f ) { return this.array.map( f ); }
```

Can you please explain why this set of methods is not useful, consistent or performant?

**Comment by pixelzoom** [comment]
> Can you please explain why this set of methods is not useful

No support for modification while iterating.  If you're going to suggest `filter` or `map` as a way of doing that, then change "no support" to "poor support".

No support for adding/removing > 1 element from the collection. All changes are 1 element at a time.

Length cannot be observed; you have to register a listener with both `elementCreatedEmitter` and `elmentDisposedEmitter`. 

> consistent

The API differs from other PhET collections, see ObservableArray.

> performant

Afaik, no performance testing has been done to verify that `forEach` is the best iterator choice. And many a Google search indicates that `forEach` is not the most performant iterator.   So I would put this one back in the iO team's court - demonstrate that it's performant.

**Comment by pixelzoom** [comment]
> > hide the details of how members of the collection are stored
> It seems like this could be accomplished by making PhetioGroup.array private.

Accessing `PhetioGroup.array` is currently necessary for 2 reasons: 
(1) To make a copy of the array, in order to support modification while iterating.
(2) To try other iterators, since PhetioGroup performance has not been vetted.

**Comment by pixelzoom** [comment]
> > hide the details of how members of the collection are stored
>
> It seems like this could be accomplished by making PhetioGroup.array private.

Accessing `PhetioGroup.array` is currently necessary for 2 reasons:

(1) To make a copy of the array, in order to support modification while iterating.
(2) To try other iterators, since PhetioGroup performance has not been vetted.

> > provide good iterators (useful, consistent, performant,..,)
> 
> Here are the current collections-style methods provided by PhetioGroup at the time of this writing:
> ...
> Can you please explain why this set of methods is not useful,

No support for modification while iterating.  If you're going to suggest `filter` or `map` as a way of doing that, then change "no support" to "poor support".

No support for adding/removing > 1 element from the collection. All changes are 1 element at a time. (Necessity probably depends on performance.)

Length cannot be observed; you have to register a listener with both `elementCreatedEmitter` and `elmentDisposedEmitter`. 

> consistent,

The API differs from other PhET collections, see ObservableArray.

The API exposes the internal storage of the collection (`array`).

> or performant?

Afaik, no performance testing has been done on PhetioGroup.  For example, has it been determined that `Array.forEach` is the best choice for implementing iteration? Many a Google search indicates that `forEach` is not the most performant Array iterator.   So I would put this one back in the iO team's court - demonstrate that PhetioGroup is performant, Get a feel for how performance is related to collection size, and how that influences the choice of when/whether to use PhetioGroup.

**Comment by pixelzoom** [comment]
To the above "useful" list, I would add...  I don't believe that `forEach` is the only useful iterator.  `Array` provides multiple iterators to fit different situations, providing the flexibility to choose an iterator based on performance, readability, etc.  Have we looked at the Java iterator interface for Java Collections?  C++ iterator? Other APIs? What are the iterator use-cases for PhetioGroup?

**Comment by pixelzoom** [comment]
Before proceeding further with this issue, I think we need to decide whether acting as a collection is a primary responsibility of PhetioGroup.   I'm on the fence about that.  Over in https://github.com/phetsims/tandem/issues/170#issuecomment-617339885, I proposed adding `getArray` and `getArrayCopy` to both ObservableArray and PhetioGroup.  @zepumph didn't like the idea of exposing the array.  But playing devil's advocate...

PhetioGroup's primary responsibility is creating and disposing of dynamic PhET-iO elements. It's not intended to act as a collection. If we're clear that the collection is a public property of PhetioGroup, and that it's an Array, then we can rely on the Array API for iterators, etc.  Then we'd be using a well-known, flexible collection API (Array) and not have to incur the expense of developing one.   The most obvious downside is that there's no way to prevent modification-during-iteration programming errors (also true with Array), and it puts the responsibility on the client to properly use `getArray` vs `getArrayCopy`.   I'd be OK with that tradeoff, given the complexity of designing and implementing a collection API for PhetioGroup.

ObservableArray, on the other hand, does need a collection API.  And the current API needs work.

**Comment by samreid** [comment]
I don't feel strongly about this issue and will wait until there is more of a consensus.  Please discuss and/or promote to developer meeting if you want a larger conversation.

**Comment by pixelzoom** [comment]
Until this issue is resolved, would anyone object to adding PhetioGroup `getArray` and `getArrayCopy`, and making `array` private?   That would make things easier to change in the future.  And I have an immediate to modify-while-iterating in Natural Selection, and would prefer not to be writing code like `bunnyGroup.array.slice()`.

**Comment by pixelzoom** [comment]
Until this issue is resolved, would anyone object to me adding PhetioGroup `getArray` and `getArrayCopy`, and making `array` private?   That seem to be a baby step in the right direction, and would make things easier to change in the future.  And I have an immediate to modify-while-iterating in Natural Selection, and would prefer not to be writing code like `bunnyGroup.array.slice()`.   And I would handle this.

**Comment by samreid** [comment]
Go for it!

**Comment by pixelzoom** [comment]
OK.  Unless I hear objections, I'll be adding modifying the `array` part of the API this afternoon.

**Comment by pixelzoom** [comment]
Proceeding with PhetioGroup `getArray` and `getArrayCopy` in https://github.com/phetsims/tandem/issues/180.

**Comment by samreid** [comment]
> PhetioGroup's primary responsibility is creating and disposing of dynamic PhET-iO elements. It's secondary responsibility is as a collection. If we're clear that the collection is a public property of PhetioGroup, and that it's an Array, then we can rely on the Array API for iterators, etc. Then we'd be using a well-known, flexible collection API (Array) and not have to incur the expense of developing one. The most obvious downside is that there's no way to prevent modification-during-iteration programming errors (also true with Array), and it puts the responsibility on the client to properly use getArray vs getArrayCopy. I'd be OK with that tradeoff, given the complexity/cost of designing and implementing a collection API for PhetioGroup.
> 
> ObservableArray, on the other hand, does need a collection API. And the current API needs work.

That makes a lot of sense.  But I don't understand why that plan is OK for PhetioGroup but not ObservableArray?

**Comment by pixelzoom** [comment]
> That makes a lot of sense. But I don't understand why that plan is OK for PhetioGroup but not ObservableArray?

The way I see it, ObservableArray's primary responsibility is to serve as a collection that supports notification -  conceptually a subclass of Array that adds notification features.   So (to me) it feels more important to hide ObservableArray's internal Array.  But I'd be OK with proceeding with the same `getArray` and `getArrayCopy` approach.  

@zepumph had an opinion about this (for PhetioGroup and ObservableArray) over in https://github.com/phetsims/tandem/issues/170#issuecomment-617339885:
> I don't think I'm a fan of having array exposed. Let's discuss ways to make PhetioGroup more collection-like and flexible.

**Comment by zepumph** [comment]
I'm happy with the way your are proceeding, especially with the regard to performance and a maintainable api.

**Comment by zepumph** [comment]
@pixelzoom anything else for this issue?

**Comment by pixelzoom** [comment]
So to summarize, the collection part of the API is now `getArray` and `getArrayCopy`, with some convenience methods that operate directly on the internal array (`forEach`, `indexOf`,...)

I'm OK with calling this good, so I'll close.  If anyone object, feel free to reopen.
