### ISSUE TITLE
PhetioGroup is not scalable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#173]
Related to https://github.com/phetsims/studio/issues/122 (Studio handling of dynamic elements is not scalable)

In Natural Selection, bunnies are dynamically created via a PhetioGroup subclass - see BunnyGroup.js. The group can contain at most ~3000 living bunnies, and an open-ended number of dead bunnies (bunnies dies after 2 generations, or if killed by environmental factors).

Scalability problems that I see in Natural Selection:

1. PhetioGroup creates elements 1 at a time.  On each cycle of the clock, bunnies are paired up and have a litter of 4 bunnies.  If I have 800 bunnies, that's 400 pairs x 4 per litter = 1600 bunnies that will be created, and 1600 calls to `PhetioGroup.createNextElement`.  This results in a very noticeable pause in animation (seconds).

2. PhetioGroup disposes of elements 1 at a time. If 50 bunnies die at the same time, that's 50 calls to `PhetioGroup.disposeElement`.

3. PhetioGroup `clear` calls `disposeElement` for each element in the group. Bunnies take over the world when there are > 1000 living bunnies (and an open-ended number of dead bunnies). Pressing the _Reset All_ button or _Start Over_ button in Natural Selection results in a significant lag (seconds), because a large number of calls to `PhetioGroup.disposeElement` is made.

4. Performance for all of the above is even worse in Studio, making it effectively unusable. See https://github.com/phetsims/studio/issues/122.

**Comment by pixelzoom** [comment]
Notes from 4/23/20 phet-io meeting:

* Work on optimizing PhetioGroup
* Determine some "upper bound" for when PhetioGroup doesn't work
* Recommend other patterns for when PhetioGroup won't work
* Work on the "collection API" part of PhetioGroup, see https://github.com/phetsims/tandem/issues/172

**Comment by zepumph** [comment]
@chrisklus, @samreid, and I committed over in https://github.com/phetsims/tandem/issues/176 changes that shaved a few hundred milliseconds off of natural selection generation jumps that create many bunnies. It is by no means an end all solution, but hopefully we can find a few more solutions like that which help improve the performance of underlying phet-io code.

**Comment by samreid** [comment]
In https://github.com/phetsims/studio/issues/122 @pixelzoom reported:

> Nice! That's a massive improvement, Studio is now usable.

I'm inclined to move priority to medium, but please correct me if it should remain high.

**Comment by samreid** [comment]
In https://github.com/phetsims/natural-selection/issues/60#issuecomment-653686932 @pixelzoom reported:

> Just for kicks, I tried eliminating the PhetioGroup that created BunnyNode instances, since it's unclear whether BunnyNode really needs to be instrumented.   On my 2019 MacBook Pro, the delay reduction was negligible - from 326 ms to 317 ms (3%).

**Comment by samreid** [comment]
I'm not seeing a lot of overhead in PhetioGroup specifically:

![image](https://user-images.githubusercontent.com/679486/90585268-b1ef9f00-e191-11ea-9448-048e52e37f98.png)

Taking this with the preceding comment indicating only around 3% overhead, can this issue be closed?

**Comment by pixelzoom** [comment]
Yep, closing.
