### ISSUE TITLE
revisit PhetioObject.createCorrespondingGroupElement API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#174]
`PhetioObject.createCorrespondingGroupElement`API results in relative ugly call sites.  Here are the current usages:

```js
const chargedParticleNode = chargedParticleNodeGroup.createCorrespondingGroupElement( addedChargedParticle, addedChargedParticle );
const electricFieldSensorNode = electricFieldSensorNodeGroup.createCorrespondingGroupElement( addedElectricFieldSensor, addedElectricFieldSensor );
const bunnyNode = this.createCorrespondingGroupElement( bunny, bunny );
const blockNode = blockNodes.createCorrespondingGroupElement( addedBlock, addedBlock );
const beakerView = this.beakerViews.createCorrespondingGroupElement( addedBeaker, addedBeaker );
```

Could we revisit this API, so that we're not always duplicating the same 2 args?

In the most general case, the first parameter to `createCorrespondingGroupElement` should be `{string} tandemName`, not `{PhetioObject} phetioObject`.  It's using nothing but `phetioObject.tandem.name`, an example of unnecessary coupling.

**Comment by pixelzoom** [comment]
Worst case, the new API would be:

```js
  /**
   * When creating a view element that corresponds to a specific model element, we match the tandem name index suffix
   * so that electron_0 corresponds to electronNode_0 and so on.
   * @param {string} tandemName
   * @param {...*} argsForCreateFunction - args to be passed to the create function, specified there are in the IO Type `stateToArgsForConstructor` method
   * @returns {PhetioObject}
   * @public
   */
  createCorrespondingGroupElement( tandemName, ...argsForCreateFunction ) {
```

And call sites would look like:

```js
const bunnyNode = this.createCorrespondingGroupElement( bunny.tandem.name, bunny );
```

**Comment by samreid** [comment]
That seems reasonable to me, but let's run it past @zepumph.

**Comment by zepumph** [comment]
Yes I think that just passing in the tandem name as the first arg is appropriate. Thanks!

**Comment by pixelzoom** [comment]
Back to the phet-io team to decide who works on this.

**Comment by chrisklus** [comment]
Committed above and tested in CAF, EFAC, and Natural Selection. @samreid or @zepumph please review.

**Comment by zepumph** [comment]
very good! Thanks. I'm going to close, please reopen if there is anything else.
