### ISSUE TITLE
Bogus documentation for PhetioGroupIOImpl constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#175]
Bogus documentation for PhetioGroupIOImpl constructor in PhetioGroupIO.js, see below.  What is "Track"? 

```
class PhetioGroupIOImpl extends ObjectIO {

    /**
     * Adds a Track as specified by the phetioID and state.
     * A Track will create its own ControlPoints
     * @param {PhetioGroup} group
     * @param {string} componentName
     * @param {Object} stateObject
     * @returns {PhetioObject}
     * @throws CouldNotYetDeserializeError - if it could not yet deserialize
     */
    static addChildInstance( group, componentName, stateObject ) {
````

**Comment by chrisklus** [comment]
I took a first pass. Are we still intentionally using "member" in some places (like that function) or should everything be converted to "element"?

**Comment by pixelzoom** [comment]
Based on work completed in https://github.com/phetsims/tandem/issues/156, my understanding is "element".

**Comment by pixelzoom** [comment]
A couple of other things:

- [ ] The name `addChildInstance` also seems questionable, since it's described as "Creates an element of the group".  

- [ ] All methods of class `PhetioGroupIOImpl` are missing visibility annotations.

**Comment by samreid** [comment]
All steps complete, back to @pixelzoom for review.
