### ISSUE TITLE
Tandem should keep reference to their children

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#176]
@samreid, and @chrisklus and I think that this may be a way to improve performance around PhetioObject, especially as it pertains to dynamic elements and recursively applies that flag to its children in `propagateDynamicFlagsToChildren`.

We found, while working on https://github.com/phetsims/studio/issues/122, that `getChildren` calls within `propagateDynamicFlagsToChildren` could be taking upwards of 15% of a single laggy frame when creating hundreds of bunnies (all PhetioObjects).

Here is a patch that adds children to Tandem. I'm unsure this is the right approach, but I see a visible improvement (~10%) speed up in that frame.

<details>

```diff
Index: phet-io/js/phetioEngine.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- phet-io/js/phetioEngine.js	(revision d971b14897bd600cabaee963b8750bc05268f849)
+++ phet-io/js/phetioEngine.js	(date 1587770809632)
@@ -453,18 +453,14 @@
    * Get all the phetioObjects that are children to the supplied PhetioObject. This will only return phetioIDs of
    * instrumented PhetioObjects, and not strings of "organizational" ids.
    * @param {PhetioObject} phetioObject
-   * @returns {Array.<PhetioObject>}
+   * @returns {PhetioObject[]}
    * @public
    */
-  getChildren( phetioObject ) {
-    const prefix = phetioObject.tandem.phetioID + window.phetio.PhetioIDUtils.SEPARATOR;
-    const prefixLength = prefix.length;
+  getDescendants( phetioObject ) {
 
-    return this.phetioIDs.filter( phetioID => {
-
-      // Optimize since this can be a performance problem, see https://github.com/phetsims/studio/issues/122#issuecomment-618787451
-      return phetioID.substring( 0, prefixLength ) === prefix;
-    } ).map( phetioID => this.phetioObjectMap[ phetioID ] );
+    const descendantTandems = phetioObject.tandem.getDescendants();
+    return descendantTandems.filter( tandem => this.phetioObjectMap.hasOwnProperty( tandem.phetioID ) )
+      .map( tandem => this.phetioObjectMap[ tandem.phetioID ] );
   }
 
   /**
Index: tandem/js/Tandem.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/Tandem.js	(revision b5815ffcb753d6e7972b8a26fa8681f570625f23)
+++ tandem/js/Tandem.js	(date 1587771540200)
@@ -81,6 +81,14 @@
       supplied: true
     }, options );
 
+    // {Tandem[]}
+    this.children = [];
+
+    if ( this.parentTandem ) {
+      assert && assert( this.parentTandem.hasChild( this.name ) )
+      this.parentTandem.children.push( this );
+    }
+
     // @private
     this.required = options.required;
 
@@ -169,6 +177,7 @@
         arrayRemove( bufferedPhetioObjects, phetioObject );
       }
       else {
+        phetioObject.tandem.dispose();
         for ( let i = 0; i < phetioObjectListeners.length; i++ ) {
           phetioObjectListeners[ i ].removePhetioObject( phetioObject );
         }
@@ -200,7 +209,77 @@
    * @public
    */
   createTandem( name, options ) {
-    return new Tandem( this, name, this.getExtendedOptions( options ) );
+
+    options = this.getExtendedOptions( options );
+
+    // re-use the child if it already exists, but make sure it behaves the same.
+    if ( this.hasChild( name ) ) {
+      const currentChild = this.getChild( name );
+      assert && assert( currentChild.required === options.required );
+      assert && assert( currentChild.supplied === options.supplied );
+      assert && assert( currentChild instanceof Tandem );
+      return currentChild;
+    }
+
+    return new Tandem( this, name, options );
+  }
+
+  /**
+   * @param {string} name
+   * @returns {boolean}
+   */
+  hasChild( name ) {
+    for ( let i = 0; i < this.children.length; i++ ) {
+      const child = this.children[ i ];
+      if ( child.name === name ) {
+        return true;
+      }
+    }
+    return false;
+  }
+
+  /**
+   * @param {string} name
+   * @returns {*}
+   */
+  getChild( name ) {
+    for ( let i = 0; i < this.children.length; i++ ) {
+      const child = this.children[ i ];
+      if ( child.name === name ) {
+        return child;
+      }
+    }
+
+    // TODO: maybe just return null
+    assert && assert( false, 'name not a child' + name );
+  }
+
+  /**
+   * Get all Tandem children and their children. . . recursively.
+   * @returns {Tandem[]}
+   */
+  getDescendants() {
+    return this.children.concat( ...this.children.map( c => c.getDescendants() ) );
+  }
+
+  /**
+   *
+   * @param {Tandem} child
+   */
+  removeChild( child ) {
+    assert && assert( child instanceof Tandem );
+    arrayRemove( this.children, child );
+  }
+
+
+  /**
+   * @private
+   */
+  dispose() {
+
+    // TODO: this was causing assertion errors, I'm unsure this is needed
+    assert && assert( this.children.length === 0, 'cannot dispose parent when it still has children' );
+    this.parentTandem.removeChild( this );
   }
 
   /**
Index: tandem/js/PhetioObject.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/PhetioObject.js	(revision b5815ffcb753d6e7972b8a26fa8681f570625f23)
+++ tandem/js/PhetioObject.js	(date 1587770256365)
@@ -428,7 +428,7 @@
    */
   propagateDynamicFlagsToChildren: function() {
     assert && assert( _.hasIn( window, 'phet.phetio.phetioEngine' ), 'phetioEngine should be defined' );
-    const children = phet.phetio.phetioEngine.getChildren( this );
+    const children = phet.phetio.phetioEngine.getDescendants( this );
 
     for ( let i = 0; i < children.length; i++ ) {
       const child = children[ i ];


```
</details>

**Comment by zepumph** [comment]
We worked on this more today in the context of https://github.com/phetsims/tandem/issues/173. We committed a change that improved the code responsible to propagating flags to dynamic children by streamlining the usages. We found reasonably good, though unreliable speed up numbers in the chrome dev tools in Natural Selection, but are certain that we are creating less garbage, which will only help with performance (though it is sometimes harder to notice in the profiler).

I'll keep this open and come back after CT is clear.

**Comment by samreid** [comment]
Sims that use GroupTandem are having assertions errors on CT.

**Comment by zepumph** [comment]
The above has three changes. I'm not totally sure which of the three fixed the bug in BAA, but afterwards I can't reproduce it. I am fine leaving it like this, since it was all in deprecated code. Hopefully this cleans up CT a bit. I'll check back tomorrow.

**Comment by zepumph** [comment]
This cleaned up CT! Over to @samreid and/or @chrisklus for a review of the original commits, as well as a glance at the above workaround for the deprecated, GroupTandem pattern.

**Comment by samreid** [comment]
The changes look great.  The only part I wasn't able to determine was whether there is a memory leak for PhetioGroup member tandems.  Imagine a PhetioGroup that only has 10 members at any given time, but keeps cycling through higher and higher indices.  Is there a part of Tandem that knows how to dispose the unused children?  Do we need that?

**Comment by zepumph** [comment]
>but keeps cycling through higher and higher indices. 

Can you explain how this might happen? The only way I can imagine it is in a way where the lower numbers get disposed. When this occurs, that lower number's tandem ('element_0') also get's disposed. See `Tandem.removePhetioObject`. This then plucks that Tandem out of the tree so that it can get garbage collected. That coupled with likely logic in any PhetioObject subtypes disposing children or any Tandems that are children to the tree should be enough to prevent a memory leak here.

>Is there a part of Tandem that knows how to dispose the unused children? Do we need that?

I guess it is the other way around. A disposed child cuts itself out of the tree. Does that make sense?

I think we may have a problem because PhetioObject.dispose doesn't null out `this.tandem`. Should it? I have a hard time remembering what it takes for something to get garbage colelcted. When I added it as a test, we ran into trouble in `PhetioDynamicElementContainer.disposedEventListener` which gets called on a disposed element. Maybe this doesn't matter because the tandem and phetioObject can keep references to each other, and they will get garbage collected together.

**Comment by samreid** [comment]
> When this occurs, that lower number's tandem ('element_0') also get's disposed. See Tandem.removePhetioObject. 

That looks good, thanks!

> Maybe this doesn't matter because the tandem and phetioObject can keep references to each other, and they will get garbage collected together.

An object becomes eligible for garbage collection when there are no references from heap "roots" (I forget the technical term) to the object.  If a program has Root R and objects A and B, where A and B have references to each other, but R doesn't have a reference to either A or B, then A and B are eligible for garbage collection.

This issue seems ready to close.
