### ISSUE TITLE
PhetioGroup.forEach should guard against modification while iterating

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#179]
Related to #172 (collection API for PhetioGroup)

PhetioGroup `forEach` operates on the underlying array, so perhaps it should guard against modification while iterating.  Before iterating, register a listener with `elementCreatedEmitter` and `elementDisposedEmitter` (or better yet, add `countProperty`) and fail if the listener is called. After iterating, remove the listener.

**Comment by samreid** [comment]
`Array` is the de-facto standard collections API in JavaScript, and it doesn't guard against modification.  Why should we choose an inconsistent behavior for our own collections ?

**Comment by pixelzoom** [comment]
@samreid I don't understand your response. Are you saying that we just because JavaScript allows you to shoot yourself in the foot, we should do the same?  And how is a catching a programming error "inconsistent behavior"?  So if Array let's you make a programming error, we should build our APIs to allow the same programming errors?

**Comment by pixelzoom** [comment]
lodash's `_.merge( {}, 1 )` silently ignores its second arg. PhET's `merge( {}, 1 )` notes that the second arg is incompatible with merge and fails an assertion.  Using the argument in https://github.com/phetsims/tandem/issues/179#issuecomment-620683717, why did we bother to improve on lodash's behavior?

**Comment by samreid** [comment]
> @samreid I don't understand your response. 

Basically I was considering this excellent argument:

> If we're clear that the collection is a public property of PhetioGroup, and that it's an Array, then we can rely on the Array API for iterators, etc. Then we'd be using a well-known, flexible collection API (Array) and not have to incur the expense of developing one.

**Comment by pixelzoom** [comment]
Then shall we get rid of PhetioGroup `forEach` if it's not any protection against modification-while-iterating?  Or it it still valuable as a convenient replacement for `group.getArray().forEach(...)`?

**Comment by samreid** [comment]
It seems to be a valuable convenience replacement.

**Comment by zepumph** [comment]
I'm happy either way!

**Comment by pixelzoom** [comment]
I'm not clear on why this was assigned back to me.  @samreid can you please clarify?

**Comment by samreid** [comment]
There were 2 responses to your question in https://github.com/phetsims/tandem/issues/179#issuecomment-621563423.  Now that you received those responses, how do you recommend to proceed for this issue?

**Comment by pixelzoom** [comment]
Thanks for clarifying.  It sounds like no one else agrees that there is value in making `forEach` guard against modification while iterating, and that's it's better to make it behave the same as `getArray().forEach`.  I still don't agree, but feel free to close.

**Comment by samreid** [comment]
https://github.com/phetsims/tandem/issues/172#issuecomment-620673276 says:

> PhetioGroup's primary responsibility is creating and disposing of dynamic PhET-iO elements. It's secondary responsibility is as a collection. If we're clear that the collection is a public property of PhetioGroup, and that it's an Array, then we can rely on the Array API for iterators, etc.  Then we'd be using a well-known, flexible collection API (Array) and not have to incur the expense of developing one.   The most obvious downside is that there's no way to prevent modification-during-iteration programming errors (also true with Array), and it puts the responsibility on the client to properly use `getArray` vs `getArrayCopy`.  I'd be OK with that tradeoff, given the complexity/cost of designing and implementing a collection API for PhetioGroup.

Are we still OK with that tradeoff, or do we want to reopen that decision?

**Comment by pixelzoom** [comment]
I'm still OK with exposing the array via `getArray` and `getArrayCopy`.   I think that's preferable to trying to add a collection API.   That was attempted for ObservableArray (unsuccessfully imo), and I generally find it to be easier/clearer to use `getArray` or `getArrayCopy` there also.

**Comment by samreid** [comment]
Understood, thanks.  It sounds like this issue is ready to close.  Please reopen if that's incorrect.
