### ISSUE TITLE
Move TandemEmitter behavior to Emitter (if possible)

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#18]
We would like to integrate tandem into all core classes, including Emitter.  It may not be possible for Emitter, since Emitter may need to include child Emitters as part of its definition.  We'll have to see.

See https://github.com/phetsims/phet-io/issues/926

**Comment by samreid** [comment]
In the preceding commits @zepumph and I got things working.  I'll leave this open and assigned to myself to double check on Bayes after the change, and assigned to @zepumph to double check the changes and see if there's anything else.

**Comment by samreid** [comment]
Bayes seems OK, @zepumph can you please double check everything?

**Comment by zepumph** [comment]
I think everything looks good to me. Thanks for finishing that up. Closing
