### ISSUE TITLE
Should Tandem instances have a reference to their PhetioObject?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/tandem#186]
So far, PhetioObjects only have a reference to their tandem, but not the other way around. If a PhetioObject is needed by its corresponding `tandem.phetioID`, it can use `phetioEngine.getPhetioObject`.

For testing purposes and if there are enough uses of `phetioEngine.getPhetioObject`, it could be nice to have a reference like `tandemInstance.phetioObject`. For testing, this would be a big improvement because it would eliminate the need for a phetioEngine, and therefore get rid of the need for API tests to run in phet-io brand only. We could also test with a more modular map that was only as populated as the test needed to be, instead of the overhead that comes with initializing `phetioEngine`

**Comment by zepumph** [comment]
We have not yet needed this, and it is easy enough to use the phetioEngine.phetioObjectMap when we need to get from a phetioID to its object. In general, storing this in Tandem goes beyond the scope of Tandem, as a naming-string-based tree library that PhET-iO uses. 

>For testing purposes and if there are enough uses of phetioEngine.getPhetioObject, it could be nice to have a reference like tandemInstance.phetioObject.

There are 13 usages of that. This doesn't seem worth the effort. Closing. Please reopen if you feel differently.
