### ISSUE TITLE
bad phetioComponentOptions validation in PhetioObject

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#189]
In PhetioObject.js:

```js
// phetioComponentOptions can specify either (a) the name of the specific subcomponent to target or (b) use a key from
// DEFAULTS to apply to all subcomponents
const SUPPORTED_PHET_IO_COMPONENT_OPTIONS = _.keys( DEFAULTS ).concat( [

  // NodeIO
  'visibleProperty', 'pickableProperty', 'opacityProperty',

  // TextIO
  'textProperty'
] );
```

Validation of subclass options doesn't belong in PhetioObject. It belongs in the subclasses (Node, Text, RichText). Putting it in PhetioObject leads to bad validation results for other subclasses.

For example, if I add this to my constructor in Bunny.js, it fails a validation assertion:

```js
      phetioComponentOptions: {
        bogusProperty: {}
      }
```

But if I add this, which is equally wrong, there is no complaint:

```js
      phetioComponentOptions: {
        visibleProperty: {}
      }
```

So because  'visibleProperty' is valid for Node, it's considered valid for Bunny, and all other PhetioObject subclasses.

**Comment by zepumph** [comment]
That makes a lot of sense! Over in https://github.com/phetsims/scenery/issues/1046 we are going to remove all components that require `phetioComponentOptions`, and hopefully after that we can deprecate phetioComponentOptions. I would rather work on that than this, but you are right, this is very wrong.

**Comment by pixelzoom** [comment]
> ... hopefully after that we can deprecate phetioComponentOptions. ...

That's going to be fun.  There are currently 74 occurrences of "phetioComponentOptions:".

**Comment by zepumph** [comment]
phetioComponentOptions was removed in  https://github.com/phetsims/tandem/issues/222, and good riddance!.
