### ISSUE TITLE
TandemButtonListener code should be inlined into ButtonListener

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#19]
Similar to #18, we should move TandemButtonListener code to ButtonListener and delete TandemButtonListener.

**Comment by samreid** [comment]
Fixed above, for testing I did:

* manual testing of the data stream where the listener is instrumented
* aqua test for phet-io sims
* tested lint for unit-rates
* spot test for aqua

I'll post on Skype for developer to be aware of this change, closing.

**Comment by samreid** [comment]
On second thought, review sounds best.  @jonathanolson can you please review these changes?

**Comment by jonathanolson** [comment]
Changes look good to me (at least on the Scenery/phet-io side).
