### ISSUE TITLE
improve doc for fromStateSetting

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#190]
The documentation for `fromStateSetting` doesn't tell me anything useful.  I have no idea what it does, or how it's related to validation. 

In PhetioGroup.js and PhetioDynamicElementContainer.js:

```js
   * @param {boolean} [fromStateSetting] - used for validation during state setting.
  ...
  disposeElement( element, fromStateSetting ) {
```

In PhetioGroup.js:

```js
   * @param {boolean} [fromStateSetting] - used for validation during state setting.
   * @returns {PhetioObject}
   * @public (PhetioGroupIO)
   */
  createIndexedElement( index, argsForCreateFunction, fromStateSetting ) {
```

In PhetioGroup.js, as an option to method `clear`:

```js
    options = merge( {
      fromStateSetting: false, // used for validation during state setting (phet-io internal)
```

**Comment by samreid** [comment]
I took a look around but am not clear what is happening here.  @zepumph can you please take a look?

**Comment by zepumph** [comment]
Yes, this is a confusing parameter, and there isn't a clear single place to document all usages of it. I did the best I could of pointing to a single explanation. @pixelzoom please review.

**Comment by pixelzoom** [comment]
Much better documentation, thanks.  I fixed a few typos in the above commit. Closing.
