### ISSUE TITLE
Tandem.REQUIRED is no longer checked

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#192]
Discovered in https://github.com/phetsims/tandem/issues/191

> I tested on a clean working copy by adding an uninstumented `Checkbox` and running with `?phetioValidateTandems` and was surprised to see that this was not caught.  I wonder if I'm testing wrong or if this will need to be corrected.
> 
> UPDATE: @pixelzoom tested on his working copy and saw the same thing.  Creating an instrumented `Checkbox` with `?phetioValidateTandems` (the default) does not trigger any error.

**Comment by samreid** [comment]
This used to be checked at https://github.com/phetsims/tandem/blob/87e72e24a1cf436d1435f1b28f9a2593e800ecfb/js/Tandem.js#L135 but now I don't think objects with `{tandem: Tandem.REQUIRED}` are reaching that point.  @zepumph can you please take a look?

**Comment by pixelzoom** [comment]
Is this a problem in the ph-scale 1.4 release branch? If so, is it something that should be patched, so that we don't make PhET-iO mistakes in 1.4 maintenance releases?

**Comment by zepumph** [comment]
Yes I think that this has been a bug since a commit on June 5th where this was added:

**Comment by pixelzoom** [comment]
>  ph-scale was instrumented before that was broken, and so most likely this isn't effecting that sim. 

The concern is with ongoing maintenance of the 1.4 branch.  There's no telling how long that branch will be the production branch.   And if that branch doesn't correctly detect Tandem.REQUIRED, then it would be possible to accidentally remove a required tandem in a maintenance release.    So once the fix is identified, please investigate patching the ph-scale 1.4 branch.

**Comment by samreid** [comment]
@zepumph are you recommending a check like this?  It appears to test OK.  If we do this, what should we do with the code in Tandem.js that used to do this part?

```diff
Index: js/PhetioObject.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/PhetioObject.js	(revision 6fddb61195a44ba31c825191f0fb2addd768d6df)
+++ js/PhetioObject.js	(date 1595258592175)
@@ -232,6 +232,10 @@
   initializePhetioObject: function( baseOptions, config ) {
     assert && assert( config, 'initializePhetioObject must be called with config' );
 
+    if ( config.tandem && config.tandem.required ) {
+      assert && assert( config.tandem.supplied, 'required tandems must be supplied' );
+    }
+
     // The presence of `tandem` indicates if this PhetioObject can be intiialized. If not yet initialized, perhaps
     // it will be initialized later on, as in Node.mutate().
     if ( !( config.tandem && config.tandem.supplied ) ) {
```

**Comment by zepumph** [comment]
@samreid, could we please pair on this on Friday. I think that would be the "work-around" sort of solution&mdash;quick-and-dirty. I think the best way to proceed is to look at how and why initializePhetioObject is being called. Note that quite a bit of logic is being called even when `!Tandem.PHET_IO_ENABLED`. I would like to take this chunk of code to the next level of cleanliness. I foresee the conversation touching on how PhetioObject and Tandem have a blurred division of responsibility.

**Comment by zepumph** [comment]
Adding blocking publication since it is holding up ph-scale

**Comment by pixelzoom** [comment]
Let me know when this is fixed, so that I can cherry-pick for https://github.com/phetsims/ph-scale/issues/183.

**Comment by zepumph** [comment]
I implemented the above workaround. This is now ready for cherry-picking into RC branches. @samreid I still don't know how to remedy this with the validation that is currently in `Tandem.js`. Can we still discuss this code duplication soon?

**Comment by pixelzoom** [comment]
fba18d1edf4a616d15ba91bb04ed99c5a7883dea has been cherry-picked to ph-scale and ph-scale-basics 1.4 branches for https://github.com/phetsims/ph-scale/issues/183.

**Comment by zepumph** [comment]
I marked this for collaboration to discuss Tandem assertions that don't run often now because of the PhetioObject early exit.

**Comment by zepumph** [comment]
@samreid and I think that having the Tandem.REQUIRED check in Tandem.addPhetioObject and at the beginning of PhetioObject.initializePhetiObject is OK. That is really the only assertion in Tandem.addPhetioObject, so there isn't much duplication. Closing
