### ISSUE TITLE
PhET-iO API error when using 'screens' query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#194]
Noted while working on ph-scale RC issues.

If I run ph-scale in Studio via phetmarks with `screens=3`, I get an API error message when I load the sim into Studio:

```
Assertion failed: PhET-iO API error:
phScale.macroScreen.model.autofillEnabledProperty:  7. Any schema entries in the overrides file must exist in the baseline file.
```

Is this intended or a bug?  If it's intended, how does the PhET-iO client use the screens query param?

Running without `phetioDebug` query parameter eliminates the assertion failure. But hhen how do I enable assertions for development when testing a specific screen?

**Comment by pixelzoom** [comment]
Slack:

Michael Kauzmann  2:25 PM
In the past, phetioValidation was turned off always for built sims, but I think that was compiled into the same channel as everything else now. I think an issue is warranted. Please assign the team.

Sam Reid:house_with_garden:  2:28 PM

Here is a patch that will likely solve it:

```diff
Index: js/phetioAPIValidation.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/phetioAPIValidation.js	(revision 73deca55fb27e7473122e6f952b696c7ec2818bb)
+++ js/phetioAPIValidation.js	(date 1595881692913)
@@ -107,7 +107,10 @@
       return;
     }
-    this.validateOverridesFile();
+    // Validate the overrides file, but only when running with all screens
+    if ( phet.chipper.queryParameters.screens === null && phet.chipper.queryParameters.homeScreen ) {
+      this.validateOverridesFile();
+    }
     if ( !this.referenceAPI ) {
       return;
```

**Comment by pixelzoom** [comment]
I have no idea if this should be blocking, or if it should be cherry-picked for ph-scale 1.4.

**Comment by zepumph** [comment]
>Here is a patch that will likely solve it:


Is that the only phetioAPI validation rule section that we want to guard. I'm pretty sure that API validation should be turned off in  built versions. I feel like there was some sort of guard about that, where `phetioAPIValidation.enabled` was set to false when in production. I could be miss-remembering though.

**Comment by samreid** [comment]
I have a better patch on the way

**Comment by samreid** [comment]
In the commit, validation is only run when enabled and using the guard for default values of ?screens and ?homeScreen.  It tests OK in ph-scale-basics?screens=3.  @zepumph can you please review at your convenience?

**Comment by samreid** [comment]
This is showing issues on CT like:

```
gravity-and-orbits : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/gravity-and-orbits/gravity-and-orbits_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595883609202%22%2C%22timestamp%22%3A1595884896268%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'gravityAndOrbits.general.view.navigationBar.phetButton.phetMenu.aboutDialogCapsule.archetype.termsPrivacyAndLicensingLinkText.pickableProperty' of null
TypeError: Cannot read property 'gravityAndOrbits.general.view.navigationBar.phetButton.phetMenu.aboutDialogCapsule.archetype.termsPrivacyAndLicensingLinkText.pickableProperty' of null
at PhetioAPIValidation.onPhetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/tandem/js/phetioAPIValidation.js:260:82)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/phet-io/js/phetioEngine.js:434:25)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/phet-io/js/phetioEngine.js:634:49)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/tandem/js/Tandem.js:165:38)
at NodeProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/tandem/js/PhetioObject.js:343:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/tandem/js/PhetioObject.js:189:10)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/axon/js/Property.js:69:5)
at new NodeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/scenery/js/util/NodeProperty.js:32:5)
at new NodeIO (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/scenery/js/nodes/NodeIO.js:25:30)
at new RichTextIO (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595883609202/scenery/js/nodes/RichTextIO.js:23:5)
id: Bayes Chrome
Snapshot from 7/27/2020, 3:00:09 PM
```

I'll investigate

**Comment by samreid** [comment]
I pushed a proposed fix, ready for CT and review again.

**Comment by chrisklus** [comment]
I updated a comment and a TODO above. Also, if a sim with 3 screens is run with `screens=1,2,3` (default), then validation will still be off. Is that desirable? It may not be worth the trouble to support this case - I'm fine with turning off validation whenever `screens` is provided.

**Comment by samreid** [comment]
Thanks @chrisklus I had the same concern.  Ideally `phetioAPIValidation` would be able to ask `sim.areAllScreensInstantiated` and use that to determine whether it should be `enabled`.  However, at the moment, `phetioAPIValidation` is a singleton that determines its `enabled` value during construction.  Let's check in with @zepumph.

**Comment by zepumph** [comment]
The above seems reasonable. I am ok with duplication, but I could also see us using an `initialize` pattern, as we do in other phet-io classes, which would allow us to set `enabled` based on screens passed to the Sim's constructor. I don't know if that is worth the hassle right now though. 

Reviewing the individual commits, I don't really know if it is best to turn all validation off based on that parameter, I liked the way it was before, where it only checked that where necessary (`onSimStarted`). Maybe it would be best to just tuck the overrides piece into that conditional checking if screens===null. For example, the way that https://github.com/phetsims/tandem/blob/dd5a0acdd10e99ed20ab4f8989458030b63d084d/js/phetioAPIValidation.js#L98 looks.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/tandem/issues/194#issuecomment-664622244:
> I have no idea if this should be blocking, or if it should be cherry-picked for ph-scale 1.4.

Still no idea if I need to patch this for ph-scale RC.  Tracking in https://github.com/phetsims/ph-scale/issues/190.

**Comment by zepumph** [comment]
I think this should block ph-scale, for the case when a screen parameter is provided in built studio with the `phetioDebug` parameter on. This could error out.

**Comment by samreid** [comment]
> which would allow us to set `enabled` based on screens passed to the Sim's constructor. I don't know if that is worth the hassle right now though. 

There are callbacks to `onPhetioObjectAdded` before the Sim constructor is called, so waiting for Sim constructor could be too late.

> Reviewing the individual commits, I don't really know if it is best to turn all validation off based on that parameter, I liked the way it was before, where it only checked that where necessary (onSimStarted).

I'm happy with either paradigm "phetioAPIValidation is fully disabled when not creating all screens" vs "we will always try to check as much as possible", but I would not be able to address that this week.  @zepumph or @chrisklus please feel free to proceed if we agree to go with the latter, or reassign me if I should work on it next week.  Also, does that level of detail block publication?

**Comment by zepumph** [comment]
I am inclined to agree with you, let's turn validation off when specifying and screens parameter (since it is already implemented). With that in mind what is left for this issue?

**Comment by samreid** [comment]
On slack, I said:

The recommendations that came from the code review were (a) a better way to know if the sim is creating all screens and (b) enabling some validations when the sim isn’t creating all screens.  What if we create separate non-blocking issues for those recommendations, and give SHAs to pixelzoom to move forward?

**Comment by zepumph** [comment]
I created https://github.com/phetsims/tandem/issues/195, a non-blocking cleanup issue.

@pixelzoom, please cherry-pick the following:
https://github.com/phetsims/tandem/commit/c9e004d052a00c503c9d5968b0283b2b0789599a
https://github.com/phetsims/tandem/commit/a514ecb8e8ea8e42718998ccd1548358fc0b6cff

@KatieWoe please confirm this is fixed in ph-scale during the next test with the following two step process:
* Note that this throws an error: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-rc.1/phet-io/wrappers/studio/?phetioDebug&screens=1
* Add the same parameters (?phetioDebug&screens=1) to studio in the new version and make sure it doesn't error.

**Comment by pixelzoom** [comment]
I verified the fix in master, so @jbphet is cleared for his RCs.

But I'm running into a merge problem with cherry-picking for ph-scale 1.4 and ph-scale-basics-1.4:

```
% cd perennial
% grunt checkout-target --repo=ph-scale --target=1.4
% cd tandem
% git checkout ph-scale-1.4
% git cherry-pick c9e004d052a00c503c9d5968b0283b2b0789599a
% git cherry-pick a514ecb8e8ea8e42718998ccd1548358fc0b6cff
error: could not apply a514ecb... Avoid baseline check and guard all enabled on query parameters, see https://github.com/phetsims/tandem/issues/194
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
% 
```

The conflicts are in phetioValidation.js, and WebStorm shows:

e72559457341f9bb74efc4e462c84c7f74ea3127:
```js
68 this.enabled = assert && Tandem.PHET_IO_ENABLED;
```

Base version:
```js
68 this.enabled = assert && Tandem.VALIDATION;
```

Changes from server:
```js
    this.enabled = assert &&
                   Tandem.VALIDATION &&
                   phet.chipper.queryParameters.screens === null &&
                   phet.chipper.queryParameters.homeScreen;
```

Assigning to @zepumph, please advise on how to resolve.

**Comment by zepumph** [comment]
Please add the screens related conditional to your sha's. There should be a direct swapping from PHET_IO_ENABLED to VALIDATION in master that you can ignore in your branch. Please field any other questions today through @chrisklus.

**Comment by pixelzoom** [comment]
> There should be a direct swapping from PHET_IO_ENABLED to VALIDATION in master that you can ignore in your branch. 

I guess this means that I should change Tandem.VALIDATION to Tandem.PHET_IO_ENABLED in the merge conflict in phetioApiValidation.js.   So I changed this:

```js
    this.enabled = assert &&
                   Tandem.VALIDATION &&
                   phet.chipper.queryParameters.screens === null &&
                   phet.chipper.queryParameters.homeScreen;
```

To this:

```js
    this.enabled = assert &&
                   Tandem. PHET_IO_ENABLED &&
                   phet.chipper.queryParameters.screens === null &&
                   phet.chipper.queryParameters.homeScreen;
```

Seems to work OK in ph-scale 1.4 and ph-scale-basics-1.4, but makes me nervous to be doing partial cherry-picks.

Closing.
