### ISSUE TITLE
Should phetioAPIValidation.enabled be based on `?screens`?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#195]
From https://github.com/phetsims/tandem/issues/194, the phet-io team fixed an immediate bug, but it could use some improvement. From https://github.com/phetsims/tandem/issues/194#issuecomment-665975148 I said:

>Reviewing the individual commits, I don't really know if it is best to turn all validation off based on that parameter, I liked the way it was before, where it only checked that where necessary (`onSimStarted`). Maybe it would be best to just tuck the overrides piece into that conditional checking if screens===null. For example, the way that https://github.com/phetsims/tandem/blob/dd5a0acdd10e99ed20ab4f8989458030b63d084d/js/phetioAPIValidation.js#L98 looks.

@samreid then said that he agreed and thought that it was best to only have this check in the `onSimStarted`. We should just make sure to cover the overrides check also, unlike the linked line of code above.

Marking as high priority as it is a cleanup step that would be good to do soon.

**Comment by samreid** [comment]
Implemented in the commit and ready for review.  Maybe a nice improvement would be to add unit tests for `allScreensCreated`, but I wasn't sure that was worth the time.  @zepumph can you please review and advise?

**Comment by samreid** [comment]
In the commit, I added the unit tests.

**Comment by zepumph** [comment]
Everything looks really nice. Thanks for this addition. I think it is more complete and nicer in general. It was very cool to compare as Sets as a way to ignore ordering. Good work!
`_.isEqual( new Set( allSimScreens ), new Set( selectedSimScreens ) ) `
