### ISSUE TITLE
It is possible that some test html files were updated for validation?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#196]
In https://github.com/phetsims/tandem/issues/191#issuecomment-663259433 @zepumph said:

> It is possible that some test html files were updated, for example I hit a validation flag change while calling grunt update for studio-tests.html over in phetsims/studio#171

**Comment by samreid** [comment]
I did run `grunt update` after making that change.  Did I miss something, or run it on a file that did not need it?  What else needs to be done to close this issue?  Or will it be covered by https://github.com/phetsims/tandem/issues/199 ?

**Comment by zepumph** [comment]
I think it is covered by #199. Thanks!
