### ISSUE TITLE
Make the default value for phetioValidation be false

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#197]
In https://github.com/phetsims/tandem/issues/191#issuecomment-663259433 @zepumph said:

> * `?phetioValidation` has a defaultValue that we never intend to use. I think it would be prefereable to make the default value `null`, then the line in Tandem can be a be consolidated:
```js
const VALIDATION = PHET_IO_ENABLED && !PRINT_MISSING_TANDEMS && ( phet.preloads.phetio.queryParameters.phetioValidation || packageJSON.phet[ 'phet-io' ].validation );
```

>  Or maybe some other way  that provides proper precedent to the query parameter.

**Comment by samreid** [comment]
I replied:

Can a type: boolean query parameter have a default value of null?

**Comment by samreid** [comment]
@zepumph replied:

> Looks like not. I played around with a custom boolean/null type like so:
```js
    phetioValidation: {
      type: 'custom', defaultValue: null,
      parse: x => x === 'true' ? true : x === 'false' ? false : x,
      isValidValue: value => typeof value === 'boolean' || value === null
    },
```

> It worked, but did not actually make the Tandem.js usage any better. My recommendation is to keep it. The only issue I can think of running into down the road is if we eventually set up wrapper side code to always provide the query parameter, like our pattern for `phetioEmitHighFrequencyEvents`. Would there ever be a case where we provided it via the query parameter like that but we wanted to read from packageJSON? I don't think we need to worry about this right now; just brainstorming.

**Comment by samreid** [comment]
I also asked:

> Should it use `containsKey` instead?

**Comment by samreid** [comment]
The current version in master is using `containsKey`

```js
const IS_VALIDATION_QUERY_PARAMETER_SPECIFIED = window.QueryStringMachine && QueryStringMachine.containsKey( 'phetioValidation' );
```

**Comment by zepumph** [comment]
The rc.js validation check didn't get changed. I think the above is what we want.

**Comment by zepumph** [comment]
containsKey seems to work quite well. Closing
