### ISSUE TITLE
Make phet-io validation default to true, but allow package.json to opt out

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#199]
In https://github.com/phetsims/tandem/issues/191#issuecomment-670708542

I said:

> How about if we default validation to true & it doesn't need to be specified in package.json.  The only allowed value in package.json is "validation: false"?  We would never assert that the package.json flag is provided.  I don't want the validation to default to false, or to have to visit every package.json and add "validation:true" to it once it is ready.
> 
> If that sounds agreeable, I can proceed on that.  Otherwise we should probably schedule for Wednesday discussion before I continue.

**Comment by samreid** [comment]
@zepumph replied:

I think that is the appropriate solution. It is opposite from all the other "opt in" flags in package.json, but that is the only con I can think of. I think in practice, only the few sims currently being worked on in initial development (less than 5?) will opt out of validation. So it makes the most sense to set things up sparsely like that. 

- [ ] Please also make sure to update the instrumentation guide appropriately to communicate this opt-out flag to be used in initial development, as well as a place to remind devs to turn validation back on.

**Comment by samreid** [comment]
Implemented and ready for review.

**Comment by zepumph** [comment]
@samreid and I talked and think that it is likely ok to allow `validation:true` in package.json, as we feel like it will likely be a stepping stone when turning on validation. Instead of deleting that line, someone will swap a `false` for a `true`.

**Comment by zepumph** [comment]
This is the code that will need to go:

```

// Validation defaults to true, so should only appear in package.json as "validation": false as an opt-out.
if ( PHET_IO_ENABLED && _.hasIn( packageJSON, 'phet.phet-io.validation' ) ) {
  assert && assert( packageJSON.phet[ 'phet-io' ].validation === false, 'validation can only be specified as false as an opt-out' );
}

```

**Comment by samreid** [comment]
I pushed a commit, now validation: true is allowed.

**Comment by zepumph** [comment]
Looks really good to me, thanks.
