### ISSUE TITLE
provide basic documentation for how to instrument a sim

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#2]
In https://github.com/phetsims/beers-law-lab/issues/99, it was decided that beers-law-lab should be fully instrumented (a) because it's partially done to support concentration, and (b) to give me an opportunity to instrument a sim while the API is still in flux.

@samreid suggested in https://github.com/phetsims/beers-law-lab/issues/99#issuecomment-98429168:
> Before @pixelzoom starts on this, it would be good for @jbphet & @samreid to provide some documentation/instruction/support that @pixelzoom or other instrumentors would be able to use.

It was agreed, and @jbphet was assigned to provide the documentation.

**Comment by pixelzoom** [comment]
Labeling this issue as high priority.  It's a prerequisite to me instrumenting beers-law-lab, and I'm a little concerned that things are continuing to evolve (and perhaps become solidified) for specific customers, without me (or anyone other than @samreid and @jbphet) having experience with instrumenting a sim.

**Comment by ariel-phet** [comment]
Plan is for @pixelzoom and @jbphet to pair on instrumenting beer's law and then give an outline on useful documentation

**Comment by samreid** [comment]
Instrumentation documentation will be created as part of https://github.com/phetsims/together/issues/114, closing.
