### ISSUE TITLE
optimize PhetioObject.initializePhetioObject

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#200]
PhetioObject.initializePhetioObject was identified as a potential bottleneck in https://github.com/phetsims/natural-selection/issues/60#issuecomment-672366041:

> When I drill down into `stepSimulation.execute.(anonymous).step`, I see lots of occurrences of `PhetioObject.initializePhetioObject`, each one being only 1% or 2%.  But looking at Bottom-Up view, they add up to a whopping 16.4% (see screenshot below). Perhaps there's something that can be optimized there. 

<img width="647" alt="screenshot_477" src="https://user-images.githubusercontent.com/3046552/89959222-1abaa280-dbf9-11ea-9c8a-5aa38fa66737.png">

And in https://github.com/phetsims/natural-selection/issues/60#issuecomment-672368009 I identified no-op calls to `validate` as significant:

> `PhetioObject.initializePhetioObject` contains 14 calls to `validate`, which are no-ops when `assert` is disabled.  Why are these not short-circuited, so that we aren't calling a no-op function 14x for every PhetioObject?  If I comment out the 14 calls to `validate`, `initializePhetioObject` drops from 16.4% to 5.5% in Bottom-Up view:

<img width="851" alt="screenshot_478" src="https://user-images.githubusercontent.com/3046552/89959889-a84ac200-dbfa-11ea-9f03-9bcfc8459c20.png">

**Comment by samreid** [comment]
I added the guard in the above commit.

**Comment by pixelzoom** [comment]
Thanks for doing that.  This is a nice "quick fix" for this specific problem in initializePhetioObject. 

But now we have `assert && validate(...)` and an additional `assert` test inside `validate`.    I see 150 other occurrences of `validate`, all making unnecessary function calls when assertions are disabled.   Some of these are in critical code, like a for loop in Action.js.  Should other uses of `validate(...)` be changed to use this `assert && validate(...)` pattern?

**Comment by pixelzoom** [comment]
Thanks for doing that.  This is a nice "quick fix" for this specific problem in `initializePhetioObject`. 

But now we have `assert && validate(...)` and an additional `assert` test inside `validate`.    I see 150 other occurrences of `validate`, all making unnecessary function calls when assertions are disabled.   Some of these are in critical code, like in a for loop in Action.js, and throughout serialization methods in IO types.  

Should other uses of `validate(...)` be changed to use the `assert && validate(...)` pattern?    Or should `validate` be re-written to be like assert, i.e. `validate && validate(...)`?

**Comment by pixelzoom** [comment]
> ... Or should `validate` be re-written to be like assert, i.e. `validate && validate(...)`?

Something like:

```js
let validate = assert && ( value, validator, options ) => {

  // Throws an error if not valid
  ValidatorDef.isValueValid( value, validator, merge( { assertions: true }, options ) );
  return value;
};
validate = validate || null;

axon.register( 'validate', validate );
export default validate;
```

**Comment by pixelzoom** [comment]
Hmmm... I guess that won't work for cases like this that are relying on `validate` returning a value:

```
// wave-interference.Scene
   this.waveSpatialType = validate( config.waveSpatialType, { validValues: Scene.WaveSpatialType.VALUES } );
```

**Comment by samreid** [comment]
I opened https://github.com/phetsims/axon/issues/323 for the more general case.  Can this issue be closed?

**Comment by pixelzoom** [comment]
Yes, OK to close.
