### ISSUE TITLE
Support setting a partial instead of total state

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#201]
From phetsims/phet-io#1697: There is 1 or more call to phetioStateEngine.stateSetEmitter.addListener. There is now a 2nd argument to the listener, which is a predicate that tests Tandems and returns true if they are in scope. We should check these listeners and see if any of them need to check whether they are in scope of a partial state set.

**Comment by zepumph** [comment]
This has been handled, and converted to use the most recent, best pattern in the parent's parent issue, see https://github.com/phetsims/tandem/commit/02cd469987adf23ab4c07125b0165662cf8c9b03. The other usage in PhetioGroup is already well set up to support partial state setting. Closing
