### ISSUE TITLE
memory leak in Tandem.removePhetioObject

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#203]
Over in https://github.com/phetsims/natural-selection/issues/189#issuecomment-680124352, I identified a huge memory leak in Natural Selection due to PhET-iO, even with `brand=phet`.  I determined that 0 instances of Tandem and DynamicTandem were being deleted.  

@samreid helped me identify the source of the problem. The leak was introduced on 5/1/2020 in 571cc878aeb3ecb42cf7a8b38532e2808ea571e0  for https://github.com/phetsims/tandem/issues/176.  It affects all sims that have been published since then.

@samreid provided the patch below, which I confirmed address the leaking of Tandem and DynamicTandem in natural-selection. This patch needs to be reviewed by @zepumph, with top priority.

<details>
<summary>patch</summary>

```diff
Index: js/Tandem.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/Tandem.js	(revision fbd3b1c92b1d25369476ea270402326632ef632e)
+++ js/Tandem.js	(date 1598374832259)
@@ -202,12 +202,13 @@
         arrayRemove( bufferedPhetioObjects, phetioObject );
       }
       else {
-        phetioObject.tandem.dispose();
+
         for ( let i = 0; i < phetioObjectListeners.length; i++ ) {
           phetioObjectListeners[ i ].removePhetioObject( phetioObject );
         }
       }
     }
+    phetioObject.tandem.dispose();
   }
   /**
```

</details>

Then we need to identify which sims have been published with this problem, decide which to patch, schedule maintenance releases, etc. 

Assigning to @jbphet because this leak is almost certainly present in the recently-published SOM.

**Comment by pixelzoom** [comment]
This is blocking ph-scale RC, see  phetsims/ph-scale#199.

**Comment by pixelzoom** [comment]
This is blocking natural-selection prototype RC, see https://github.com/phetsims/natural-selection/issues/205.

**Comment by pixelzoom** [comment]
This is blocking ph-scale RC, see phetsims/ph-scale#199.  Milestone for 1.4 publication is ??

This is blocking natural-selection prototype RC, see https://github.com/phetsims/natural-selection/issues/205. Milestone for publication is "this week if possible".

**Comment by samreid** [comment]
The patch disposes of the Tandem in every brand, not just in phet-io.  It looks correct to me, leaving assigned to @zepumph to confirm.

**Comment by samreid** [comment]
I decided to commit the proposal, still ready for review.

**Comment by zepumph** [comment]
This change looks good to me. I would also add that this is better to dispose after calling phetioObjectRemoved listeners because those listeners may depend on the tandem (like phetioAPIValidation.onPhetioObjectRemoved). Good catch and thanks for the implementation. I did not test to confirm that it fixed the memory leak. I only looked at the code.

**Comment by zepumph** [comment]
Any rc taken after 5/1 would be effected by this. I know that means at least:
* ph-scale
* SOM

@Denz1994 I'm unsure about BaM
@chrisklus, I'm unsure about EFAC

This fix should be very simple though, just cherrypick https://github.com/phetsims/tandem/commit/dc10b0352a7650599cd79be48f50c60ef6f328ea. This issue effects `brand=phet`.

**Comment by zepumph** [comment]
Assigning to @Denz1994 and @chrisklus to determine if their RC was made after 5/1. If so to apply the patch, either in this issue or a sim-specific one. 

The patch is https://github.com/phetsims/tandem/commit/dc10b0352a7650599cd79be48f50c60ef6f328ea.

**Comment by zepumph** [comment]
Any RC with shas after 5/1 has a memory leak in phet brand in https://github.com/phetsims/tandem/issues/203. I know of only what I spoke of above. Assigning to @ariel-phet to make sure that this doesn't effect other sims published. Likely there are prototypes that effect this, but maybe we don't care about memory leaks in those.

**Comment by samreid** [comment]
Shouldn't we use the batch maintenance release process to automatically identify all live branches with this bug and automatically or semi-automatically fix them?

**Comment by pixelzoom** [comment]
Is this issue ready for verification in Natural Selection, so that I can resolve phetsims/natural-selection#205 and move forward with prototype publication?

**Comment by samreid** [comment]
Yes, please pull and test to confirm this is ready for Natural Selection.  This has been fixed and reviewed in master.  The only reason this issue remains open is to see what branches it may need to be cherry-picked to.

**Comment by pixelzoom** [comment]
Memory tests look good for both NS brands, see https://github.com/phetsims/natural-selection/issues/189 and https://github.com/phetsims/natural-selection/issues/190. Closing.

**Comment by pixelzoom** [comment]
Oops. Reopening because @samreid said:
>  The only reason this issue remains open is to see what branches it may need to be cherry-picked to.

**Comment by zepumph** [comment]
Agreed. EFAC will be taken (was taken yesterday?) from master. I think all that is left is to do is for @Denz1994 to patch BAM if needed.

**Comment by Denz1994** [comment]
Thanks, @zepumph for the direction. This was patched in BAM. Removing my assignment.

**Comment by zepumph** [comment]
Sounds good. I don't any other sims are in RC right now. Over to @ariel-phet to confirm and close

**Comment by ariel-phet** [comment]
I think we are good here, closing
