### ISSUE TITLE
factor out a constant for 'IO' suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#205]
IO Types are supposed to end with 'IO'. While working on https://github.com/phetsims/tandem/issues/188, I discovered that 'IO' is duplicated throughout the code.  Examples:

6x in ObjectIO:

```js
  assert && assert( typeName.endsWith( 'IO' ) || typeName.includes( 'IO<' ), 'IO type name must end with IO' );
...
    assert && assert( splitOnParameters.indexOf( 'IO' ) === splitOnParameters.length - 'IO'.length, 'type name must end with IO' );
```

2x in PhetioElementView.js:

```js
    assert && assert( _.endsWith( baseTypeName, 'IO' ), 'IO typename should end in "IO"' );
```

... and those counts include the suffix that's mentioned in the assert messages.

This is by no means a complete list. 

Highly recommended to factor out a constant that is used by all code.

**Comment by pixelzoom** [comment]
This constant now appears in an addition place, in natural-selection createIOType.js:

`const IO_TYPE_SUFFIX = 'IO';`

**Comment by pixelzoom** [comment]
I needed this constant in order to proceed with https://github.com/phetsims/tandem/issues/188#issuecomment-689779651.  So I've added this to ObjectIO:

```js
// Suffix that is required for all IO Type class names
ObjectIO.IO_TYPE_SUFFIX = 'IO';
```

**Comment by samreid** [comment]
I refactored a few more usages to use `ObjectIO.IO_TYPE_SUFFIX`.  The remaining usages are in studio, which shouldn't load `ObjectIO`.  I was wondering if this should be factored out to `PhetioIDUtils` but this isn't for naming a phetioID, it is for naming an IO Type.  @pixelzoom where do you recommend to put this so it can be reused in studio as well?

**Comment by samreid** [comment]
> Presumably you have some other constants that are used through PhET-iO. Where do they live? 

For example, constants and methods used in the simulation code and wrapper code are declared in PhetioIDUtils.js.

Should we create PhetioConstants.js, which at the moment will have one string, but maybe will have more constants one day?

**Comment by pixelzoom** [comment]
> Should we create PhetioConstants.js, which at the moment will have one string, but maybe will have more constants one day?

If it were me, that's probably one of the first files that I would have created.  It's certainly where I'd expect to go looking for constants.  But I don't know know if it's appropriate for this project, or whether there are other constants lurking that could be moved there now.  So... Up to you.

**Comment by samreid** [comment]
I added PhetioConstants, and moved `ObjectIO.IO_TYPE_SUFFIX` there.  I tested in studio unbuilt for natural selection.  Ready for review.

**Comment by pixelzoom** [comment]
👍🏻 closing.
