### ISSUE TITLE
add static events and parameterTypes fields to ObjectIO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#208]
While reviewing #188, I noticed this in the options for `ObjectIO.createIOType`:

```js
    events: [],
    parameterTypes: []
```

These options are not documented. So I when on the hunt for what they are.  I found this for `parameterTypes`:

```js
* schema for a typeName could be defined (using regex) as `[A-Z]\w*IO([(<].*){0,1}`. In most cases, parameterized
 * types should also include a `parameterTypes` field on the TypeIO.
 * @type {string}
 */
ObjectIO.typeName = 'ObjectIO';
```

I couldn't find any documentation for `events`.

Based on the option defaults in `createIOType`, it seems appropriate to add something like this to ObjectIO:

```js
// {typeExpression} description
ObjectIO.events = [];

// {typeExpression} description
ObjectIO.parameterTypes: [];
```

**Comment by zepumph** [comment]
This issue feels like it is taken care of by the new `IOType` class created in #211. I'm going to close this now.
