### ISSUE TITLE
IOType can supply default state methods by using `valueType`

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#213]
This is explained in https://github.com/phetsims/tandem/issues/211#issuecomment-698819668, but deserves its own issue for investigation.

**Comment by samreid** [comment]
Here is the relevant part of that comment:

If we automatically leverage `valueType` in ObjectIO like so:

```js
ObjectIO = new IOType( 'ObjectIO', {
  isValidValue: () => true,
  supertype: null,
  documentation: 'The root of the IO Type hierarchy',
  toStateObject: function( coreObject ) {
    return coreObject.toStateObject ? coreObject.toStateObject() : coreObject;
  },
  fromStateObject: function( stateObject ) {
    return this.valueType && this.valueType.fromStateObject ? this.valueType.fromStateObject( stateObject ) : stateObject;
  },
  stateToArgsForConstructor: function( stateObject ) {
    return this.valueType && this.valueType.stateToArgsForConstructor ? this.valueType.stateToArgsForConstructor( stateObject ) : [];
  },
  applyState: function( coreObject, stateObject ) {
    coreObject.applyState ? coreObject.applyState( stateObject ) : null;
  }
} );
```

Then 7 IO Type declarations in Natural Selection change from looking like this:

```js
Wolf.WolfIO = new IOType( 'WolfIO', {
  valueType: Wolf,
  toStateObject: wolf => wolf.toStateObject(),
  stateToArgsForConstructor: Wolf.stateToArgsForConstructor,
  applyState: ( wolf, stateObject ) => wolf.applyState( stateObject )
} );
```

to looking like this:

```js
Wolf.WolfIO = new IOType( 'WolfIO', {
  valueType: Wolf
} );
```

**Comment by samreid** [comment]
Why does it make sense to take some things from the core type, such as `CoreType.fromStateObject`, but other things cannot be taken from the core type, such as `CoreType.phetioMethods` being taken as the IO Type `methods` or `CoreType.phetioDocumentation` being taken as the IO Type `documentation`?

**Comment by samreid** [comment]
Note the philosophy for this issue was introduced in https://github.com/phetsims/tandem/issues/188, may be good to skim that issue before closing this one, to make sure our bases are covered.

**Comment by samreid** [comment]
@zepumph and I disussed these APIs

```js
// Reasonable
Bunny.BunnyIO = new IOType( 'BunnyIO', {
  valueType: Bunny,
  fromCoreType: true
} );

// Possibly better?
Bunny.BunnyIO = IOType.fromCoreType( 'BunnyIO', Bunny );
```

**Comment by samreid** [comment]
It may be more seamless to move static methods to the core types if we support `static` attribute, see https://github.com/phetsims/tasks/issues/1048

**Comment by samreid** [comment]
@pixelzoom can you please review the proposal in https://github.com/phetsims/tandem/issues/213#issuecomment-699190995 ?  Does it seem too tricky/magical to you?  Or an efficient way to eliminate unnecessary code?

**Comment by pixelzoom** [comment]
Can you explain what an IO Type does other than serialization and type verification?  If the IO Type is delegating to the Core Type, and the IO Type doesn't have other responsibilities, then why is an IO Type necessary?

**Comment by samreid** [comment]
In addition to serialization, IO types form a type system for PhET-iO Elements for wrapper interoperability.  They describe methods, documentation, type hierarchy & events that can be emitted.

**Comment by pixelzoom** [comment]
Could those responsibilities also be folded into the Core Type, or is there value in keeping them separate?

**Comment by samreid** [comment]
There are parts that make that difficult or impossible, such as:

* IO Types that don't correspond to a core type, such as `NumberIO`, `StringIO`, `VoidIO`, `ArrayIO`, `BooleanIO`, `FunctionIO`, `Float64ArrayIO`.
* Parametric IO Types, such as `PropertyIO<Vector2IO>`
* Nullable IO Types, such as `NullableIO<StringIO>`

**Comment by pixelzoom** [comment]
OK, thanks for clarifying.  So it sounds like doing away with IO Types altogether is not an option.

So back to your original question:
> ... Does it seem too tricky/magical to you? Or an efficient way to eliminate unnecessary code?

If I understand the various options that have been proposed...  I like having the "non-magical" long form, with a factory method for the "magical" short form. For example:

```js
// Long-form
Wolf.WolfIO = new IOType( 'WolfIO', {
  valueType: Wolf,
  toStateObject: wolf => wolf.toStateObject(),
  stateToArgsForConstructor: Wolf.stateToArgsForConstructor,
  applyState: ( wolf, stateObject ) => wolf.applyState( stateObject )
} );

// Short-form, convenience
Wolf.WolfIO = IOType.fromCoreType( 'WolfIO', Wolf, { ... } );
```

**Comment by zepumph** [comment]
I really like this idea! How about the above commit. Please review. I'm mainly wondering if it is too strict to make sure that options doesn't have all 4 of these things:
```js

    if ( assert && options ) {
      assert && assert( !options.hasOwnProperty( 'valueType' ), 'fromCoreType sets its own valueType' );
      assert && assert( !options.hasOwnProperty( 'toStateObject' ), 'fromCoreType sets its own toStateObject' );
      assert && assert( !options.hasOwnProperty( 'stateToArgsForConstructor' ), 'fromCoreType sets its own stateToArgsForConstructor' );
      assert && assert( !options.hasOwnProperty( 'applyState' ), 'fromCoreType sets its own applyState' );
    }

```

**Comment by pixelzoom** [comment]
@zepumph asked:
> ... I'm mainly wondering if it is too strict to make sure that options doesn't have all 4 of these things:

I think that's perfect for now.  If we find a reason that one of those options should be applied, we can change later. 

Question...  I see this in `fromCoreType`:

```js
225 stateToArgsForConstructor: CoreType.stateToArgsForConstructor,
```

What happens in CoreType doesn't have `stateToArgsForConstructor`?  I'd like to `fromCoreType ` for several other IO Types in Natural Selection that have this boilerplate, and the Core Type does not define `stateToArgsForConstructor`:

```js
GenePair.GenePairIO = new IOType( 'GenePairIO', {
  valueType: GenePair,
  toStateObject: genePair => genePair.toStateObject(),
  applyState: ( genePair, stateObject ) => genePair.applyState( stateObject )
} );
```

**Comment by zepumph** [comment]
What about this patch?

```js
  static fromCoreType( ioTypeName, CoreType, options ) {

    if ( assert && options ) {
      assert && assert( !options.hasOwnProperty( 'valueType' ), 'fromCoreType sets its own valueType' );
      assert && assert( !options.hasOwnProperty( 'toStateObject' ), 'fromCoreType sets its own toStateObject' );
      assert && assert( !options.hasOwnProperty( 'stateToArgsForConstructor' ), 'fromCoreType sets its own stateToArgsForConstructor' );
      assert && assert( !options.hasOwnProperty( 'applyState' ), 'fromCoreType sets its own applyState' );
    }

    options = merge( {
      valueType: CoreType,
      toStateObject: coreType => coreType.toStateObject(),
      forwardStateToArgesForConstructor: true, // Only needed for dynamic-element deserialization
      forwardApplyState: true // Only needed for reference-type deserialization
    }, options );

    if ( options.forwardApplyState ) {
      options.applyState = ( coreType, stateObject ) => coreType.applyState( stateObject );
    }
    if ( options.forwardStateToArgesForConstructor ) {
      options.stateToArgsForConstructor = CoreType.stateToArgsForConstructor;
    }
    return new IOType( ioTypeName, options );
  }
```

?

**Comment by pixelzoom** [comment]
> What about this patch?

I don't like `forwardStateToArgesForConstructor ` and `forwardApplyState`, they are a little too "indirect" for my tastes.

I also don't understand this line in the patch:

```js
forwardApplyState: true // Only needed for reference-type deserialization
```

Is that comment correct? WolfIO uses dynamic element serialization, and it's definition options.applyState. And is applyState really optional with `fromCoreType`?  I guess I'm not clear on which serialization situations use `fromCoreType`, and that should be documented.

With those caveats, and if `stateToArgsForConstructor` and `applyState` are truly optional....

How about this implementation?

```js
  static fromCoreType( ioTypeName, CoreType, options ) {

    if ( assert && options ) {
      assert && assert( !options.hasOwnProperty( 'valueType' ), 'fromCoreType sets its own valueType' );
      assert && assert( !options.hasOwnProperty( 'toStateObject' ), 'fromCoreType sets its own toStateObject' );
      assert && assert( !options.hasOwnProperty( 'stateToArgsForConstructor' ), 'fromCoreType sets its own stateToArgsForConstructor' );
      assert && assert( !options.hasOwnProperty( 'applyState' ), 'fromCoreType sets its own applyState' );
    }

    options = merge( {
      valueType: CoreType,
      toStateObject: coreType => coreType.toStateObject(),
    }, options );

    if ( CoreType.stateToArgsForConstructor ) {
      options.stateToArgsForConstructor = CoreType.stateToArgsForConstructor;
    }

    if ( CoreType.prototype.applyState ) {
      options.applyState = ( coreType, stateObject ) => coreType.applyState( stateObject );
    }

    return new IOType( ioTypeName, options );
  }
}
```

One more nit... `options` should be `config` in all of the above, because the param to `IOType` constructor is `config`.

**Comment by zepumph** [comment]
Sounds reasonable to me!

One small issue:
```
    if ( CoreType.prototype.applyState ) {
      options.applyState = ( coreType, stateObject ) => coreType.applyState( stateObject );
    }
```

This will not look up the hierarchy. We could recurse though.

**Comment by pixelzoom** [comment]
Good point.  And this will also not recurse (in case you missed this addition):

```js
    assert && assert( CoreType.prototype.toStateObject, 'class CoreType must implement method toStateObject' );
```

**Comment by zepumph** [comment]
We can use [Inheritance.js](https://github.com/phetsims/phet-core/blob/e3a8916b3cbf1e1b1d9fb763d2bd26436cf1b42d/js/inheritance.js) as an example of how to recurse for these checks.

**Comment by pixelzoom** [comment]
@zepumph if you need test cases for `fromCoreType`, feel free to modify the Natural Selection IO Types listed in https://github.com/phetsims/natural-selection/issues/255.

**Comment by zepumph** [comment]
>One more nit... options should be config in all of the above, because the param to IOType constructor is config.

I disagree. `fromCoreType` doesn't require anything to be provided via its options, because it sets the require pieces in `fromCoreType` (`valueType`).

I added documentation saying that `toStateObject` is required, but any deserialization method is gracefully supported. I felt good enough to convert all usages worth it in Natural Selection, and I also converted Vector2 to test `fromStateObject` (which I added support for too).

@pixelzoom please review.

**Comment by pixelzoom** [comment]
>> One more nit... options should be config in all of the above, because the param to IOType constructor is config.
>
> I disagree. fromCoreType doesn't require anything to be provided via its options, because it sets the require pieces in fromCoreType (valueType).

OK.  I took it for granted that the `config` param to `fromCoreType` was correct, but that's apparently not the case since you changed it to `options`.  In any case, they params are not consistent, and I don't see anything config-y in `fromCoreType`, so bravo!

Closing.
