### ISSUE TITLE
Use consistent naming for IOTypes on core types

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#214]
from #211, @samreid and I want consistent naming across all our IO Types.

@samreid and I discussed how we want the field on core types to be named that stores the IO Type. We think that always naming it to be the phetioTypeName of the IO Type is clearest. This will look the same for parametric types and non.

Like this:

`Emitter.EmitterIO = parameterTypes => {. . . `
`Wolf.WolfIO= new IOType(. . . `
`      phetioType: Property.PropertyIO( NullableIO( ReferenceIO( Vector2.Vector2IO ) )`

This works well in the above case where we mix IO Types that come from core types with those that have their own file. If there are many usages of an IO Type, you can always store it at the top of a file, like so:
`const PropertyIO = Property.PropertyIO`

We prefer the above to the following:
* Always naming `IOType` like `CoreType.IOType`, `Bunny.IOType`, etc.
* Having parametric types be called a function name like `Emitter.createEmitterIO`.

@samreid offered to take the lead here. We don't think this needs to block publication.

**Comment by samreid** [comment]
I fixed the existing occurrences and will keep this in mind as we proceed in https://github.com/phetsims/tandem/issues/211.  @zepumph can this issue be closed?
