### ISSUE TITLE
How to treat parametric types that have no parameters, such as EmitterIO<>?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#216]
From https://github.com/phetsims/tandem/issues/211, there is a TODO in the IOType constructor:

```js
    // Validate that parametric types look as expected
    // REVIEW: What about EmitterIO<> that has no parameter types?  See https://github.com/phetsims/tandem/issues/211
    // if ( this.typeName.includes( '<' ) ) {
    //   assert && assert( this.parameterTypes.length > 0,
    //     'angle bracket notation is only used for parametric IO Types that have parameter IO Types' );
    // }
```

Should EmitterIO that emits nothing be a parametric type (like other EmitterIO) or a non-parametric type (since it doesn't emit anything)?  I'm uncertain of the assumptions or ramifications for studio.  @zepumph can you please make a recommendation?

If necessary, we could change the default for `parameterTypes` to `null` (meaning non-parametric) instead of `[]` (meaning parametric with 0 parameters).

**Comment by samreid** [comment]
This seems higher than medium priority, and related to https://github.com/phetsims/tandem/issues/223.  Marking "high" until we know more.

**Comment by zepumph** [comment]
I think this is slightly a duplicate of https://github.com/phetsims/tandem/issues/223. Personally, I don't feel like we need to do anything with this issue. It is more important to me that we make sure that `parameterTypes` are set correctly, and not that `<>` are exclusive only to a type with parameters, as it will never be a complete list (like for Function). 

Feel free to close this issue if you agree.

**Comment by samreid** [comment]
I agree it is perfectly natural to use types like `ActionIO<>` etc.  In the commit, I removed the commented-out code, closing.
