### ISSUE TITLE
ReferenceIO should serialize an object with key `phetioID`

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#218]
This is preferred to just being a string, and would allow for it to be a supertype to subtypes that want to add more data. Like https://github.com/phetsims/ph-scale/issues/205

**Comment by zepumph** [comment]
@samreid what do you think about this? Likely review with commits to come over in https://github.com/phetsims/ph-scale/issues/205

**Comment by zepumph** [comment]
One bug fix in studio where the serialized screen was an id, but now it is an object with a phetioID.

**Comment by zepumph** [comment]
There are a couple of bugs the above commits caused, like https://github.com/phetsims/phet-io/issues/1710

**Comment by zepumph** [comment]
Studio is now fuzzing. Unassigning. Ready for review.

**Comment by zepumph** [comment]
We needed to update how studio was serializing valid values, since it didn't support Objects. This original issue commit made a valid value radio button from "my.phetio.id" to `{"phetioID":"my.phetio.id"}`. Fixed in the above commit.

**Comment by samreid** [comment]
CT is clear and these changes look good, nice work @zepumph!  Closing.
