### ISSUE TITLE
Remove Tandem.unlaunch()

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#221]
Now that qunitStart calls `Tandem.launch()`, I'm pretty sure that we can remove this. The only reason we would want to keep it around is if Tandem had tests that needed to split on logic around launched. 

Currently I see 4 usages of Tandem.unlaunch
```
scenery\js\nodes
  NodeTests.js
      Tandem.unlaunch();
tandem\js
  phetioAPITest.js
    Tandem.unlaunch();
    Tandem.unlaunch();
  PhetioObjectTests.js
    Tandem.unlaunch();
  Tandem.js
    static unlaunch() {
```

I think this is preferred to adding more usages to get around problems like https://github.com/phetsims/scenery/issues/1046#issuecomment-707182249. @samreid can you please review this issue, and then either implement or assign back to me for implementation.

**Comment by samreid** [comment]
Can you please review the test in PhetioObjectTest: `'archetype bugginess when Tandem is not launched yet'`, should we keep that one?

That is, can all tests assume that Tandem is launched, and if they need it to be unlaunched, they will take care of that step?

**Comment by zepumph** [comment]
I think it was best to keep Tandem.unlaunch for that one test. I got rid of other usages though. I think this issue is ready to close. @samreid?

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
