### ISSUE TITLE
Get rid of phetioComponentOptions

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#222]
This include `mergePhetioComponentOptions`. 

Tagging https://github.com/phetsims/scenery/issues/1091 and https://github.com/phetsims/scenery/issues/1046 as underlying work. This is on hold until the following are complete:

- [x] https://github.com/phetsims/scenery/issues/1047
- [x] https://github.com/phetsims/scenery/issues/1082

**Comment by samreid** [comment]
Removed in the commit.  I tested several unit tests in both brands, and compared natural-selection API before and after, and saw no differences. Ready for review.

**Comment by zepumph** [comment]
Looks great to me. Thanks! It is so fun to actually remove junk from PhetioObject instead of adding to it.
