### ISSUE TITLE
Extra assertion about '<' correlated with parameterTypes

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#223]
From https://github.com/phetsims/tandem/issues/217, promoting TODO to issue in IOType:

```js

    // Validate that parametric types look as expected
    // TODO: What about EmitterIO<> that has no parameter types?  See https://github.com/phetsims/tandem/issues/217
    // if ( this.typeName.includes( '<' ) ) {
    //   assert && assert( this.parameterTypes.length > 0,
    //     'angle bracket notation is only used for parametric IO Types that have parameter IO Types' );
    // }
```

**Comment by samreid** [comment]
`EmitterIO<>` seems reasonable to me, perhaps that should be a supported feature.  If we keep that, do we need to update anything else?

**Comment by zepumph** [comment]
My goal in this was to make sure that the `parameterTypes` option stayed in line with our typeName conventions. Perhaps the best we could do would be the opposite assertion:

```
    if ( this.parameterTypes.length > 0 ) {
      assert && assert( this.typeName.includes( '<' ), 'parameterTypes should be in the type name' );
    }
```

**Comment by samreid** [comment]
I tried this and it yielded 2 problems:

```js
    // Parametric types should show the parameter types in the type name.  Note the reverse is not true, e.g.,
    // EmitterIO<> has 0 parameterTypes, but still has '<>' in the name.
    if ( assert && this.parameterTypes.length > 0 ) {
      assert && assert( this.typeName.includes( '<' ), 'parameterTypes should be in the type name' );
    }
```

First, the FunctionIO type name doesn't have any `<` at the moment.  Let's decide how it should look.  I think it should be `FunctionIO<ArgIO1,ArgIO2,ReturnIO>` or possibly `FunctionIO<ReturnIO,Arg1IO,Arg2IO>`.

Second, `NumberPropertyIO` specifies `parameterTypes:[NumberIO]` since it is a `PropertyIO`, but it has type name `NumberPropertyIO`.

@zepumph let's discuss how to proceed.

**Comment by samreid** [comment]
This feels like higher priority to me, since it affects public API and how we name and conceptualize the types.

**Comment by samreid** [comment]
I'd like to hear feedback from @zepumph on https://github.com/phetsims/tandem/issues/223#issuecomment-719601299 before working on this issue further.

**Comment by zepumph** [comment]
I like the way that FunctionIO and NumberProperty is currently more than I like having that assertion. If you disagree and would rather change all types with parameters to include `<` then we should discuss this more, perhaps in person.

**Comment by samreid** [comment]
NumberProperty was discussed in https://github.com/phetsims/tandem/issues/216.  @zepumph commented that he prefers FunctionIO the way it is, which is like so: `FunctionIO(${parameterTypesString})=>${returnType.typeName}`.  The code in question was removed as part of #216, closing.
