### ISSUE TITLE
PhetioObject lacks assertion messages for validation failures

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#229]
In https://github.com/phetsims/phet-io/issues/1589#issuecomment-789987905, I identified impediments to PhET-iO instrumentation, including:
> (2) Cryptic assertion messages. These require knowledge of phet-io internals, and don't provide the value(s) that caused the problem. I'll try to note these as I encounter them, instead of powering through and moving on.

A good place to start would be assertion messages for validators in PhetioObject. This is typical of the lack of assertion messages for validators, which is one of the reasons I don't use them.

Here's the example that motivated this issue.  I'm trying to do something that should be simple, add `phetioDocumentation` to a Property:  

```js
phetioDocumentation: 
  'Qualitative vector representation of the dipole, based on the electronegativity difference between the atoms.\n' +
  '+x is to the right, +y is DOWN, and positive rotation is CLOCKWISE.'
```

I get this failure:

```
Assertion failed: value failed isValidValue: Qualitative vector representation of the dipole, based on the electronegativity difference between the atoms.
+x is to the right, +y is DOWN, and positive rotation is CLOCKWISE.
assert.js:25 Uncaught Error: Assertion failed: value failed isValidValue: Qualitative vector representation of the dipole, based on the electronegativity difference between the atoms.
+x is to the right, +y is DOWN, and positive rotation is CLOCKWISE.
    at window.assertions.assertFunction (assert.js:25)
    at Object.isValueValid (ValidatorDef.js:307)
    at validate (validate.js:25)
    at DerivedProperty.initializePhetioObject (PhetioObject.js:168)
    at new PhetioObject (PhetioObject.js:106)
    at new Property (Property.js:76)
    at new DerivedProperty (DerivedProperty.js:55)
    at new Bond (Bond.js:42)
    at new DiatomicMolecule (DiatomicMolecule.js:44)
    at createMolecule (TwoAtomsModel.js:22)
```

Instead of just telling me "you can't have a newline in phetioDocumentation", I have to spend 5 minutes tracing this to this line in PhetioObject:

```js
const PHET_IO_DOCUMENTATION_VALIDATOR = { valueType: 'string', isValidValue: doc => doc.indexOf( '\n' ) === -1 };
``

**Comment by zepumph** [comment]
I committed a fix just for phetioDocumentation as part of a proposal over in https://github.com/phetsims/axon/issues/346. If that goes well, we can add messages to the rest of the validations in this file.

**Comment by zepumph** [comment]
@pixelzoom, I want to note that I just found the comment above the phetioDocumentation validator:


https://github.com/phetsims/tandem/blob/b8fa64d34f560181a3ab15faf17fa765512c6053/js/PhetioObject.js#L32-L33

so you can use `<br>` to get new lines.

**Comment by samreid** [comment]
@zepumph what remains to be done for this issue?

**Comment by zepumph** [comment]
Adding messages to all validators. Please review.

**Comment by samreid** [comment]
I skimmed the messages and they sound reasonable, and I tested with newlines in molecule polarity phetioDocumentation and saw this error:

```
Assertion failed: phetioDocumentation must be provided in the right format: value failed isValidValue: Qualitative vector representation of the dipole, based on the electronegativity difference 

between the atoms. +x is to the right, +y is DOWN, and positive rotation is CLOCKWISE.
```

This seems reasonable to me, @pixelzoom would you like anything else for this issue?

**Comment by pixelzoom** [comment]
Messages look reasonable to me too. Closing.
