### ISSUE TITLE
PhetioIDUtils to be loaded by node code

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#231]
Over in https://github.com/phetsims/phet-io/issues/1750, we wanted to use PhetioIDUtils in phetioCompareAPIs, but that function is exported flexibly to be used by Node or the browser. We should adopt a similar pattern for PhetioIDUtils for use in chipper.

**Comment by samreid** [comment]
I'm not seeing that `phetioCompareAPIs` needs PhetioIDUtils at the moment.  I'm OK with the constant `'.'` or concatenation rules being copied there.  It feels like a better long term solution would be to gravitate toward modules everywhere.

**Comment by zepumph** [comment]
Sounds good.
