### ISSUE TITLE
Detect memory leaks caused by failure to de-register tandems.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#243]
Forgetting to dispose of subcomponents that have registered tandems is a common mistake (see https://github.com/phetsims/sun/issues/710). It creates a memory leak. And there's currently no support for catching this type of problem.

Should an assertion be added that prevents a parent tandem from being deregistered when it has child tandems registered?   For example, suppose that we have the following for a NumberSpinner instance:

`mySpinner`
`mySpinner.numberDisplay`
`mySpinner.incrementButton`
`mySpinner.decrementButton`

If I deregister `mySpinner` while the others are registered, that's probably due to a buggy `dispose` implementation.   If that caused an assertion to fail, then we would easily detect problems like https://github.com/phetsims/sun/issues/710.

**Comment by zepumph** [comment]
This is relatively similar in topic to recent discussion in https://github.com/phetsims/circuit-construction-kit-common/issues/704#issuecomment-873235709. We tried to add that assertion when creating the disposal/removal code, but ran into trouble because not all Tandems are tied to a PhetioObject. Thus if you have a child, you have no way of knowing if it should have been disposed, or if it is an intermediary Tandem created for structure. The only way to know this would be to add a reference on tandem to a nullable PhetioObject, so that the tandem can see if the child it has is expected to still exist. 


1. I don't think that manually disposing intermediate nodes (like in DragListener) is the right path, but I could potentially be convinced.
2. I really don't want to add an option pointer to a PhetioObject on Tandem.

**Comment by samreid** [comment]
I tested this patch by running http://localhost/main/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?brand=phet-io&phetioStandalone (note assertions and debugger are disabled)

<details>

```diff

Index: main/circuit-construction-kit-common/js/view/SwitchNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/circuit-construction-kit-common/js/view/SwitchNode.js b/main/circuit-construction-kit-common/js/view/SwitchNode.js
--- a/main/circuit-construction-kit-common/js/view/SwitchNode.js	(revision 2243bc44461f04c2ce4085fba0cab137444c44ca)
+++ b/main/circuit-construction-kit-common/js/view/SwitchNode.js	(date 1625850608489)
@@ -160,6 +160,8 @@
     };
     circuitSwitch.closedProperty.link( closeListener );
 
+    assert && assert( tandem.supplied );
+
     super(
       screenView,
       circuitLayerNode,
@@ -266,8 +268,8 @@
    * @override
    */
   dispose() {
-    this.disposeSwitchNode();
     super.dispose();
+    this.disposeSwitchNode();
   }
 }
 
Index: main/tandem/js/PhetioObject.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/tandem/js/PhetioObject.js b/main/tandem/js/PhetioObject.js
--- a/main/tandem/js/PhetioObject.js	(revision 3a12eeafe70f489965638957aad85ee202cacf0f)
+++ b/main/tandem/js/PhetioObject.js	(date 1625850571272)
@@ -584,6 +584,19 @@
    * @public
    */
   dispose() {
+
+    const descendants = [];
+    if ( phet && phet.phetio && phet.phetio.phetioEngine && this.tandem.supplied ) {
+      console.log( 'disposing ' + this.tandem.phetioID );
+      const phetioEngine = phet.phetio.phetioEngine;
+      this.tandem.iterateDescendants( tandem => {
+        if ( phetioEngine.hasPhetioObject( tandem.phetioID ) ) {
+          console.log( tandem.phetioID );
+          descendants.push( phetioEngine.getPhetioObject( tandem.phetioID ) );
+        }
+      } );
+    }
+
     assert && assert( !this.isDisposed, 'PhetioObject can only be disposed once' );
 
     // In order to support the structured data stream, PhetioObjects must end the messages in the correct
@@ -592,11 +605,16 @@
     // disposed PhetioObjects.
     //
     // The phetioEvent stack should resolve by the next frame, so that's when we check it.
-    assert && animationFrameTimer.runOnNextTick( () => {
+    animationFrameTimer.runOnNextTick( () => {
 
       // Uninstrumented PhetioObjects don't have a phetioMessageStack attribute.
       assert && assert( !this.hasOwnProperty( 'phetioMessageStack' ) || this.phetioMessageStack.length === 0,
         'phetioMessageStack should be clear' );
+
+      descendants.forEach( descendant => {
+        // assert && assert( descendant.isDisposed, `descendants should be disposed by the next frame. ${descendant.tandem.phetioID}` );
+        console.log( descendant.isDisposed, `descendants should be disposed by the next frame. ${descendant.tandem.phetioID}` );
+      } );
     } );
 
     if ( this.phetioObjectInitialized ) {
Index: main/circuit-construction-kit-common/js/view/CircuitLayerNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/circuit-construction-kit-common/js/view/CircuitLayerNode.js b/main/circuit-construction-kit-common/js/view/CircuitLayerNode.js
--- a/main/circuit-construction-kit-common/js/view/CircuitLayerNode.js	(revision 2243bc44461f04c2ce4085fba0cab137444c44ca)
+++ b/main/circuit-construction-kit-common/js/view/CircuitLayerNode.js	(date 1625850287553)
@@ -258,7 +258,7 @@
     const initializeCircuitElementType = ( predicate, layer, createCircuitElement ) => {
       const addCircuitElement = circuitElement => {
         if ( predicate( circuitElement ) ) {
-          const circuitElementNode = createCircuitElement( circuitElement, Tandem.OPTIONAL );
+          const circuitElementNode = createCircuitElement( circuitElement, tandem.createTandem( 'mySwitchNode' ) );
           this.circuitElementNodeMap[ circuitElement.id ] = circuitElementNode;
 
           layer.addChild( circuitElementNode );
Index: main/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js b/main/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js
--- a/main/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js	(revision 2243bc44461f04c2ce4085fba0cab137444c44ca)
+++ b/main/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js	(date 1625850042391)
@@ -409,7 +409,7 @@
         new Switch(
           new Vertex( Vector2.ZERO ),
           new Vertex( new Vector2( SWITCH_LENGTH, 0 ) ),
-          Tandem.OPTIONAL
+          tandem.createTandem( 'switch' )
         ), viewTypeProperty, tandem.createTandem( 'switchIcon' ), {
           isIcon: true
         } ),

```

</details>

It correctly detected bug in https://github.com/phetsims/circuit-construction-kit-common/issues/704#issuecomment-873235709 where the FireListener wasn't being disposed.  That test and patch is contrived (since we had to avoid API validation because CCK wasn't set up with PhetioGroup yet), but I wanted to provide a complete example.  But I did test in both orders of disposal in SwitchNode:

```js
  dispose() {
    super.dispose();
    this.disposeSwitchNode();
  }
```

and 
```js
  dispose() {
    this.disposeSwitchNode();
    super.dispose();
  }
```
And it had the expected behavior in both cases.  Here is a better proposal for discussion:

<details>

```diff

Index: js/PhetioObject.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/PhetioObject.js b/js/PhetioObject.js
--- a/js/PhetioObject.js	(revision 3a12eeafe70f489965638957aad85ee202cacf0f)
+++ b/js/PhetioObject.js	(date 1625850868556)
@@ -584,6 +584,17 @@
    * @public
    */
   dispose() {
+
+    const descendants = [];
+    if ( phet && phet.phetio && phet.phetio.phetioEngine && this.tandem.supplied ) {
+      const phetioEngine = phet.phetio.phetioEngine;
+      this.tandem.iterateDescendants( tandem => {
+        if ( phetioEngine.hasPhetioObject( tandem.phetioID ) ) {
+          descendants.push( phetioEngine.getPhetioObject( tandem.phetioID ) );
+        }
+      } );
+    }
+
     assert && assert( !this.isDisposed, 'PhetioObject can only be disposed once' );
 
     // In order to support the structured data stream, PhetioObjects must end the messages in the correct
@@ -597,6 +608,10 @@
       // Uninstrumented PhetioObjects don't have a phetioMessageStack attribute.
       assert && assert( !this.hasOwnProperty( 'phetioMessageStack' ) || this.phetioMessageStack.length === 0,
         'phetioMessageStack should be clear' );
+
+      assert && descendants.forEach( descendant => {
+        assert && assert( descendant.isDisposed, `descendants should be disposed by the next frame. ${descendant.tandem.phetioID}` );
+      } );
     } );
 
     if ( this.phetioObjectInitialized ) {

```

</details>

**Comment by pixelzoom** [comment]
To circle back to the first comment in this issue...  PhET-iO makes is easy to create memory leaks by forgetting to unregister tandems.  There is currently no support for detecting such a leak. Such leaks definitely exist in current common code.  So I'm proposing that PhET-iO prevent the programmer from creating such leaks.  And I don't particularly care how that's implemented. That said... 

I don't fully understand the previous comment. Is it an example, or does it address the "trouble" described by @zepumph in https://github.com/phetsims/tandem/issues/243#issuecomment-876468048?

> One other aspect of this problem. PhetioObjects are only disposed when in a PhetioDynamicElementContainer. Maybe that is where the disposal belongs?

Will that detect the case where someone incorrectly disposes of something outside of a PhetioDynamicElementContainer?

**Comment by samreid** [comment]
To elaborate on the proposal, it is an implementation of this idea: When a PhetioObject is disposed, in the next frame, assert that its instrumented descendants are also disposed.  It is done in the next frame (asyncronously) so there is no constraint on the order of whether children or parents must be disposed first.

> Will that detect the case where someone incorrectly disposes of something outside of a PhetioDynamicElementContainer?

That is already handled well by phetioAPIValidation.

**Comment by zepumph** [comment]
The second patch, with some minor adjustments, was looking really nice. A great idea to kick it off to the next tick! I committed after fuzz testing every phet-io sim in local aqua fuzzing.

@pixelzoom can you please review with your context. Also note that we have no registry in phet brand, so this is only for PhET-iO brand (not sure if this was the scope you were hoping for).

**Comment by pixelzoom** [comment]
This is a nice improvement. Let's see how it works out in pratice, and if it catches potential memory leaks. 

Closing.
