### ISSUE TITLE
fromCoreType should use CoreType.STATE_SCHEMA and not the stateSchema option

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#245]
While working on https://github.com/phetsims/phet-io/issues/1782, I see 9 usages. Let's just put the schema on the type instead, and assert that we don't supply with options (like we do for all other state methods). Tagging @samreid so he is aware of it.

**Comment by zepumph** [comment]
This made fromCoreType a bit simpler, and I think it will help us out over in https://github.com/phetsims/phet-io/issues/1782. @samreid, please spot check things and feel free to close.

**Comment by zepumph** [comment]
There is a large bug that was discovered while supporting @jbphet over in https://github.com/phetsims/greenhouse-effect/issues/85, For composite schemas, we need to know if the children should be deserialized with fromStateObject or with applyState. I think the best path forward to to begin to embed the "defaultDeserializationType" into the IOType. This has long been on my wishlist, over in https://github.com/phetsims/phet-io/issues/1583. Then by default the IOType will decide if it by default uses fromStateObject or applyState to do its bidding. Then stateSchema can use that.

**Comment by zepumph** [comment]
The above commits fix this, be adding IOType.defaultDeserializationMethod. This is how a stateSchema can know how to deserialize its component. The commit feels pretty safe, but I'm unsure this is the best direction. What about something more general like over in https://github.com/phetsims/phet-io/issues/1583. I feel like we added complexity, instead of adding an organizational property that could help in communicating how PhET-iO serialization works.

@samreid please review the immediate changes, and then perhaps we can also discuss if this is the best direction. Maybe we will need to set up a meeting. Let me know how it goes!

**Comment by zepumph** [comment]
Hey, @samreid, I'm very sorry that I have made things confusing here. This was totally the wrong issue for work https://github.com/phetsims/tandem/issues/245#issuecomment-921065520 and below. It should have instead been but on https://github.com/phetsims/phet-io/issues/1782 instead.

**Comment by samreid** [comment]
@zepumph and I reviewed https://github.com/phetsims/phet-io/issues/1782 and this.  We didn't reorganize everything for https://github.com/phetsims/phet-io/issues/1583 but this is a nice addition for what's already in place.  Thanks!  Closing.
