### ISSUE TITLE
Serialization of NaN and infinities

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#246]
From https://github.com/phetsims/density/issues/87#issuecomment-916541483:

> The contact force on the scale seems to immediately go to NaN (not-a-number), and it looks like that's getting nulled out by the JSON stringify (infinities and NaNs don't transfer well to JSON, since they're not supported).
> 
> ![image](https://user-images.githubusercontent.com/480878/132780349-38b6b8fc-e084-48ae-b34c-07fb49ed8b2e.png)
> 
> So first of all, I would expect NumberIO and Vector2IO (etc.) to handle serializing infinities and NaNs. @zepumph should we create a general issue?
> 
> But also, I shouldn't be getting NaNs anyway, I'll fix that.

I think we should assert that we aren't serializing NaN, since `typeof NaN === 'number'` so that we aren't catching this in the validator.

I also thought we were successfully serializing infinity, so we should check on that. Tagging @samreid.

**Comment by zepumph** [comment]
Alright, I supported NumberIO in Vector serialization, and also throw an error for NaN now. I wrote tests to outline NumberIO's serialization strategy. @samreid please review.

**Comment by samreid** [comment]
Everything looks great!  A few questions, some for my own education:

1. Vector2 supports NaN but Vector2IO doesn't.  Should that be rectified, either by removing NaN from Vector2 support or by adding NaN support to NumberIO?  Could be a separate issue for "later"
2. Vector2 has this code.  Could the toStateObject be powered by the state schema?
```js
  toStateObject() {
    return {
      x: NumberIO.toStateObject( this.x ),
      y: NumberIO.toStateObject( this.y )
    };
  }
  static get STATE_SCHEMA() {
    return {
      x: NumberIO,
      y: NumberIO
    };
  }
```
3. I rewrote the NumberIO with ternaries, can you double check it?

**Comment by samreid** [comment]
On second thought, back to @zepumph to see if there's anything else.
