### ISSUE TITLE
Can PhetioDynamicElementContainer.disposeElement be marked as public?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#248]
From https://github.com/phetsims/circuit-construction-kit-common/issues/749, even though the overrides of disposeElement are marked as public, TypeScript used the parent annotation.  But I was confused about why it is protected in the base class?  Should it not be called typically?  I'll mark it as public to make progress in https://github.com/phetsims/circuit-construction-kit-common/issues/749, but would be good to discuss.  Self assigning to take a closer look, but I'll consult with @zepumph soon.

**Comment by zepumph** [comment]
This file is now in typescript, and disposeElement is marked as `protected`. yay. Closing
