### ISSUE TITLE
Convert PhetioObject to TypeScript

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#249]
In Slack:

@jonathanolson said:
> merge is .js, and the new options pattern seems unused in Property.ts. Presumably I'd want to have a good options pattern that's decent if I'm going to handle PhetioObject/Node/etc. (getting the options pattern right from the start seems beneficial)

I said:

> I haven’t done the options pattern there yet.  Should we start on that next?
> I’ll investigate converting PhetioObject to ts
> It’s going to be tricky.

@jonathanolson said:

> It makes sense to do PhetioObject before Node
> I can always typescript some of the internal kite/scenery things

**Comment by zepumph** [comment]
I would like to review this! Will you post any weirdness that you might specifically want my attention on?

**Comment by samreid** [comment]
Maybe look at the ts-ignores and the options patterns?

**Comment by samreid** [comment]
This file no longer has ts-expect-error or ts-ignore. It has been working reliably for a long time and I don't think we need an issue for an "eager" review. We can address needs as they arise.  Closing.
