### ISSUE TITLE
State schema related types hyperlinks don't work in Studio when showing "Selected" types

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#250]
Discovered in Gravity and Orbits in https://github.com/phetsims/gravity-and-orbits/issues/414, and probably related to the work in https://github.com/phetsims/phet-io/issues/1781, it seems State schema related types hyperlinks don't work in Studio when showing "Selected" types.  I was able to reproduce this problem on master.  This problem did not affect the last gravity and orbits publication because I don't see a state schema section in its documentation.  I thought this code would be related: https://github.com/phetsims/tandem/blob/5679c8e50ee39475a38ddbadc47fcf8eac511570/js/types/StateSchema.js#L191-L213

@zepumph can you please take a look?

**Comment by zepumph** [comment]
Fixed above. How does that look?

**Comment by samreid** [comment]
That looks great, thanks!  Closing.
