### ISSUE TITLE
Typescript error in PhetioObject

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#251]
`tsc` in tandem comes out clear, and there are no issues with transpile, but when I navigate to PhetioObject, Webstorm says it can't understand `_` as a variable. @samreid are you experiencing this? I was surprised because I see that lodash is included in the tsconfig.

**Comment by samreid** [comment]
Mine does not show in red, but mousing over it gives this error (warning?)

![image](https://user-images.githubusercontent.com/679486/144629193-f5ebf83a-e2ee-4dc7-86bf-f1d7b2783d5d.png)

**Comment by zepumph** [comment]
Hmm,

![image](https://user-images.githubusercontent.com/6856943/144633340-ec4861c5-4827-491a-b8ac-14e32e550766.png)

**Comment by samreid** [comment]
I can take a look on zoom and we could try some things, but I'm not sure it can be fixed if WebStorm is acting wacky.

**Comment by zepumph** [comment]
I restarted webstorm with PhetioObject open, and it seems to have fixed itself. Perhaps a dependency caching problem or something on their end.
