### ISSUE TITLE
Should low frequency events nested in high frequency emit with `?phetioEmitHighFrequencyEvents=false`

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#255]
Pondered over in https://github.com/phetsims/geometric-optics/issues/348, where it seemed weird that a high frequency event could be filtered out and its low-frequency children would be promoted to top-level events.

Poking through dataStream.js, I found some comments that hint to this being a purposeful design decision, but I'm not sure at this time.

https://github.com/phetsims/phet-io/blob/ce6fa02a11fbd2e19def0bfbf23d2e5212a3a342/js/dataStream.js#L36-L41

@samreid, do you have any recollection about how we designed high frequency events?

**Comment by samreid** [comment]
That comment makes sense to me, that the data stream is saying "I don't want to know about HFEs, but I do want to know about LFEs".  So if there is a LFE that was a child of a HFE, then the data stream would just show the LFE.

**Comment by zepumph** [comment]
Makes sense! I bet that was from LFE that were triggered from stepSimulation or something like that. I feel good to close. Thanks for jogging my memory.
