### ISSUE TITLE
Forbid tandem name "pickableProperty"

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#258]
In https://github.com/phetsims/center-and-variability/issues/105 @kathy-phet proposed:

> maybe there should be an assertion if pickableProperty is in a phet-io name or something?

@chrisklus and I confirmed there are no existing usages.  It's OK with me if we add an assertion guard.

**Comment by zepumph** [comment]
Makes sense to me, but seems like we should have a general solution. Brainstorming time!!!

* A list in tandem that is a blacklist checked by `createTandem`
* A way to register a blacklisted tandem. For example, in Node.ts (where pickableProperty matters) statically have this line of code:
```js
Tandem.registerBlacklistedTandem( ENABLED_PROPERTY_TANDEM_NAME )
```

What do you think @samreid?

**Comment by samreid** [comment]
I recommend consolidating the list in Tandem.

**Comment by zepumph** [comment]
Sounds excellent. I feel like this is best. Anything else here?

**Comment by samreid** [comment]
For review, can we please use a different term, for the reasons mentioned in https://thenewstack.io/words-matter-finally-tech-looks-at-removing-exclusionary-language/ ?

**Comment by zepumph** [comment]
Sounds good. See https://github.com/phetsims/special-ops/issues/221
