### ISSUE TITLE
Convert Tandem to TypeScript

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#266]
Convert Tandem to TypeScript.  This came up several times when investigating the type-checking lint rules, so would be good to do soon.

**Comment by samreid** [comment]
I ported Tandem to TypeScript, it was pretty straightforward.  For review, there is one question in a TODO.  @zepumph can you please review this change at your convenience?

**Comment by zepumph** [comment]
Looks great. Thanks for converting! I'm excited for the change. Closing
