### ISSUE TITLE
Remove out dated and useless IOType methods

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#269]
While working on https://github.com/phetsims/tandem/issues/268, I came up with the following list of methods that we should likely just remove from the PhET-iO API:

**TextIO**:
* setFontOptions
* getFontOptions
* setMaxWidth
* getMaxWidth

**SliderIO**
* setMajorTicksVisible
* setMinorTicksVisible

@samreid what do you think?

**Comment by samreid** [comment]
Yes, let's remove them until we have a need for them.  The ticks visible maybe should move to a PropertyIO(BooleanIO) when needed.  Maybe same with the font options.

**Comment by zepumph** [comment]
Excellent! Thanks
