### ISSUE TITLE
Tandem: bad names for instance listener API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#27]
Tandem uses the listener pattern for notifying when an instance is added and removed.  The documentation for `addInstance` includes the specification for an instance listener:

```js
    /**
     * Adds a listener that will be notified when items are registered/deregistered
     * Listeners have the form
     * {
     *   addInstance(id,instance),
     *   removeInstance(id,instance)
     * }
     * where id is of type {string} and instance is of type {Object}
     *
     * @param {Object} instanceListener - described above
     * @public
     * @static
     */
    addInstanceListener: function( instanceListener ) {
      instanceListeners.push( instanceListener );
    },
```

In this case, the function names don't conform to the typical listener pattern.  The current names, `addInstance` and `removeInstance`, make it sound like they are doing the adding and removing.  The names should be something like `instanceAdded` and `instanceRemoved` respectively.  Highly recommended to rename these.

**Comment by samreid** [comment]
We removed this interface in https://github.com/phetsims/phet-io/issues/1422, closing.
