### ISSUE TITLE
Copy/paste duplication and inconsistency between all of the regexes for `isValidTandemName`

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#270]
More generally, there is copy/paste duplication and inconsistency between all of the regexes for `isValidTandemName`.  Should we create our own data structure to make it possible to "tack on" more allowed characters for certain cases?

Also note: DynamicTandem doesn't allow commas.  That is a problem too.

**Comment by zepumph** [comment]
Ok, trying to get a handle on this issue:

1. There is duplicated regex chars/definitions in Tandem and DynamicTandem
2. It isn't clear if DynamicTandem wants less chars supported (`][,-`) or if it is just out of sync
3. It is kind hard to know how to factor this out. Something like `const regexBaseCharsAllowed = 'A-z0-9.  . . '`; And then we use `new RegExp()` to fill it in, or add the `_` in dynamic tandem.

Adding to the PhET-iO backlog over in https://github.com/phetsims/phet-io/issues/1914

**Comment by samreid** [comment]
Looking great, thanks!  @zepumph also volunteered to put some RegExp constants nearby `Tandem.BASE_TANDEM_TERM`.

**Comment by zepumph** [comment]
Thanks for helping me get this. I like where we got it.
