### ISSUE TITLE
Tandem description is inaccurate

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#28]
```js
/**
 * Tandem is a general instance registry that can be used to track creation/disposal of instances in PhET Simulations.
 * It is used for phetio.js instrumentation for PhET-iO support.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
```

This is inaccurate.  There is no registry implemented here.  This is just a thin wrapper that forwards registration requests to "instance listeners".   The registry appears to live in pheti-io.phetio.js.

**Comment by samreid** [comment]
This was corrected in https://github.com/phetsims/tandem/issues/26 and subsequent commits, closing.
