### ISSUE TITLE
Primitive IOTypes should have much less boilerplate

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#280]
Over in #277 @samreid and I realized that we should just simplify types and state objects for number, string, and boolean, instead of continuing to build up scaffolding for them. More to explain later!

**Comment by zepumph** [comment]
@samreid and I made a bunch of progress here. We realized how much less work it is to have BooleanIO StringIO and NumberIO serialize as their primitives. The only reason we hadn't done that yet is because NumberIO was serializing infinity for us. What a headache infinity was causing. So we just made it its own IOType. Only needed by RangeIO and Bounds2IO. So much nicer! This will be some API changes though, I wonder if we need some migration rules for it! Commit coming soon.

**Comment by zepumph** [comment]
@samreid can you please review this and https://github.com/phetsims/tandem/issues/277#issuecomment-1289804145 and let me know if you think there is anything more to do?

**Comment by zepumph** [comment]
- [ ] From https://github.com/phetsims/tandem/issues/277#issuecomment-1291189012, we need to update the documentation for InfiniteNumberIO

**Comment by zepumph** [comment]
@samreid sorry I didn't assign you.

**Comment by zepumph** [comment]
>@samreid sorry I didn't assign you.

And still! :sigh:

**Comment by samreid** [comment]
I updated the docs, skimmed commits and reviewed comments.  Everything seems great! Closing.
