### ISSUE TITLE
Export and import IOTypes so usages look like PropertyIO instead of Property.PropertyIO

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#285]
When we designed the IO Type system, we did not utilize the fact that a file could have multiple exports.  But it seems like a lot of usage sites would be easier to read and write if IO types could be written like `Vector2IO` or `PropertyIO` instead of `Vector2.Vector2IO` and `Property.PropertyIO`.

Tagging @pixelzoom and @zepumph so they aware this is coming up.

**Comment by pixelzoom** [comment]
Usages like `Vector2.Vector2IO` don't bother me.  And in fact I think it's preferrable (and necessary) if you want to save/restore private parts of the core type.  So if you're planning to change that, let's chat first.

**Comment by pixelzoom** [comment]
Oh... Maybe you're saying that Vector2.ts should simply add an export for `Vector2.Vector2IO`?

**Comment by samreid** [comment]
Yes, adding an export. I'll add a commit momentarily demonstrating it for `Property.PropertyIO`.

**Comment by samreid** [comment]
The commits show the proposal for exporting PropertyIO.  @pixelzoom does that look good to you?

**Comment by pixelzoom** [comment]
I'm not sure that PropertyIO was a good choice as an example.  Or maybe it was to demonstrate problems with your proposal.

(1) PropertyIO is not defined in Property.ts, and is in fact associated with core type ReadOnlyProperty.  So it violates the PhET naming conventions, and was therefore confusing.  If convetions had been used, I should have been looking at replacements of `Property.PropertyIO` with `PropertyIO`.

(2) Most IO Types I've seen are declared like `public static readonly SomethingIO =`.  PropertyIO is declared as `public static PropertyIO<T, StateType>( parameterType: IOType<T, StateType> ): IOType`.   Maybe that's the responsible for the odd export that's needed.

(3) The additional export requires an eslint-disable. Is that going to be needed for all such exports?
```
export const PropertyIO = ReadOnlyProperty.PropertyIO; // eslint-disable-line bad-text
```

That said...

Is this the general convention that you're proposing?

```typescript
export default class MyType {
   public static readonly MyTypeIO = ...;
}

export const MyTypeIO = MyType.MyTypeIO;
```

... with the developer able to use either `MyTypeIO` or `MyType.MyTypeIO`.

If so... 
* I see very little value or point in this, especially if IOTypes are a `public static readonly` property of their core type.
* It allows developers to violate conventions, as has been done with PropertyIO.
* The time that I spend remember the form of the  additional`export` will negate any benefit. 
* I can think of 10 PhET-iO problems that are 100x more important than this.

So my vote for this is "no".

**Comment by samreid** [comment]
I agree, having IO types be declared as a `public static readonly` property of the core type seems like the most important part, and it is not necessary to provide a shorthand for usage sites.  Most commits will auto-revert, but I'll need to manually revert axon and energy-forms-and-changes.  Coming up soon...

**Comment by samreid** [comment]
Thanks, I reverted the changes for this issue and elaborated on a new side issue https://github.com/phetsims/axon/issues/429.  @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
👍🏻 closing.
