### ISSUE TITLE
should addInstance and removeInstance handle noop for optional but not supplied tandems?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#29]
I find myself often needing to cover my bases with the following commands:

`options.tandem.isLegalAndUsable() && options.tandem.addInstance( this, TTooMuchFunTypingBoilderPlate )`.

Is there a way around this? Marking for phet-io meeting.

**Comment by samreid** [comment]
I have had the same problem, including places where other qualifiers were needed (perhaps for phetioEvents), it would be good to discuss.

**Comment by samreid** [comment]
Perhaps there are cases where tandem.addInstance should sometimes be no-op if tandem is not legal and usable and some cases where it should be an error if tandem is not legal and usable?

**Comment by zepumph** [comment]
This issue has been handled by PhetioObject, closing
