### ISSUE TITLE
StateSchema's default toStateObject and applyState should support IOType supertypes

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#295]
These methods support a solid implementation, but they don't cascade up to parent supertypes. It would be ideal that this could occur, so that a StateSchema only needs to provide its own keys, and not manually add in its parents.

**Comment by zepumph** [comment]
- [ ] @jbphet and I ran into one other problem with the applyState function where we want to use the defaultApplyState function, but don't want to overwrite the array reference for emEnergyPackets: 

https://github.com/phetsims/greenhouse-effect/blob/55b7a4e401dc1765d905676a2a0eafe090a95e57/js/common/model/LayersModel.ts#L349-L352

**Comment by zepumph** [comment]
https://github.com/phetsims/tandem/issues/295#issuecomment-1568873424 was fixed with a new ReferenceArrayIO. Yay!

**Comment by zepumph** [comment]
Alright. I worked with @samreid on this, and state seems to be working well! @samreid do you think there is anything else here? Sorry for the broad review, but I don't know quite how to write up some of the larger portions of state schema and IOType work that we may want to work on to make things better and easier. Perhaps the key is trying to move towards a StateSchema-centric usage.

**Comment by samreid** [comment]
@zepumph and I finished this up, nice work! Closing.
