### ISSUE TITLE
tandem dependency is missing from package.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#3]
`TANDEM` was added to beers-law-lab-config.js, but `tandem` doesn't appear in package.json.  

This causes 2 problems:

(1) dependencies.json is incomplete, it is missing `tandem` shas. So for interoperable sims published to date, we have no way to reproduce their source code snapshot.

(2) "Quick Start" instructions in README.md are incomplete. This is causing problems for non-PhET developers, as reported in https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/NnEOWam9sYQ

This is a problem for all sims that have been instrumented with tandem. i.e.:

beaker
beers-law-lab
color-vision
concentration
energy-skate-park-basics
faradays-law
molecules-and-light

**Comment by pixelzoom** [comment]
Since all sims will eventually be instrumented with tandem, there are 2 ways to proceed with fixing this:

(1) Add tandem to common.preload in chipper/build.json, so that it's a preload for all sims. This is a 1-line fix that resolves the issue for the above sims and future sims.  But adds a dependency that's not required for sims that haven't been instrumented.

(2) Add tandem to preload in package.json for sims as they are instrumented. Requires fixing all of the repos mentioned above, and remembering to do this correctly in the future as sims are instrumented.

**Comment by pixelzoom** [comment]
For now, I did option (2) above - that is, fixed the sims that currently have a dependency on tandem. I added tandem to phetLibs in their package.json, and (for published sims) regenerated their README.md file. 

@samreid please review, and let's discuss whether to add tandem to common.phetLibs in chipper/build.json.

**Comment by pixelzoom** [comment]
Great. Now all of the above sims are failing lint, because tandem doesn't pass lint.  Eg:

```
% cd concentration
% grunt 
Running "jshint:allFiles" (jshint) task
Linting ../tandem/js/Tandem.js ...ERROR
[L33:C3] W021: 'Tandem' is a function.
  Tandem = inherit( Object, Tandem, {

Warning: Task "jshint:allFiles" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by pixelzoom** [comment]
Lint fix pushed, but not tested, since I'm not clear on how to test tandem.

**Comment by samreid** [comment]
Lint fix for tandem tests nicely, I tested by running http://localhost:8080/together/html/concentration-together.html?togetherEvents.log=console and looking at the console log.

**Comment by pixelzoom** [comment]
Thoughts on whether to add tandem to common.phetLibs in chipper/build.json?

**Comment by samreid** [comment]
I suspect it should be in the common libs.  It will be instantiated in each sim's main and just passed through constructors, so each sim will need it (unless we come up with some other strategy for dealing with this problem).

**Comment by samreid** [comment]
@pixelzoom now that you are more familiar with how tandem is intended to be used in simulations, can you help me answer the question of how to proceed here?  Or should we still discuss it an upcoming meeting?

**Comment by pixelzoom** [comment]
I'm OK with putting tandem in chipper/build.json, and it sounds like you agree (https://github.com/phetsims/tandem/issues/3#issuecomment-141723906).  What remains is to see if anyone else objects to having a phetLib dependency for all sims that won't actually apply to all sims for quite some time.

**Comment by pixelzoom** [comment]
I'm OK with putting tandem in chipper/build.json, and it sounds like you agree (https://github.com/phetsims/tandem/issues/3#issuecomment-141723906).  What remains is to see if anyone else objects to having a phetLib dependency for all sims that won't actually apply to all sims for quite some time.  If other developers want to chime in here, that could eliminate the need for discussion at developer meeting. @jbphet @jonathanolson @aaronsamuel137 @jessegreenberg?

**Comment by samreid** [comment]
Unassigning until after this has been discussed.  The `phet-io-meeting` label will help us make sure this issue stays on our radar.

**Comment by samreid** [comment]
Design meeting consensus: add tandem to chipper/build.json

**Comment by samreid** [comment]
And get rid of the tandem references in the sims package.jsons.

**Comment by samreid** [comment]
I've added tandem to chipper/build.json and removed tandem references from 7 repos.  Tested building and launching built beaker, everything seemed ok.  Will commit shortly.

**Comment by samreid** [comment]
@pixelzoom commented that this solution:

> Technically requires regenerating README.md for all published sims.

**Comment by samreid** [comment]
I'm not too familiar with the readme generation tasks.  Is the strategy here to iterate over all of the simulations and check whether the version is < or > than 1.0.0, and choose whether to use the unpublished-README or published-README task?  Is there already a script that will do that?  Pinging @pixelzoom and @jonathanolson since they look like the primary contributors to generateREADME.js.

**Comment by pixelzoom** [comment]
There is unfortunately no list of published sims. So the procedure to regenerate README.md for published sims is:

1. Edit active-runnables so that it contains only published sims
2. Run `grunt-all.sh published-README`
3. Commit all modified README.md files

**Comment by samreid** [comment]
After looking around it seems we do not need to generate the unpublished sim readme's because they don't list their git clone dependencies.

**Comment by pixelzoom** [comment]
Correct - unpublished sims have no "Quick Start" section in their README.md, which is where the dependencies appear in the form of `git clone` commands.  That's why I said "Technically requires regenerating README.md for all *published* sims" (emphasis added).

**Comment by samreid** [comment]
I updated the README's above, anything else to do here?

**Comment by pixelzoom** [comment]
I think that covers it.  Closing.
