### ISSUE TITLE
Centralize logic for add/removeInstance, AKA implement model tandems like scenery node tandems

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#31]
On Thursday we discussed centralizing the logic for add/removeInstance, perhaps like it is done for scenery Node subclasses.  Here are my raw notes:

pass in the phetioType in options or on prototype.....

then tandem.addinstance

maybe need a PhETObject core type that everything extends.

Only one tandem per object.

OK to put things on the prototype but not on the instance.

If we go with this.subtypeTandem, then we have to iterate through and get rid of this.tandem because they will get stomped on.

**Comment by samreid** [comment]
@zepumph was there some problem that contraindicated the proposed strategy?  My memory is a bit fuzzy from the last part of that conversation.

**Comment by samreid** [comment]
More notes from https://github.com/phetsims/phet-io/issues/1248

To make the proposed strategy work, we would need the following ingredients:

1. A base type like PhETObject that all models can inherit from
2. PhETObject would accept options including a `phetioType` parameter which defaults to null
3. All PhETObject subclasses (and their subclasses) would need to call mutate/setTandem 

If I understand correctly, this is the strategy used by Node.  However this proposal and the Node implementation share a synchronization problem.  If there is synchronous code scheduled to run upon creation of an object, it will be called before the subclass constructors complete, and therefore act on an instance with incomplete/inconsistent data.  I do not know why this problem hasn't bitten us with scenery Nodes before (perhaps we aren't using synchronous settings enough to encounter an error case yet).

It seems we would either need to (a) eliminate synchronous changes to nodes (in which case this problem goes away) or (b) to make sure tandem.addInstance isn't called until the subtypiest constructor completes (this is the strategy employed with `createSupertypeTandem`)

@zepumph I'd love to hear your thoughts on the matter.

**Comment by zepumph** [comment]
>It seems we would either need to (a) eliminate synchronous changes to nodes (in which case this problem goes away) or (b) to make sure tandem.addInstance isn't called until the subtypiest constructor completes (this is the strategy employed with createSupertypeTandem)

I think the reason that this hasn't bitten us before is because in general when implementing, I'm keeping tandem out of the hierarchy until the last line of a constructor. An example of this is `ExpandCollapseBar.js`. It doesn't call mutate with the tandem until the very last line of the subtypiest type. I can't find another example right now (perhaps ExapndCollapseBar` isn't the best) but sometimes we have a type like so that we want to now instrument for phet-io:
```js

function mySubNode( options){
   options = _.extend();
   
   Node.call(this, options)

   /*
      construct the node
    */
   
}
inherit();
```

What we have to do in this case is aggressively make sure that the tandem is the last thing called like so:

```js

function mySubNode( options){
   options = _.extend( {tandem: options.tandemRequired()});
   
   var tandem = options.tandem;
   delete options.tandem;
   Node.call(this, options)

   /*
      construct the node
    */
   this.mutate( {tandem: tandem});
}
inherit();
```

@samreid could this explain why we haven't been bitten?

**Comment by samreid** [comment]
> It doesn't call mutate with the tandem until the very last line of the subtypiest type.

Let's say I have node subtype Button, which calls `this.mutate`.  Then I add subclass RoundButton, which adds a `radius` property and also calls `this.mutate`.  The first mutate call will register the tandem, but the radius property isn't set yet.  So any attempts to read/write the radius will fail.

**Comment by zepumph** [comment]
Yes, but you don't pass tandem up through options AND mutate in the sub class. If the subclass needs to hold off on tandem registration because it adds something important during construction, then it is up to the subclass to NOT pass up the tandem in options to the super type. Notice my lines in above code:
```js
   var tandem = options.tandem;
   delete options.tandem;
   Node.call(this, options)
```

Then we can mutate with the tandem at the end of the subtypiest constructor. 

If i'm not understanding you correctly, I'm happy to chat about it.

**Comment by samreid** [comment]
I understand, thanks for clarifying.

**Comment by zepumph** [comment]
I think this is a pertinent point though, it is delicate. We should make sure to thoroughly check usages of this as we go through and redesign/ bring up to phet-io code.

**Comment by zepumph** [comment]
Or should we work on a more robust way of doing things. Like the tandem setter knows to always wait until the constructor is done somehow.

**Comment by samreid** [comment]
We could abandon synchronous modifications and schedule registration for the first `setTimeout` after instantiation?  Synchronous modifications require an alternate API anyways, and waiting for a `setTimeout` guarantees that the instance is fully created.  Then the base class is the only one that needs to call `addInstance`, but we would still need to know the subtype TType.  But perhaps this could be provided via a new tandem flag, like `phetioType: MyType` which would get passed through the options?

@zepumph can you please comment on the proposal before I start prototyping with it?

**Comment by samreid** [comment]
Or maybe we don't even need to schedule registration for first `setTimeout` callback because `postMessage` and `iframe` will already automatically wait until sim frame is ready because it is single-threaded.

**Comment by zepumph** [comment]
I like the thought, and it seems like the right direction. Please feel free to prototype, but if I'm online before you start, I would love to talk about it a bit more. I want to make sure that I understand it completely. I'm not sure I understand the parts about `setTimeout`

**Comment by samreid** [comment]
The proposal was based on the assumption that iframes are single-threaded and cannot be interrupted in an intermediate or inconsistent state.  @zepumph and I couldn't find specific documentation about this, but we set up a test to investigate the behavior.  We tried to interrupt the "sim" frame on chrome but were unable to do so (at least on Chrome).

```html
<html>
<body>
<iframe src="html_forIFrame.html" id="source"></iframe>
<script>
  var iframe = document.getElementById( 'source' );
  setInterval( function() {
    iframe.contentWindow.postMessage( 'hello', '*' );
  }, 0 );
</script>
</body>
</html>
```

```html
<script>
  window.myForLoop = function() {
    var time = Date.now();
    while ( Date.now() - time < 2000 ) { console.log( Date.now() )}
  };

  setTimeout(window.myForLoop, 0);

  window.addEventListener( 'message', receiveMessage, false );

  function receiveMessage( event ) {
    console.log( event.data );
  }
</script>
```

**Comment by samreid** [comment]
This will be clumsy for parametric types like Property, which already supply the phetioValueType.  But maybe we can get rid of phetioValueType and have subclasses specify `phetioType: TProperty(myTType)`

**Comment by samreid** [comment]
I'm seeing plenty of occurrences with `tandem.addInstance(this,TType)` and have been converting them to `tandem.addInstance(this,{phetioType: TType})` but it crossed my mind that we may want to support 2nd arg as TType|options.

**Comment by samreid** [comment]
Maybe this could also simplify the Node side, we could call addInstance right away instead of waiting for last mutate call.

**Comment by samreid** [comment]
The proposed changes resulted in significant changes over 158 files.  Most importantly:

1. Many cases changed `tandem.addInstance(this,TType)` to `tandem.addInstance(this,{phetioType: TType})`
2. Parameterized types such as TProperty and TObservableArray now use `phetioType: TProperty(TType)` instead of `phetioValueType: TType`
3. I renamed `TProperty.valueType` to `TProperty.elementType` to distinguish it from `NumberProperty.valueType`
4. Elimination of `createSupertypeTandem` and its related implementation, class and usages.
5. Elimination of calls to `tandem.addInstance` in subclasses.

I've got things to the point where Faraday's Law Instance Proxies is working (at least no obvious defects), but we'll need a lot more testing and refinement to get this solid.

**Comment by samreid** [comment]
Beer's Law Lab instance proxies seems to be working now.  Beer's Law Lab state seems to be working except for the background color:

![image](https://user-images.githubusercontent.com/679486/32820620-9f356838-c98c-11e7-9d1e-b9f5844a98d9.png)

**Comment by samreid** [comment]
Balloons and Static electricity Instance Proxies and State are working.

**Comment by samreid** [comment]
All phet-io sims are passing phet-io aqua fuzz.

**Comment by samreid** [comment]
All phet sims are passing aqua fuzz.  `grunt lint-everything` is passing.  I think I'm at a good commit point.  We can let Bayes take a look at things, and it will be good to discuss these changes with @zepumph, perhaps take a look at a few files from axon, sun, tandem, and a sim to get a sense of the changes and let's chat.

Another benefit of this approach, the `tandem` in the superclass is the same tandem reference as the `tandem` in the subclass, this was a point of confusion previously.

**Comment by samreid** [comment]
I slacked: 

Brace yourself for nontrivial changes coming to 158 files across 32 repos to support `https://github.com/phetsims/tandem/issues/31`.  Local tests were passing and lint was OK for at least one pass, but I expect Bayes to find some trouble.

**Comment by samreid** [comment]
Pushes complete, please be on your toes and report any problems here.

**Comment by samreid** [comment]
I realized we also need to eliminate `expressions`, I'll take a look at that next.

**Comment by samreid** [comment]
I slacked @jbphet to ask:

> I’m refactoing phet-io expressions and want to know how I can test the sonification wrappers that exercise that option. For example, I saw `sonificationToneForCurrent.js` and I would like to be able to test and refactor it, but I don’t see any usages of that file.

**Comment by samreid** [comment]
It may be best to eliminate `expressions` and replace all usages with `invokeSequence`.  However, I'm wondering if we will need to add a high-level function on SimIFrameClient for that.  Or if we will need a holdover like putting `TObject.applyExpressions` in a `setTimeout` so things will continue working until we have the long term solution.

**Comment by samreid** [comment]
I was also surprised to see that many expressions still work correctly (since many of them are only calling methods on the base type, like TNode.setVisible, etc.)

**Comment by jbphet** [comment]
I spoke on zoom with @samreid and answered his questions from the comment above (https://github.com/phetsims/tandem/issues/31#issuecomment-344660098).

**Comment by samreid** [comment]
In the above commit, I converted `expressions` to `invokeSequence` in the sonification wrappers.  I tested that http://localhost/phet-io-wrapper-sonification/ohms-law/html/ohms-law-sonification.html?sonificationFile=sonificationTonesForSliderChanges&accessibility works as expected.  @jbphet can you skim the rest to see if anything was disturbed?

**Comment by samreid** [comment]
@zepumph can you please spot check some of the changes and report if they seem reasonable?  Let's also leave this issue open until @jbphet reports about testing sonification wrappers.

**Comment by zepumph** [comment]
These look good besides the above bug pointed out by @pixelzoom. Now I see 51 addInstance calls. Is it time to make a supertype that can handle that for us everywhere but in Node.js?

**Comment by samreid** [comment]
> Now I see 51 addInstance calls. Is it time to make a supertype that can handle that for us everywhere but in Node.js?

So instead of doing:

```js
tandem.addInstance(this,options);
// in dispose
tandem.removeInstance(this);
```

It would be:
```js
var PhETIOInstance = ...;
PhETIOInstance.call(this,options)
inherit(PhETIOInstance,{...});
```

And PhETIOInstance would have the removal in its dispose?

If we added a new type for this, would Node use it too?

**Comment by zepumph** [comment]
>If we added a new type for this, would Node use it too? 

Could it? I wasn't sure because of the mutator keys. I don't think it is necessary, let's get the model side set and see how that goes. It may reveal an obvious choice for how to handle the view.

In terms of PhETIOInstance, is that too phetio specific? Has there ever been a desire to adjust the prototype of Object in order to hit all of our types? If so, this file can serve that function. Perhaps keeping a more general name like `ModelObject` or `ModelInstance` could be nice.

**Comment by samreid** [comment]
Perhaps it would be used for things like ButtonListener too.  Perhaps we should name it as `PhETObject` or something general?

> Has there ever been a desire to adjust the prototype of Object in order to hit all of our types?

We've never discussed it before, I'm not sure how it would work exactly--it sounds contraindicated because 3rd party code we use may be relying on Object as it is.

**Comment by zepumph** [comment]
I guess I'm just saying that we shouldn't rule it out as a flexibility. Maybe though, PhET would never need this because if we need something with such global access, we just make it a global, like lodash. I can't see a benefit to using `this.extend(` rather than lodash's `_.extend` because we added methods like that to the Root's prototype. Whatever you think it best.

**Comment by samreid** [comment]
Here's my current thoughts on PhETObject.js.  Note the following:

* it may help simplify the event start/end calls for https://github.com/phetsims/phet-io/issues/1235.  
* it includes the phetio options
* it stores the tandem and phetioType for use in subclasses and methods
* it significantly simplifies e.g., Emitter.js

```js
// Copyright 2017, University of Colorado Boulder

/**
 *
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );
  var ObjectIO = require( 'ifphetio!PHET_IO/types/ObjectIO' );
  var phetCore = require( 'PHET_CORE/phetCore' );
  var phetioEvents = require( 'ifphetio!PHET_IO/phetioEvents' );
  var Tandem = require( 'TANDEM/Tandem' );

  /**
   * @constructor
   */
  function PhETObject( options ) {
    options = _.extend( {
      tandem: Tandem.tandemOptional(),
      phetioType: ObjectIO, // Supply the appropriate IO type
      phetioState: true, // To include the instance in the state
      phetioEvents: true, // To permit into the phet-io events stream
      phetioReadOnly: false, // When true, you can only get values from the instance; no setting allowed.
      phetioInstanceDocumentation: '' // Useful notes about an instrumented instance, shown in instance-proxies
    }, options );
    this.phetObjectTandem = options.tandem; // TODO: rename to this.tandem after all other this.*tandems deleted
    this.phetioType = options.phetioType;
    options.tandem.addInstance( this, options );
  }

  phetCore.register( 'PhETObject', PhETObject );

  return inherit( Object, PhETObject, {

    startEvent: function( eventType, event ) {
      return this.phetObjectTandem.isLegalAndUsable() && phetioEvents.start( eventType, this.phetObjectTandem.id, this.phetioType, event );
    },
    endEvent: function( id ) {
      this.phetObjectTandem.isLegalAndUsable() && phetioEvents.end( id );
    },
    dispose: function() {

      // Tandem de-registration
      this.phetObjectTandem.removeInstance( this );
    }
  } );
} );
```

**Comment by samreid** [comment]
This change will push us to always put tandem in the options.

**Comment by samreid** [comment]
For example, here's a diff indicating the change to a PrecipitateParticle in Beer's Law Lab:

![image](https://user-images.githubusercontent.com/679486/32984724-1380d446-cc69-11e7-8984-49f11d1b2083.png)

If this is indicative of the savings on other code, this will be a nice move.

**Comment by samreid** [comment]
I committed PHET_CORE/PhETObject.js above, see https://github.com/phetsims/phet-core/blob/master/js/PhETObject.js.  This will be a large change for our project to move from inheriting from Object to having instrumented types inherit from PhETObject instead.  It seems like it locks us into one way of doing things, but on the other hand, it seems like the appropriate solution to this problem and factors out a bunch of duplicated code and makes it possible to clearly document things in the right spot.  Will it have performance implications?  Maybe it will have better performance because we reduce the number of dispose closures that are used?  Or maybe having another level in the prototype chains is costly?

Anyways, this strategy seems promising but we will need to discuss it across the team to see if it's reasonable to move our entire project to this new paradigm.

**Comment by samreid** [comment]
@zepumph can you look at the proposed PhETObject.js and make recommendations before the next dev meeting?

**Comment by samreid** [comment]
@zepumph and I were wondering if we would want any other functionality in a common base type, such as tracking disposal:

```js
    /**
     * Unregisters from tandem when longer used.
     */
    dispose: function() {
      assert && assert(!this.isDisposed,'Cannot dispose the same object twice');
      this.isDisposed = true;
      
      // Tandem de-registration
      this.phetObjectTandem.removeInstance( this );
    }
```

**Comment by samreid** [comment]
If we want to support this or something like it for Node.js, then it should support Node.call(tandem) or this.mutate(tandem), which are the two supported paradigms for Node initialization.

**Comment by samreid** [comment]
@jonathanolson is wondering if this should be a mixin?

**Comment by samreid** [comment]
@jonathanolson recommends lowercase `ET`

**Comment by zepumph** [comment]
Another thought, refactoring phetioEvents into `PhetObject` is a nice idea, but I want to talk about edge cases before implementing. I can't remember what issue, but this has been brought up before. I'm thinking of how PushButtonModel triggers phet-io events with the IOType of the view, so as to hide the model/view implementation detail.

**Comment by samreid** [comment]
> I'm thinking of how PushButtonModel triggers phet-io events with the IOType of the view, so as to hide the model/view implementation detail.

Maybe we can still support this behavior, say, if the PushButtonModel triggers an Emitter that the PushButton observes, and the PushButton is truly responsible for the event, as opposed to a workaround that lets the PushButtonModel masquerade as a PushButton.

**Comment by zepumph** [comment]
That sounds nice. I agree, we should proceed with this top level approach, and we will fit in edge cases to work with this clearly better/easier system.

**Comment by zepumph** [comment]
This is now blocking two separate issues related to phetsims/joist#445.

**Comment by zepumph** [comment]
Looks like we may not be able to discuss this until the first dev meeting in December since @samreid and @pixelzoom are out the week after thanksgiving. Is there a way that we could expedite this?

**Comment by samreid** [comment]
Perhaps we will be able to discuss it Tuesday or Wednesday of next week, going on hold until then.

**Comment by zepumph** [comment]
After thinking about https://github.com/phetsims/phet-io/issues/1216#issuecomment-346405797, I feel more inclined to have this be a phet-io specific type. `PhetioObject.js` as a mixin to any type we want to be instrumented. This would be very nice to handle addInstance, disposal/removeInstance, assigning a phetioID or tandem to itself, assigning its phetioOptions to itself like phetioState/phetioInstanceDocumentation. 

I don't understand why we should have phetio.js handling its own instance options. It is confusing and not idiomatic to phet convention. Instead, if we centralized that in a phetioObject type, we would have the flexibility of options, and the structure that all devs are used to.

If we then felt like PhET needed its own type, PhetObject.js, it could be a parent to PhetioObject.js, and still be mixed in everywhere needed.

**Comment by samreid** [comment]
At a recent developer meeting, we discussed broader use of mixins in the project.  @jonathanolson also pointed out there are a few places where inheritance is dictated by other concerns, such as `molecule-shapes/js/common/view/3d/AtomView.js` which must extend `THREE.Mesh`.  That being said, I think inheritance will be the more straightforward/idiomatic/maintainable way to proceed, even if we cannot use that pattern in every case.

Currently mixins are less frequently used than inheritance: over 3000 invocations of `inherit` and less than 100 invocations of `mixInto`.  They also have unsavory parts (which one day we may solve) such as `invalidateStroke` in Paintable.js:

```js
      // Patch in a sub-type call if it already exists on the prototype
      if ( proto.invalidateStroke ) {
        var subtypeInvalidateStroke = proto.invalidateStroke;
        proto.invalidateStroke = function() {
          subtypeInvalidateStroke.call( this );
          invalidateStroke.call( this );
        };
      }
      else {
        proto.invalidateStroke = invalidateStroke;
      }
```

It would be interesting if we could design a type to be usable as a parent class or a mixin, or alternatively figure out how to overhead in making mixins to make it closer to inheritance.

I agree with the preceding comments that we should rename this to be PhET-iO specific, and fix the casing.  Perhaps it will be PhetIOObject or simply IOObject (parallel to IO types).

**Comment by samreid** [comment]
In the preceding commit, I renamed PhETObject=>IOObject.

**Comment by samreid** [comment]
Also, now that it is specialized for PhET-iO, perhaps it doesn't belong in phet-core?  On the other hand, if we put it in the `phet-io` repo, then we will have to load it with `ifphetio!` plugin and add crazy workarounds to get it running.  Maybe it should go in the tandem repo because it's available everywhere it is needed, and it is about instrumenting instances through the tandem interface and tandem is one of the primary options?

**Comment by pixelzoom** [comment]
This is assigned to me, but I'm not clear on what I'm supposed to review, or what feedback is needed. https://github.com/phetsims/tandem/issues/31#issuecomment-345887237 refers to "the bug reported by @pixelzoom" but I see no reference a specific bug in this issue.   So...  I'm going to self-unassign and await further instructions.

**Comment by samreid** [comment]
I've isolated the part for @pixelzoom review to https://github.com/phetsims/tandem/issues/36, we can proceed there.

**Comment by samreid** [comment]
Unmarked for developer meeting, after I get it fixed up we'll run it past @pixelzoom first.

**Comment by samreid** [comment]
Review complete, and PhetioObject is mainstream now, closing.
