### ISSUE TITLE
Clean up `tandemNameSuffix` and delete `TANDEM_NAME_SUFFIX`.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#310]
For code review phetsims/projectile-data-lab#32 ...

Common-code things that have a required tandemName suffix provide `TANDEM_NAME_SUFFIX`.   E.g. `RectangularRadioButton.TANDEM_NAME_SUFFIX`.   

This sim has zero uses of `TANDEM_NAME_SUFFIX`. Lots of examples where it could be used, here are a few. Search for "tandemName: " and "createTandem" and you'll find more.

```ts
tandemName: 'springRadioButton',
tandemName: 'measuringTapeCheckbox'
tandemName: `mysteryLauncher${mysteryLauncher.launcherNumber}RadioButton`,
tandem: providedOptions.tandem.createTandem( 'launcherConfigurationProperty' ),
tandemName: 'field' + fieldNumber + 'RadioButton',
```

I'm on the fence about the importance of using `TANDEM_NAME_SUFFIX` to form tandem names, and whether that's actually even what `TANDEM_NAME_SUFFIX` should be used for.  I know that I have not used it consistently, and I've never used `ReadonlyProperty.TANDEM_NAME_SUFFIX`.  If we ever need to change a suffix,  it will be less painful if we use `TANDEM_NAME_SUFFIX`.  But the combined pain (and verbosity) of having to use `TANDEM_NAME_SUFFIX` is probably greater than the one-time pain of changing some suffix. 

Anyway... You decide.

**Comment by pixelzoom** [comment]
This work is done.  Option `tandemNameSuffix` is used throughout, and redundant suffix assertions were removed.

ReadOnlyProperty and Dialog were a little tricky, because they needed to handle archetypes:

```ts
// ReadOnlyProperty.ts
tandemNameSuffix: [ 'Property', DYNAMIC_ARCHETYPE_NAME ], // DYNAMIC_ARCHETYPE_NAME means that this Property is an archetype.

// Diaog.ts
tandemNameSuffix: [ 'Dialog', DYNAMIC_ARCHETYPE_NAME ], // DYNAMIC_ARCHETYPE_NAME means that this Dialog is an archetype.
```

There are only 2 places where I was unabled to get rid of `TANDEM_NAME_SUFFIX`:

(1) In ComboBox, we need `const ITEM_TANDEM_NAME_SUFFIX = 'Item'` because ComboBoxItem is a `type`, so suffix must be handled by ComboBox (not PhetioObject).

(2) `Tandem.RootTandem.createTandem` constrains its tandem names, and `Tandem.SCREEN_TANDEM_NAME_SUFFIX` is one of the allowed names.  It would be preferrable if that constant were defined in Screen.ts, but tandem cannot depend on joist.

@samreid Would you like to have a look?  Close if OK.

**Comment by samreid** [comment]
I reviewed the commits and the notes, and everything seems good to me. Nice work and thanks. Closing.
