### ISSUE TITLE
Improve doc for PhetioStateEngine Emitters.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#313]
PhetioStateEngine has these 2 Emitters:

```ts
  // emits before state the state is set. Emits with the state object that will be set. Use the
  // second argument to check if a client Tandem is in the scope of the current set state. This is because some state
  // set calls only set partial state (like for a screen/scene).
  public readonly clearDynamicElementsEmitter: TEmitter<[ FullPhetioState, Tandem ]> = new Emitter( { parameters: [ { valueType: Object }, { valueType: Tandem } ] } );

  // emits the state after each time the PhetioStateEngine has set all that it can for the
  // provided state. Use the second argument to check if a client Tandem is in the scope of the current set state.
  // This is because some state set calls only set partial state (like for a screen/scene).
  public readonly stateSetEmitter: TEmitter<[ FullPhetioState, Tandem ]> = new Emitter( { parameters: [ { valueType: Object }, { valueType: Tandem } ] } );
```

In both cases, the documentation could use some work.  Specifically:
(1) The first parameter `valueType: Object ` is not described, and difficult to guess what it might be. Is it really `Object`, or should it be `PhetioObject`?
(2) An example of how to "Use the second argument to check if a client Tandem is in the scope of the current set state." would be nice.

**Comment by pixelzoom** [comment]
> (1) The first parameter valueType: Object  is not described, and difficult to guess what it might be. Is it really Object, or should it be PhetioObject?

Oh, I see... the first param is `FullPhetioState`.

Still having a problem with (2).

**Comment by pixelzoom** [comment]
If we have `TEmitter<[ FullPhetioState, Tandem ]>` then why do we have `{ parameters: [ { valueType: Object }, { valueType: Tandem } ] }`.  Shouldn't the first param be `valueType: FullPhetioState`?

**Comment by zepumph** [comment]
One is in type space and the other is in value space. `options.parameters` got a lot less useful once we got TypeScript, but it is still how we rely on how many args an Emitter is expected to emit(). That option is how we got runtime safety while we got rid of emit1()/emit2()/etc.

**Comment by zepumph** [comment]
How's this?

**Comment by zepumph** [comment]
You can also find the few usages that use this with:

`stateSetEmitter.addListener( ( `

**Comment by pixelzoom** [comment]
Perfect, thanks. Closing.
