### ISSUE TITLE
PhetioIDUtils should be a module and imported, not a preload

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#316]

**Comment by zepumph** [comment]
I'm starting in the right direction, but I'm not done yet.

**Comment by samreid** [comment]
CT is failing `phet-io-wrappers-tests`, I committed a potential fix.

**Comment by zepumph** [comment]
Thank you! Looks great.

**Comment by zepumph** [comment]
Alright. I have converted PhetioIDUtils from a preload to a module, and updated all usages everywhere (including wrappers). I also converted it to typescript. I have run local built and unbuilt tests of the whole wrapper suite, unit tests, and special wrappers like PDL CODAP. I also tested studio functionality, phet brand, and built jsdoc. Things are looking good! I also have a separate commit that shows typescript updates needed at usages sites, mostly that weren't taking care of undefined/null potential. 

@samreid can you please review the work. For focus:
* Changes to copySupplemental... and any possible downstream effects you can think of from the build
* The current shape of the file
* If I missed any spots where we are importing it a its own `script` tag, or from a context as a global.
* Changes in PhetioClient. Note that, like the phetioAPIComparison, it is a static global on there, but this one is public. But... since we don't want to change the Hydrogen API, I'm also setting it to be a global in PhetioClient as well. Still I tried to remove all usages in the codebase of it as a global, not from the PhetioClient.PhetioIDUtils static.
* is bad-sim-text the right spot to prohibit `phetio.PhetioIDUtils`?

Thanks ahead of time!

**Comment by samreid** [comment]
PhetioClient has `/* eslint-disable phet/bad-typescript-text*/` and hence does not fail out this line of code:

```ts
window.phetio.PhetioIDUtils = PhetioIDUtils;
```
But I wasn't sure if we wanted access differently at the PhetioClient layer. Also, SimTests has these:

```ts
    assert.ok( !!phetio.PhetioIDUtils, 'PhetioIDUtils' );
    assert.ok( !!phetio.PhetioIDUtils.getDOMElementID, 'PhetioIDUtils.getDOMElementID' );
```

So I can't tell if we should delete or document those.

**Comment by zepumph** [comment]
These two together hid the jsdoc constructor:

```
@hideconstructor
@class
```

Closing.
