### ISSUE TITLE
Should optional and not supplied tandems opt out of removeInstance?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#33]
In Tandem.removeInstance I don't see a check that no-ops if the tandem is `!required && !supplied` like I do in addInstance. That seems problematic, since then Tandem is calling remove listeners on an object that hasn't been registered with phet-io before. How have we not run into trouble before? @samreid tag so you are aware.

I suggest removeInstance look like:

```js
    /**
     * Removes an instance from the
     * @param {Object} instance - the instance to remove
     * @public
     */
    removeInstance: function( instance ) {
        if ( !this.required && !this.supplied ) {
             return;
        }

      // Only active when running as phet-io
      if ( PHET_IO_ENABLED && this.enabled ) {
        for ( var i = 0; i < instanceListeners.length; i++ ) {
          instanceListeners[ i ].removeInstance( this.id, instance );
        }
      }
    },

**Comment by samreid** [comment]
Good point, the logic in addInstance and removeInstance should probably be the same

**Comment by zepumph** [comment]
Bayes looks good. Closing
