### ISSUE TITLE
this.options is unused outside of Tandem constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#38]
Tandem.js line 47:

```js
    // @private - options (even subtype options) must be stored on the instance so they can be passed through the super
    // type inheritance chain. Note: Make sure that added options here are also added to options for inheritance and/or
    // for composition (createTandem) as they make sense.
    this.options = _.extend( {
```

`this.options` is `@private` and unused outside of the constructor.  So there's no reason to make it an instance field.

**Comment by pixelzoom** [comment]
To clarify... All of the fields in `this.options` are assigned to individual instance fields in the Tandem constructor.  So there's no need to `this.options`.

**Comment by zepumph** [comment]
Right you are, thanks.

**Comment by zepumph** [comment]
How does that look?
