### ISSUE TITLE
encapsulate the format of phetioID

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#41]
Relocating this from https://github.com/phetsims/tandem/issues/25#issuecomment-349097125, since it's an issue of it's own.   Also related to https://github.com/phetsims/tandem/issues/40.

There is currently no encapsulation of the tandem id format.  The separator (`'.'`) appears as a string literal in numerous places (see https://github.com/phetsims/tandem/issues/40).   And client code is doing things like this:

```js
// sonificationUISoundsSampled.js
163 var lastIdElement = messageObject.phetioID.split('.').pop();
```

If it's not appropriate to use `Tandem` in cases like the above, then factor out the id-related functions so that they can be by both `Tandem` and cases like the above. With the current approach, you currently have zero encapsulation of the id format.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/tandem/issues/25#issuecomment-349098299, @zepumph said:

sonificationUISoundsSampled.js is client wrapper code, so we don't have access to the Tandem instance there. We only have the string literal (phetioID).

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/tandem/issues/25#issuecomment-349099138, I said:

> sonificationUISoundsSampled.js is client wrapper code, so we don't have access to the Tandem instance there. We only have the string literal (phetioID).

See https://github.com/phetsims/tandem/issues/25#issuecomment-349097990.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/tandem/issues/25#issuecomment-349099699 @zepumph said:
We struggle with this, because we don't have a library that that is used on the sim side (with requirejs) or with wrapper code (just a global, see WrapperUtils.js).

**Comment by pixelzoom** [comment]
What's the barrier to having a library that encapsulates tandem id and is usable by both sims and wrappers?

**Comment by pixelzoom** [comment]
And for the record... The lack of encapsulation is not limited to wrappers.  I see 9 occurrences of `'.'` in the phet-io repository that qualify.

**Comment by pixelzoom** [comment]
Looks like not all occurrences of '.' in the phet-io repository are related to tandem identifier.  But my point is some of them likely are, and it's not easy to tell which ones.

**Comment by zepumph** [comment]
I see two of the 9 (10 for me) that apply to this problem:
```js
var format = function( phetioID ) {
      if ( phetioID.indexOf( '.' ) > 0 ) {
        var lastIndex = phetioID.lastIndexOf( '.' );
        return phetioID.substring( 0, lastIndex + 1 ) + '%c' + phetioID.substring( lastIndex + 1, phetioID.length );
      }
```

These should use use a Tandem static method to parse so that we can factor out the usage of '.' into a singular "tandemDelimiterChar" in Tandem.js. Is this the type of thing you are trying to centralize?

**Comment by pixelzoom** [comment]
The delimiter is only part of the encapsulation problem.  The functions for picking apart a tandem id are the other part.  E.g the above example is essentially duplicating `Tandem` `tail` and `parentTandem`.

**Comment by samreid** [comment]
phetioEvents.js should change to take a Tandem as an argument rather than a phetioID.  Other places I see `phetioID.`:

sonification: these look like they are doing string matching and probably OK
build-an-atom: testing strings, perhaps OK
create-instance-proxy-div:

```js
  /**
   * Get the display name from a lower case, dot separated string.
   * @param {string} phetioID
   * @returns {*}
   */
  var getFriendlyName = function( phetioID ) {
    var array = phetioID.split( '.' );
    var tail = array[ array.length - 1 ];
    return toWhitespaced( tail );
  };
```

instance-proxies.js does prefix matching, maybe can be deleted.

I'm not convinced that factoring out 

```js
    var array = phetioID.split( '.' );
    var tail = array[ array.length - 1 ];
```
into an auxiliary library file that is only used from one location.  In fact https://stackoverflow.com/questions/573145/get-everything-after-the-dash-in-a-string-in-javascript pointed out that a simpler implementation is `phetioID.split( '.' ).pop()` which also seems like it doesn't need to be factored out.

**Comment by samreid** [comment]
@pixelzoom thoughts?

**Comment by pixelzoom** [comment]
> sonification: these look like they are doing string matching and probably OK
build-an-atom: testing strings, perhaps OK

Not clear what specifically you're referring to, so I can't comment on whether I think that are OK.

Things are properly encapsulated if:
(1) you can change the separator from '.' to something else _in one place_ 
(2) code for parsing a tandem (e.g. `tail`, `parentTandem`) is not duplicated

**Comment by pixelzoom** [comment]
Related issue: phetio ids should not be formed using string concatenation

**Comment by samreid** [comment]
Based on the remarks in this issue and in https://github.com/phetsims/molecules-and-light/issues/165 I want to make sure we are on the same page about usage of `phetioIDs` and how they are intended to be used.  Let's look for instance at phet-io-wrappers/build-an-atom-game/build-an-atom-game.html which has this code:

```js
simIFrameClient.invokeSequence([
  { phetioID: 'buildAnAtom.gameScreen.model.provideFeedbackProperty', method: 'setValue', args: [ false ] },
  { phetioID: 'buildAnAtom.gameScreen.view.scoreboard.scoreText', method: 'setVisible', args: [ false ] },
  { phetioID: 'buildAnAtom.gameScreen.view.scoreboard.startOverButton', method: 'setVisible', args: [ false ] }
]);
```

The first `phetioID` is `buildAnAtom.gameScreen.model.provideFeedbackProperty` which is a term that a PhET-iO client would observe in the Instance Proxies wrapper or Documentation wrapper which lists all of the phetioIDs.

In order to factor out the `.` are you picturing something like this?

```js
var Tandem = require('SOME WAY OF LOADING TANDEM.JS IN A WRAPPER HTML FILE');
// ...
var tandem = Tandem.createRootTandem('buildAnAtom'); // Note: root tandem is defined for sims, not for wrappers.  The wrapper could access the sim Tandem.rootTandem but it would be asynchronous
simIFrameClient.invokeSequence([
    { phetioID: tandem.createTandem('gameScreen').createTandem('model').createTandem('provideFeedbackProperty', method: 'setValue', args: [ false ] },
 // ...
```

If this is what you are picturing, then please describe how the benefits outweigh the costs.  If this is not what you are picturing, then please clarify or describe an alternative.

**Comment by pixelzoom** [comment]
I'm OK with usages like:

`{ phetioID: 'buildAnAtom.gameScreen.model.provideFeedbackProperty', method: 'setValue', args: [ false ] },`

... where you're using a complete id that was formed elsewhere.  If you were somehow manipulating this id (e.g. `phetioID.split( '.' ).pop()`) that's not OK.

**Comment by zepumph** [comment]
>phetioID: 'buildAnAtom.gameScreen.model.provideFeedbackProperty'
vs
>If you were forming this id using string concatenation, or somehow manipulating this id (e.g. phetioID.split( '.' ).pop()) that's not OK.

To me, string manipulation and using intact phetioIDs (both in the wrapper code) use the same assumptions about id structure and separator key. @pixelzoom would you explain how you find these different? Please note that I am only talking about the wrapper side, which most often means that 
 we aren't using requirejs, but rather plain ol' javascript.

**Comment by pixelzoom** [comment]
`'buildAnAtom.gameScreen.model.provideFeedbackProperty'` (for example) is a token that you got from the sim that identifies a specific Property.  You don't care about what the actual token is, what the separators are, etc.  For the purposes of the wrapper, it could just as well have been something like "4f284dkg74232".    So no problem _using_ that identifier as a string literal.

What is a problem is not encapsulating how those identifier are formed and manipulated.

**Comment by samreid** [comment]
For the moment, let's focus our conversation on phet-io-wrappers/instance-proxies/createInstanceProxyDiv.js line 65

```js
  /**
   * Get the display name from a lower case, dot separated string.
   * @param {string} phetioID
   * @returns {*}
   */
  var getFriendlyName = function( phetioID ) {
    return toWhitespaced( phetioID.split( '.' ).pop() );
  };
```

I appreciate the recommendation to factor this out.  Where should we factor it out to?  Once we decide how to address this occurrence, we can generalize to other occurrences if any.

Option 1: Make a `getPhetioIDTail` function earlier in the file.  
Option 2: Factor out `.` in the file as `PHETIO_ID_SEPARATOR`
Option 3: Create a new file called: `PhetIOIDUtils.js` that creates globals you can use for this.
Option 4: Add a utility function in `WrapperUtils.js` that has a function for this.

I'm leaning toward Option 4, @pixelzoom is that what you had in mind?

**Comment by pixelzoom** [comment]
> I'm leaning toward Option 4, @pixelzoom is that what you had in mind?

For `getFriendlyName`, the wrappers and sims should be using the same implementation as Tandem `tail`. `WrapperUtils.js` lives in phet-io-wrappers.   So unless you want to make every sim depend on phet-io-wrappers, no, that's not the approach I had in mind.  

Option 3 is closer, but not globals.  There should be an encapsulation of phetioID-related methods that is usable by sims and wrappers. 

Perhaps we should discuss on Slack.  This is very basic best practices for design of a protocol, this should not be this difficult, or require this much discussion.

**Comment by samreid** [comment]
Available to chat about tandem/issues/41 at your convenience.

Until then, I'll look into creating a preload file that can be used by sims and wrappers.

**Comment by pixelzoom** [comment]
Here's what I had in mind, PhetioIDUtils.js in tandem.  There may be a better term than "component" for the implementation and documentation.

```js
// Copyright 2017, University of Colorado Boulder

/**
 * Utilities for creating and manipulating PheT-iO identifiers, aka phetioID.
 *
 * @author Chris Malley (PixelZoom, Inc.)
 */
define( function( require ) {
  'use strict';

  // modules
  var tandemNamespace = require( 'TANDEM/tandemNamespace' );

  // constants
  var SEPARATOR = '.';

  var PhetioIDUtils = {

    /**
     * Appends a component to an existing phetioID to create a new unique phetioID for the component.
     * Example: append( 'myScreen.myControlPanel', 'myComboBox' ) -> 'myScreen.myControlPanel.myComboBox'
     * 
     * @param {string} phetioID
     * @param {string} componentName
     * @returns {string}
     */
    append: function( phetioID, componentName ) {
      assert && assert( componentName.indexOf( SEPARATOR ) === -1,
        'separator appears in componentName: ' + componentName );
      return phetioID + SEPARATOR + componentName;
    },

    /**
     * Given a phetioID, identify how many components are involved in the id.
     * Example: 'myScreen.myControlPanel.myComboBox' -> 3
     * 
     * @param {string} phetioID
     * @returns {number}
     */
    getNumberOfComponents: function( phetioID ) {
       return phetioID.split( SEPARATOR ).length;
    },

    /**
     * Given a phetioID for a component, get the part of that id that pertains to the component.
     * Example: 'myScreen.myControlPanel.myComboBox' -> 'myComboBox'
     * 
     * @param phetioID
     * @returns {string}
     */
    getComponentName: function( phetioID ) {
      var indexOfLastSeparator = this.id.lastIndexOf( SEPARATOR );
      if ( indexOfLastSeparator === -1 ) {
        return phetioID;
      }
      else {
        return phetioID.substring( indexOfLastSeparator, phetioID.length );
      }
    },

    /**
     * Given a phetioID for a component, get the part of the phetioID of the parent component.
     * Example: 'myScreen.myControlPanel.myComboBox' -> 'myScreen.myControlPanel'
     * 
     * @param {string} phetioID
     * @returns {string}
     */
    getParentID: function( phetioID ) {
      var indexOfLastSeparator = this.id.lastIndexOf( SEPARATOR );
      assert && assert( indexOfLastSeparator !== -1, 'phetioID does not have a parent component: ' + phetioID  );
      return phetioID.substring( 0, indexOfLastSeparator );
    }
  };

  tandemNamespace.register( 'TYPE$', PhetioIDUtils );

  return PhetioIDUtils;
} );
```

**Comment by samreid** [comment]
Wrappers do not use requirejs.

**Comment by pixelzoom** [comment]
Then something that can be used with or without requirejs, like `string.js` plugin.   The point is what's in the above example and how it encapsulates phetioID.

**Comment by samreid** [comment]
So.... a global?

**Comment by pixelzoom** [comment]
Assuming a sim is running, wouldn't PhetioIDUtils already be available to wrappers via `phet.tandemNamespace.PhetioIDUtils`?

**Comment by samreid** [comment]
The wrapper is in a different frame than the sim, so we would have to either (1) require same-origin policy which is not a constraint we have now, or (2) supply asynchronous support for those methods and access over postMessage or the PhET-iO API (which uses postMessage).

**Comment by pixelzoom** [comment]
So we have a design where wrappers and sims are incapable of sharing the same reusable code?

**Comment by samreid** [comment]
Looking at phet-io-wrappers/instance-proxies/instance-proxies.html I can see there are a few files used in sims and wrappers: QueryStringMachine.js, lodash, jquery.  To make code usable in sims and wrappers, the straightforward way would be to use a preload and attach objects to `window` globals.  If we apply that to this case, it seems Tandem would still be requirejs but its methods like `tail` would call utility functions in the preload.

We previously discussed supplying a sim build with the wrapper, but decided against it because of the increased download time/startup time.

**Comment by pixelzoom** [comment]
An approach similar to QueryStringMachine.js seems fine.  May want to limit use of PhetioIDUtils to Tandem, then provide static (delegate) methods in Tandem for clients that need to manipulate phetioID.

**Comment by samreid** [comment]
I created PhetioIDUtils and used it in Tandem and instance proxies.  I updated all development htmls to point to the new preload.  All fuzz tests are green (aside from sugar-and-salt-solutions) and lint everything is passing.  Committing.

**Comment by samreid** [comment]
@pixelzoom I factored out PhetioIDUtils and used it in Tandem.js and createInstanceProxyDiv.js, can you please review?

**Comment by pixelzoom** [comment]
Looks good to me.  Anything else to do?

**Comment by samreid** [comment]
That's all for now, closing.
