### ISSUE TITLE
similarity of IOObject and ObjectIO names may result in programming errors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#43]
From review of IOObject in https://github.com/phetsims/tandem/issues/36#issuecomment-350785293:

>> - [ ] IOObject and ObjectIO in the same file, potentially confusing.
> A Type always refers to its IO Type (formerly known as TType). For instance Vector2 refers to Vector2IO. IOObject has the IO prefix because it is specific to PhET-iO. Not sure how to clarify this.

Yes, I understand the semantics, and I understand the roles of IOObject and ObjectIO.  I'm just predicting that they will be inadvertently confused because of the similarity of their names.

**Comment by pixelzoom** [comment]
If we don't come up with a different name for one of these types, then we should at least mention this at a developer meeting, so that all developers are aware of this pitfall.

**Comment by samreid** [comment]
@zepumph what do you think we should do?

**Comment by zepumph** [comment]
Not changing `ObjectIO` seems like an obvious choice, since it is part of wrapper type convention. We could change `IOObject` to `phetioObject`. That seems easy and reasonable.

**Comment by pixelzoom** [comment]
Why would we use lowercase (`phetioObject`) for a type name?

**Comment by zepumph** [comment]
You are right! `PhetioObject` is probably better that `PhETIOObject` eh?

**Comment by pixelzoom** [comment]
IOObject is documented as:

```js
4 * Base type for PhET types, provides support for PhET-iO features when running with PhET-iO enabled.
```

This comment seems to leave the door open to putting non-PhET-iO functionality in this type. If that's the intent, then perhaps `PhETObject`?   If that's not the intent, then make it clear in the documentation (and type name, if it's changed) that this type handles PhET-iO responsibilities only.

**Comment by samreid** [comment]
I changed the docs to indicate it is for PhET-iO instrumentation only.

**Comment by samreid** [comment]
Meeting consensus:

> PhetioObject

**Comment by samreid** [comment]
I'll work on this.

**Comment by samreid** [comment]
I renamed it above, and realized that I need to rename this in the beers-law-lab branch as well.  And we should bring that beers-law-lab branch to master.

**Comment by samreid** [comment]
Renaming complete, closing.
