### ISSUE TITLE
Fix the parentheses space

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#45]
From https://github.com/phetsims/tandem/issues/44#issuecomment-350815308 @jonathanolson said:

> It has my approval (just reviewed the above commit), just fix the parentheses-space formatting that got reverted.

I'm guessing that @jonathanolson is referring to this new space:

![image](https://user-images.githubusercontent.com/679486/33949398-b7267d36-dfe6-11e7-8300-f7d11cf3a64e.png)

This space is added by WebStorm IDEA PhET Formatting.  Is it undesriable?

**Comment by jonathanolson** [comment]
Turns out I read the diffs incorrectly, and thought things like this were getting broken instead of fixed:

![spaces-a](https://user-images.githubusercontent.com/480878/33952585-7fb36afe-dfef-11e7-9788-71bdab34507d.PNG)

Closing, sorry about that!
