### ISSUE TITLE
questions about the 'id' used by startEvent and endEvent

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#47]
Notice in commit https://github.com/phetsims/tandem/commit/8da7c9717f130a38c1930c0b133c1a5bb123f07a while https://github.com/phetsims/phet-io/issues/1281.

Questions about PhetioObject.js:

(1) Why is the return value of `startEvent` documented as `@returns {number|boolean}`? When would it be number vs boolean?  And how can it possibly be anything but boolean when the `return` statement is a boolean expression? I.e.:

`94 return this.phetioObjectTandem.isLegalAndUsable() && phetioEvents.start( eventType, id, this.phetioType, event, args );`

(2) Similarly for `endEvent`, why is the `id` parameter documented as `@param {number|boolean} id`.  When is it appropriate to use a number vs a boolean?

**Comment by samreid** [comment]
> And how can it possibly be anything but boolean when the return statement is a boolean expression?

For example, `true && 4` evaluates to `4`.

If the tandem is not legal and usable, then the expression short circuits and returns false.  If the tandem is legal and usable, it returns a numeric identifier that is used to cross-check the end (to make sure ends and starts match).

**Comment by pixelzoom** [comment]
Thanks for the clarification. I've added that info to the `@returns` tag of `startEvent`.

Perhaps `@returns {number}|false` would be a better way to document `startEvent`?

I'm also unclear on what happens in the case where `startEvent` returns `false`.  Presumably that `false` id value is passed to `endEvent`.  But `endEvent` isn't checking to see if `id === false`, and is instead calling `isLegalAndUsable` again.  Can you clarify?

**Comment by samreid** [comment]
There is an assumption that `isLegalAndUsable` will have the same value at start and end, and hence will be a suitable check.  It may be equivalent to check `id===false`.  Not sure which I prefer, let me know your recommendation.

**Comment by pixelzoom** [comment]
I added some more doc for `endEvent`:

`@param {number|boolean} id - identifier that was returned by the corresponding startEvent`

But this whole `{number|boolean}` has that "implicit coercion" smell to it.  And (as evidenced by the trouble I'm having with it) is confusing, difficult to document, etc.   Instead of returning `false` when the tandem is "not legal and usable", how about returning a special numeric id, like -1 ?

**Comment by pixelzoom** [comment]
```js
    startEvent: function( eventType, event, args ) {
      assert && assert( !this.eventInProgress, 'cannot start event while event is in progress' );
      this.eventInProgress = true;
      var id = this.phetioObjectTandem.id;
      if ( this.phetioObjectTandem.isLegalAndUsable() ) {
        return phetioEvents.start( eventType, id, this.phetioType, event, args );
      }
      else {
        return phetioEvents.ILLEGAL_OR_UNUSABLE_EVENT_ID;
      } 
    },
```

I'm sure there's a better name for `ILLEGAL_OR_UNUSABLE_EVENT_ID` ;)

**Comment by pixelzoom** [comment]
... and since `endEvent` never uses `id` when it's a `boolean`, it really doesn't need to ever be a boolean.  When !isLegalAndUsable, you could return pretty much any numeric value from `startEvent`, and it will never be passed to `endEvent`.

**Comment by pixelzoom** [comment]
`phetioEvents.start` is already using -1 as a special "don't do anything" message index.  See phetioEvents.js lines 136 and 186.  Recommended to factor out this -1 (`NO_MESSAGE_INDEX`?), and use it in PhetioObject, something like:

```js
    /**
     * Start an event for the nested PhET-iO event stream.
     * @param {string} eventType - 'model' | 'view'
     * @param {string} event - the name of the event
     * @param {Object} [args] - arguments for the event
     * @returns {number} - a numeric identifier that is used to cross-check the endEvent call
     *   (to make sure starts and ends match), -1 if the tandem is not legal and usable.
     * @public
     */
    startEvent: function( eventType, event, args ) {
      assert && assert( !this.eventInProgress, 'cannot start event while event is in progress' );
      this.eventInProgress = true;
      var id = this.phetioObjectTandem.id;
      if ( this.phetioObjectTandem.isLegalAndUsable() ) {
        return phetioEvents.start( eventType, id, this.phetioType, event, args );
      }
      else {
        return phetioEvents.NO_MESSAGE_INDEX;
      }
    },

    /**
     * End an event on the nested PhET-iO event stream.
     * @param {number} id - identifier that was returned by the corresponding startEvent
     * @public
     */
    endEvent: function( id ) {
      assert && assert( this.eventInProgress, 'cannot end an event that hasn\'t started' );
      phetioEvents.end( id );
      this.eventInProgress = false;
    },
```

Note that there's no need to test `legalAndUsable` in `endEvent`, because `phetioEvents.end` will handle turning itself into a no-op (phetioEvents.js line 186).

There's also a little terminology problem herein...  PhetioObject startEvent/endEvent calls it an "identifier", phetioEvents.js calls it a "message index".

**Comment by samreid** [comment]
Maybe we can go one step further and have phetioEvents.start take the `tandem` as an argument (instead of the `id`), then it can do the check and short circuit itself.

**Comment by samreid** [comment]
I'm planning to work on this after https://github.com/phetsims/tandem/issues/46 is complete so there are a much smaller number of cases to convert.

**Comment by samreid** [comment]
PhetioObject.startEvent no longer has a return value, and no `id` needs to be passed to `endEvent`.  @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
This comment looks like it might be vestigial, since I don't see phetioID anywhere in PhetioObject.js:

`83 // TODO: do we need phetioID if we have phetioObjectTandem?`

**Comment by pixelzoom** [comment]
Worked on this with @samreid via Slack, see above commits.

**Comment by pixelzoom** [comment]
Reassigning to @samreid to take a closer look at faradays-law data stream, to verify before closing.

**Comment by samreid** [comment]
I'm also seeing some failed unit tests after the changes above.  I'll look into them.

```
tandem : top-level-unit-tests : require.js?ea
1 out of 3 tests passed. 2 failed.
PhetioObject: PhetioObject start/start failed:
Should throw an assertion error when starting event twice
    at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1516674468298/tandem/js/PhetioObjectTests.js?bust=1516676346673:35:29)

PhetioObject: PhetioObject end without start failed:
Should throw an assertion error when Ending an unstarted event
    at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1516674468298/tandem/js/PhetioObjectTests.js?bust=1516676346673:58:29)
```

**Comment by samreid** [comment]
Faraday's Law data stream seems good.  I removed options to endEvent() and checked lint is passing and equality explorer is launching.

**Comment by samreid** [comment]
The first unit test failure is because when running in PhET brand but not PhET-iO brand.  Specifically:
http://localhost/tandem/tandem-tests.html?ea&brand=phet-io passes
http://localhost/tandem/tandem-tests.html?ea fails

This is because in PhET brand, `isSuppliedAndEnabled` evaluates to false and the event never gets "started", so there is no error when `endEvent` is called.  Perhaps we just need to make this unit test only run in PhET-iO brand.

**Comment by samreid** [comment]
Proposed fix committed, @pixelzoom would you like to review the last series of commits?
