### ISSUE TITLE
what is the correct term for the 'id' field of a Tandem instance?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#49]
What is the correct term for referring to the `id` field of a Tandem instance?  I see no less than 4 different names for this thing in code and issues:

id
phetioID
tandem id
wrapper id

... and it's confusing.  Highly recommended that you standardize on a term, one that makes sense for the public API.

**Comment by samreid** [comment]
I think we previously agreed to use `phetioID`.  What are all of the sites that should be updated to reflect this?  Should `Tandem.id` be renamed to `Tandem.phetioID` too?

**Comment by zepumph** [comment]
In my mind Tandem has always been separate from phet-io. I think I feel this way because Tandem sets up the id structure, and phet-io attaches appropriate listeners and uses those ids. For this reason I don't dislike keeping `id` as the name, although I don't feel strongly against renaming to `phetioID` for consistency. 
Since instances are of type `Tandem`, their name should have the suffix "Tandem", so most usages look like `myTypeTandem.id`, in the phet code. Then over in the phet-io wrapper/client side, they are just strings, not of type `Tandem`, and called `phetioID`.

**Comment by samreid** [comment]
I'm comfortable with `Tandem.id` and `phetioID` in the wrappers, but OK to change to `Tandem.phetioID` if that helps.

I changed/reworded/fixed occurrences of "tandem id".  Did not see occurrences of "wrapper id".

@pixelzoom can you please review my comment and @zepumph comment and advise?

**Comment by pixelzoom** [comment]
Above changes look good.

> I'm comfortable with `Tandem.id` and `phetioID` in the wrappers, but OK to change to `Tandem.phetioID` if that helps.

`Tandem.phetioID` would certainly tie it all together, and make it clear what `@param phetioID` is expected to be.

> I changed/reworded/fixed occurrences of "tandem id".  Did not see occurrences of "wrapper id".

I must have been thinking of "wrapper type" -- which is a similar issue to this one, multiple (vestigial?) names for the same thing: wrapper type, IO type,...

**Comment by samreid** [comment]
I'll rename `Tandem.id` to `Tandem.phetioID` and create a new issue for renaming "wrapper types" to "IO types".

**Comment by samreid** [comment]
In the preceding commits, I changed `Tandem.id` to `Tandem.phetioID`.  I should manually iterate through the remaining occurrences of `.id` and see which need to be updated.  I'm seeing possibilities in some wrapper files.

**Comment by samreid** [comment]
In classroom-activity, it looks like HTML element `id`s get reused as phetioIDs, so they cannot be renamed.

**Comment by samreid** [comment]
I reviewed the 400+ occurrences of `.id` and flagged https://github.com/phetsims/phet-io-wrapper-classroom-activity/issues/4 and fixed https://github.com/phetsims/tandem/commit/62a98be078e0c70d31a251cac94dd7553c3f3662

**Comment by samreid** [comment]
@pixelzoom anything else to do for this issue?  (Note side issues which will be handled separately: https://github.com/phetsims/phet-io/issues/1291 https://github.com/phetsims/phet-io-wrapper-classroom-activity/issues/4 )

**Comment by pixelzoom** [comment]
👍 Looks good, closing.
