### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#50]
In states of matter and a few others, it looks like BooleanRectangularStickyToggleButton is never calling `PhetioObject.initializePhetioObject`.

```
TypeError: Cannot read property 'id' of undefined
    at BooleanRectangularStickyToggleButton.startEvent (/tandem/js/PhetioObject.js?bust=1514317781124:99)
    at StickyToggleButtonModel.toggle (/sun/js/buttons/StickyToggleButtonModel.js?bust=1514317781124:114)
    at Array.downListener (/sun/js/buttons/StickyToggleButtonModel.js?bust=1514317781124:61)
    at Emitter.emit2 (/axon/js/Emitter.js?bust=1514317781124:179)
    at Property._notifyListeners (/axon/js/Property.js?bust=1514317781124:180)
    at Property._setAndNotifyListeners (/axon/js/Property.js?bust=1514317781124:167)
    at Property.set (/axon/js/Property.js?bust=1514317781124:114)
    at Object.down (/sun/js/buttons/ButtonListener.js?bust=1514317781124:42)
    at ButtonListener.buttonDown (/scenery/js/input/DownUpListener.js?bust=1514317781124:103)
    at ButtonListener.down (/scenery/js/input/DownUpListener.js?bust=1514317781124:139)
```

**Comment by zepumph** [comment]
I dove into this, and it looks like this error is only happening on types marked with `Tandem.indicateUninstrumentedCode()`. There we don't have a truthy tandem with an id, so this link fails:
`var id = this.phetioObjectTandem.id;` since `this.phetioObjectTandem` is assigned from `options.tandem`. 
Two thoughts about how to proceed:

1. Add `tandem: tandem.optional` to all places with `Tandem.indicateUntstrumentedCode()` calls.
2. Support falsey downstream (less preferred I think) with the following `or` logic.
`this.phetioObjectTandem = options.tandem || Tandem.hasIdButIsNotInstrumented;`

(2) may cover up problems for us down the line.

What do you think @samreid?

**Comment by zepumph** [comment]
One more thought. In most cases this won't matter, because there won't be a phet-io event hooked up in a class that isn't instrumented, but this error is for the edge case where a subtype is not instrumented, but the parent is triggering an event to the data stream, without a tandem. Perhaps there needs to be a check for this.

**Comment by samreid** [comment]
The problem is that RoundButtonView and RectangularButtonView do not pass additional phetio options to `initializePhetioObject` so PhetioObject never gets fully initialized.  I think we need to adjust the checks in `initializePhetioObject` or have a better way of passing the base options from the call site.

**Comment by samreid** [comment]
I couldn't find a good direct solution (yet?) so I've applied a workaround in RoundButtonView and RectangularButtonView.  @zepumph can you please take a look at your convenience?

**Comment by zepumph** [comment]
>The problem is that RoundButtonView and RectangularButtonView do not pass additional phetio options to initializePhetioObject so PhetioObject never gets fully initialized.

I'm not sure I understand this. These views both inherit from Node, which has this line:
`      this.initializePhetioObject( { phetioType: NodeIO }, options );`

so why do we need more options? We already have base options.

**Comment by samreid** [comment]
The docs for `initializePhetioObject` are:

```js
    /**
     * @param {Object} baseOptions - only applied if options keys intersect OPTIONS_KEYS
     * @param {Object} options
     * @protected
     */
    initializePhetioObject: function( baseOptions, options ) {
```

If there are no relevant keys provided in `options`, then PhetioObject returns early and waits for a future call where the options are provided.

**Comment by zepumph** [comment]
Sounds good, thanks for explaining. I think that this will work for now.
