### ISSUE TITLE
Rename PhetioObject.startEvent/endEvent to have "phetio" in them

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#55]

**Comment by zepumph** [comment]
Right now it seems confusing to have these events dispersed in complicated event logic, and not well named. Like this in SimpleDragHandler, it is very difficult to see which events are for phetio, and what is just for the method:

```js

    startDrag: function( event ) {
      if ( this.dragging ) { return; }

      // set a flag on the pointer so it won't pick up other nodes
      event.pointer.dragging = true;
      event.pointer.cursor = this.options.dragCursor;
      event.pointer.addInputListener( this.dragListener, this.options.attach );

      // set all of our persistent information
      this.isDraggingProperty.set( true );
      this.pointer = event.pointer;
      this.trail = event.trail.subtrailTo( event.currentTarget, true );
      this.transform = this.trail.getTransform();
      this.node = event.currentTarget;
      this.lastDragPoint = event.pointer.point;
      this.startTransformMatrix = event.currentTarget.getMatrix().copy();
      // event.domEvent may not exist if this is touch-to-snag
      this.mouseButton = event.pointer instanceof Mouse ? event.domEvent.button : undefined;

      this.startEvent( 'user', 'dragStarted', {
        x: event.pointer.point.x,
        y: event.pointer.point.y
      } );
      if ( this.options.start ) {
        this.options.start.call( null, event, this.trail );
      }
      this.endEvent();
    },
```

**Comment by zepumph** [comment]
I went with `phetioStartEvent`/`phetioEndEvent` because we already have the convention of starting option properties with `phetio`. Now we can still say that anything phet-io related in sim/common code will either be involved with `tandem`, or start with `phetio`.

Please review. Is there anything else for this issue @samreid?

**Comment by samreid** [comment]
Looks great, thanks, closing.

**Comment by pixelzoom** [comment]
Reopening. Now we have a terminology problem, see https://github.com/phetsims/tandem/issues/156#issuecomment-603977930.  PhetioGroup deals with "member" and you've described the callback parameter as "element".   I'd like to see PhetioGroup refer to "element", but that's still up for discussion in #156.  So in the meantime, I've changed "element" to "member" so that PhetioGroup is at least internally consistent.  @zepumph please review.

**Comment by pixelzoom** [comment]
Oops, reopened and added comment to wrong issue.  I'll clean up and delete irrelevant comments.
