### ISSUE TITLE
failure to check phetioType in PhetioObject

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#56]
PhetioObject line 141:

```js
      // Instantiate the wrapper instance which is used for PhET-iO communication
      if ( PHET_IO_ENABLED && this.tandem.enabled && this.tandem.supplied ) {
        this.phetioWrapper = new this.phetioType( this, this.tandem.phetioID );
      }
```

If you instrumented a DerivedProperty and didn't specify the `phetioType` option, this will fail with:

`TypeError: this.phetioType is not a constructor`

Either some validation that needs to be added, or there is some faulty logic.  E.g. perhaps this `if` statement should be inside the `if` statement at line 101?

**Comment by samreid** [comment]
I added a more specific assertion in the preceding commit.  @pixelzoom would you like to review?

**Comment by zepumph** [comment]
I think that a few things should happen here. 
1. I think `outerType` is a difficult name to understand. What about any of the following horrible options:
    * `unparameterizedType`
    * `unconstructedType`
    * `constructorType`
    * `typeWithoutParameters`
    * `uninstantiatedType`
2. If we think this belongs here, then it also belongs in Property and Emitter, and all other types with parameterized TypeIOs.
3. Rather than "hacking" this onto the implemented type like `DerivedPropertyIOImpl.outerType = DerivedPropertyIO;`, could we have phetioInherit do this work somehow? Perhaps add this as a static property.

**Comment by samreid** [comment]
It seems unfortunate that we would have to put `outerType` or something like it on every parameterized type instance, and then have to check against that in the core types.  Also note that EnumerationIO was recently introduced as a new parametric type.

Perhaps it would be best for now to (a) remove `outerType` and the code that checks it, and precede `new this.phetioType( this, this.tandem.phetioID );` with a check that `this.phetioType` is a function?

**Comment by zepumph** [comment]
>If you instrumented a DerivedProperty and didn't specify the phetioType option, this will fail with:

>>TypeError: this.phetioType is not a constructor


I think this isn't correct. `PhetioObject` has a default PhetioObject of `ObjectIO`.

If you don't overwrite that, and the type you instrument can't be cloned with the structured cloning algorithm in `window.postMessage`.

Personally I don't feel strongly about including these assertions. If we still want to add these assertions, then they should be to all parametric types.

Over in https://github.com/phetsims/tandem/issues/101 we are coming up with a better name for "outer type." Perhaps like "creatorFunction." Let's say we go with that, I wouldn't find it too offensive to see something like what is in `DerivedProperty`:

```
   assert && options.tandem.supplied && assert( options.phetioType && options.phetioType.creatorFunction === DerivedPropertyIO,
        'unsupported phetioType' );
```

**Comment by samreid** [comment]
In https://github.com/phetsims/axon/issues/260 we are considering a strategy that might make work here unnecessary.  I recommend putting this issue on hold until https://github.com/phetsims/axon/issues/260 is decided.  Sound OK @zepumph?

**Comment by zepumph** [comment]
Yes sounds great.

**Comment by zepumph** [comment]
I still really want https://github.com/phetsims/axon/issues/260 to happen, though I don't think this issue needs a priority to match that one. We can just keep it on hold.

**Comment by zepumph** [comment]
https://github.com/phetsims/axon/issues/260 is complete, and working well. We can close this issue now.
