### ISSUE TITLE
phetioInstanceDocumentation value requirements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#58]
While working on https://github.com/phetsims/hookes-law/issues/58, I added `phetioInstanceDocumentation`.   I then discovered this assertion in PhetioObject:

```js
assert && assert( _.endsWith( options.phetioInstanceDocumentation, '.' ),
  'phetioInstanceDocumentation should end with a \'.\': ' + options.phetioInstanceDocumentation );
```

On Slack, @samreid described the requirement for an ending period as "to be consistent".  

Looking at uses of `phetioInstanceDocumentation`, the only consistency that I see is consistent use of ‘.’ at the end of fragments that are not sentences, presumably to appease this assertion.  A small number  of the 51 occurrences are grammatically correct sentences.  The majority are phrases with  initial caps (sometimes) and ending period.  

I propose that we remove this assertion.  The value of `phetioInstanceDocumentation` should be similar to comments in code — format is up to the developer.  This will allow use to use fragments where verbosity is not required, and more verbose "grammatically correct" descriptions where needed.

**Comment by pixelzoom** [comment]
So that I could commit my work for phetsims/hookes-law#58, I've added awkward periods to the ends of my `phetioInstanceDocumentation` values.  I hope to remove them in the future.

**Comment by zepumph** [comment]
>This will allow use to use fragments where verbosity is not required, and more verbose "grammatically correct" descriptions where needed.

This is public facing documentation, what benefit is there for incomplete sentences and fragments to explain implementation to clients?

**Comment by pixelzoom** [comment]
@zepumph asked:
> This is public facing documentation, what benefit is there for incomplete sentences and fragments to explain implementation to clients?

The consumer of the documentation is presumably technical.  And even for non-technical audiences, concise fragments can communicate just as effectively as overly-verbose/redundant sentences. 

And the majority of the current uses of `phetioInstanceDocumentation` are already fragments.  If the assertion was intended to require documentation to be grammatically correct, it is not accomplishing that at all.

**Comment by zepumph** [comment]
I agree, clearly it isn't enough to just have that assertion.

**Comment by samreid** [comment]
The main reason this check was introduced is that studio looked something like this:

```
(1) This was a complete sentence.
(2) This was another complete sentence.
(3) just a sentence fragment here
(4) A fragment disguised as a sentence.
```

I guess (3) just stood out to me as looking odd, so I wanted a way to find and eliminate those.  I'm not sure if we need an automated step to do this or not, but this is the main documentation for PhET-iO clients, so it would be good to make sure it is complete and consistent, however we do so.

**Comment by ariel-phet** [comment]
Consensus: assertion should be removed, and agreed that some flexibility should be allowed in the presentation of the API. 

@zepumph will make a separate issue to discuss aesthetics of the API

**Comment by zepumph** [comment]
Consensus from dev meeting: we will get rid of the assertion because it is contrived and isn't helping anything. We will move to https://github.com/phetsims/phet-io/issues/1334 for discussion about what general phet-io doc should look like.
