### ISSUE TITLE
inconsistent default for phetioInstanceDocumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#59]
In PhetioObject.js:

`DEFAULT.phetioInstanceDocumentation` is the empty string `''`, line 32.

 `this.phetioInstanceDocumentation` is documented as `{string}` but is initialized to `null`, line 58.

Recommend to use `null` consistently as the default value.  If there's something downstream that requires `phetioInstanceDocumentation` to be non-null, fix it.

**Comment by zepumph** [comment]
@pixelzoom good suggestions. I agree that null is best for this. I found one spot where we needed to make sure that undefined wasn't being passed though. Please review.

**Comment by pixelzoom** [comment]
👍
