### ISSUE TITLE
Pool tandems assign the wrong index

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#6]
Currently, if you do 

```js
tandem.createPoolElementTandem('electron');
//then
tandem.createPoolElementTandem('neutron');
```

you will receive:
electron_0
neutron_1

It should be neutron_0, so we need to change this implementation. The use case will be something like:

```js
var electronPoolTandem = tandem.createPoolTandem('electron');
var electron0Tandem = electronPoolTandem.createPoolElementTandem();
```

PoolTandem would be a subclass that adds the index.

**Comment by samreid** [comment]
@pixelzoom and I also discussed renaming from Poolable tandems to something that has less of the "pool" connotations.

Perhaps something like:
```js
      var electronGroupTandem = tandem.createGroupTandem('electron');
      var electron0Tandem = tandem.createNextTandem();
```

**Comment by samreid** [comment]
I added GroupTandem above and updated the sims to use it, @pixelzoom would you like to take a look?

**Comment by pixelzoom** [comment]
A couple of fixes in the above commits, please review.

**Comment by samreid** [comment]
Changes look good, thanks, closing.
