### ISSUE TITLE
create phetioEventType option for PhetioObject

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#61]
from https://github.com/phetsims/axon/issues/180 and https://github.com/phetsims/sun/issues/340

when we converted sun buttons to use emitter, all the events are now triggered with the `eventType` of "model" even though they should be `user` events.

We should create a better way to have a default eventType (like in PhetioObject's constructor), and specify an override as we see fit for instances/certain events. This override would be done with an option passed to `phetioStartEvent`.

@samreid found that most of the events currently in the project are of type 'user'. He suspects because the model is largely driven on Emitter and Property, where the user side is basically everything else.

**Comment by zepumph** [comment]
Thoughts:

* `getInstanceMetadata` isn't including this new property. Do you think it should (I'm on the fence leaning towards no)
* default model is ok with me. I understand your hesitation. I think the goal would be to make it as simple as possible for another phet dev to get it right, so under that mentality, I recommend that we could set `PhetioObject` default to 'user' and then `Property` and `Emitter` (and other axon types) default to `model`. That is definitely more confusing from an implementation side, but maybe the outcome would be less unwieldy. No matter this deserves a section in the how to instrument md file for sure.
* only a minor doc commit above

Back to you.

**Comment by samreid** [comment]
> getInstanceMetadata isn't including this new property. Do you think it should (I'm on the fence leaning towards no)

This doesn't seem like it should be part of the state.  It should only be used to produce the messages.

> default model is ok with me. I understand your hesitation. I think the goal would be to make it as simple as possible for another phet dev to get it right, so under that mentality, I recommend that we could set PhetioObject default to 'user' and then Property and Emitter (and other axon types) default to model. That is definitely more confusing from an implementation side, but maybe the outcome would be less unwieldy. No matter this deserves a section in the how to instrument md file for sure.

Still unsure about this.  Especially we have been moving toward nested `user` `Emitters` in UI components, as described in https://github.com/phetsims/sun/issues/396.  If we passed `phetioEventType` from parents to children (defaulting to the same value as parent), then it may make sense to put `phetioEventType: 'user'` in Node.  But I'm not sure how that would work.  Let's discuss this a bit further before closing.

**Comment by samreid** [comment]
I agree, we should include the `phetioEventType` in the `instanceMetadata`.  Not sure if we would show it in studio by default aside for specific types such as Emitter or Property.  By that token, it is odd that objects that do not send events (like Node) still have a `phetioEventType`.

**Comment by samreid** [comment]
Completed in two commits above, @zepumph can you please review and close if all is well?

**Comment by zepumph** [comment]
Looks great thanks!
