### ISSUE TITLE
phetioInstanceDocumentation is too verbose

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#63]
For an option that is basically needed for every PhET-iO instrumented object, this is very long, from slack:
```
Chris Malley [13:44]
Question about the option `phetioInstanceDocumentation`…  Since it’s provided as an option to a constructor, the “Instance” bit seems redundant/unnecessary.  I’m asking because I’ve had to add this 45 times in graphing-quadratics, and I’ve been instructed that most things that get tandems should also get  `phetioInstanceDocumentation`.  Highly recommended to choose a less verbose name. (edited)

Michael Kauzmann [13:47]
I like that idea! `phetioInstanceDocumentation` --> `phetioDocumentation`. There is then more of a blur between that option and the 'documentation` property passed in as a static property to phetioInherit.

Chris Malley [13:47]
`phetioDoc` ?

Michael Kauzmann [13:48]
That will be exposed to the public API

Chris Malley [13:48]
even `phetioDocumentation` would be an improvement.


Michael Kauzmann [13:48]
I will make an issue.
```

I'm not opposed to `phetioDoc` if we can convince ourselves that it is clear enough, and that the space saving is worth the "code smell" (in the context to PhET's coding conventions: `Names (types, variables, properties, functions,...) should be sufficiently descriptive and specific, and should avoid non-standard abbreviations. For example:`).

It was in the slack, but it should be noted that whatever we choose will be exposed on the public api, and should be updated once and for all before stable FL to make it that much easier to maintain.

@samreid what do you think?

**Comment by samreid** [comment]
`phetioDocumentation` sounds nice to me.

**Comment by zepumph** [comment]
@samreid please review. It was a pretty straight forward issue although it touched many files.

**Comment by samreid** [comment]
Looks great and tests in studio well, thanks, closing.
