### ISSUE TITLE
options.highFrequency should be a constructor option, not a phetioStartEvent option

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#64]
Just as we moved `phetioEventType` from phetioStartEvent options to a constructor option, we should also move `highFrequency` to a constructor option.

- [x] We should name it with `phetio` prefix and make sure it is used for the Input.js emitters accordingly.
- [x] Remove the phetioStartEvent option
- [x] Make sure it is filtered properly.  Maybe clients should filter based on presence/absence of that flag?  Or do we still prefer the pre-filtering?
- [x] Should it appear in the phet-io metadata?  It seems so.
- [x] Remove phetioStartEvent options.
- [x] Should PhetioObject.phetioStartEvent() first arg move to constructor arg as well?

Marked as blocks-publication since we need to do this to support Input.js emitters for https://github.com/phetsims/scenery/issues/861

**Comment by samreid** [comment]
I've made numerous changes to address the checked items in the top comment.  I moved one item to a new issue.  Local tests show:

* lint is passing
* http://localhost/phet-io-wrappers/phet-io-wrappers-tests.html?sim=faradays-law&ea is passing
* http://localhost/aqua/test-server/test-sims.html?ea&audioVolume=0&sound=disabled&testDuration=10000&testConcurrentBuilds=4&brand=phet&fuzzMouse shows no systemic problems.

I'll commit and we can continue in follow-up issues.  I'm also considering changing 
`phetioHighFrequency: false` to `phetioEventFrequency: 'low'`, partly so it keeps the `phetioEvent` prefix.

**Comment by samreid** [comment]
All remaining work removed to new issues, @zepumph can you please review?  Close if all is well.

**Comment by zepumph** [comment]
In `PhetioObject`, it looks like `phetioMessageStack` is really only needed for high frequency events. It took a bit of digging to discover this. It is confusing why there needs to be a stack in PhetioObject, and a stack in phetioEvents. Is there a way around this? I think at the very least phetioMessageStack deserves more specific documentation.

Please correct me if I am wrong.

**Comment by samreid** [comment]
`dataStream.start` returns an `id`, so that it can double check that `dataStream.end(id)` correctly matches.  The stack in PhetioObject is to keep track of the indices for cross checking in dataStream.

Now that we have significantly reduced the number of calls to dataStream.start and isolated them to a handful of sites, perhaps that is no longer necessary?  But I'm wondering what would happen if we had this buggy sequence:

```js
startEvent1()
startEvent2()
endEvent() // intended to end event 1 but actually ended event 2
```

In the case of an unended event, the data stream would never emit another message, so we should be able to catch that in QA or during development.  But what if it's a prematurely ended event?  Perhaps we should discuss before deciding how to proceed.

**Comment by zepumph** [comment]
Sounds like we should keep it in just in case.

**Comment by samreid** [comment]
Adding meeting:phet-io label in case that was intended previously.  Also, @zepumph can you please clarify the state of this issue?  Is the only remaining issue regarding https://github.com/phetsims/tandem/issues/64#issuecomment-427975129 or does more review/work remain to be done?  Can we remove the "block-publication" label?

**Comment by zepumph** [comment]
I think this is ready to be closed what about you?

**Comment by samreid** [comment]
Sounds good, thanks, closing.
