### ISSUE TITLE
Should we rename phetioHighFrequency => phetioEventFrequency or similar?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#66]
From https://github.com/phetsims/tandem/issues/64.  It would be nice to have `phetioEvent` prefix, but seems unwieldy to say `phetioEventHighFrequency`--maybe `phetioEventFrequency: 'high'` would be nice?  @zepumph what do you think?  This value leaks out of the API in the instance metadata, so it needs a long-term name.

**Comment by zepumph** [comment]
This seems like it belongs in the conversation with https://github.com/phetsims/tandem/issues/67

**Comment by zepumph** [comment]
@samreid, @chrisklus, and I discussed this substantially today during the phet-io dev meeting today. It was decided that `phetioHighFrequency` was enough for right now, if more specific processing is needed it can always be done downstream, in the wrapper. 

Closing, @samreid please reopen if there is more to discuss.

**Comment by zepumph** [comment]
>phetioHighFrequency was enough for right now

In combination with a playback class of events as well.
