### ISSUE TITLE
What's the difference between disallowTandem and indicateUninstrumentedCode?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#69]
is it possible to consolidate these at all? I'm not sure I understand them.

**Comment by samreid** [comment]
`indicateUninstrumentedCode` is a flag to help us remember to check if common files need further sub-instrumentation.

I recommend we delete `disallowTandem`--looks like it was originally used to indicate that something should not be instrumentable.  OK to delete `disallowTandem`?

**Comment by zepumph** [comment]
I agree! @chrisklus is this something you would like to do?

**Comment by samreid** [comment]
`disallowTandem` has been deleted, closing.
