### ISSUE TITLE
Add Tandem.createSupertypeTandem()

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#7]
From https://github.com/phetsims/sun/issues/192

`createSupertypeTandem` would use the same id but provide no-op for addInstance().

**Comment by samreid** [comment]
Implemented and tested in Beer's Law Lab with dropper node, it seems like it is working nicely.  @pixelzoom would you like to review (low priority)?

**Comment by pixelzoom** [comment]
Yes thanks, I'll have a look. Probably not this week.

**Comment by pixelzoom** [comment]
Should the "Step 4" of "How To Instrument a PhET Simulation" be revised to indicate that `createSuperTandem` should be used when passing a tandem to a supertype?
https://github.com/phetsims/together/blob/master/doc/how-to-instrument-a-phet-simulation.md

**Comment by samreid** [comment]
I added this section in the tandems documentation:

**Tandems in subclasses**
When passing a tandem to a superclass, `tandem.createSupertypetandem` should be used.  This will prevent the supertype from registering the instance, and the subtype can call `tandem.addInstance` at the end of its constructor, so the registration will only occur once and only when the object is fully formed.

**Comment by pixelzoom** [comment]
:+1: Closing.
