### ISSUE TITLE
Should tandem option start with phetio?

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#70]
All other PhetioObject options have a phetio prefix. Should tandem have one too, like `phetioTandem`?  I think our team is pretty accustomed to tandems and knowing they are part of instrumentation, but I wondered if this should be up for discussion.  Another possibility would be to rename `Tandem` to `PhetioID` and `tandem` to `phetioID`

**Comment by zepumph** [comment]
We have decided not to go down this path. It seems clear that everything has `phetio` except `tandem`. It is well documented ( like in `// phet-io` documented options), and has a convention. Anything else for this issue?

**Comment by samreid** [comment]
I agree, let's close.
