### ISSUE TITLE
IO types cause increase in memory footprint

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#71]
From https://github.com/phetsims/unit-rates/issues/207#issuecomment-437252582:

> For clarity, @jonathanolson and I (and mainly @jonathanolson) worked out that the source of the memory leak came from the commit when I moved phetioInherit from the phet-io repo into tandem. This consequently made it so that phetioInherit was not just "stubbing" out TypeIOs and returning no-op functions like function(){}, but instead it was actually creating TypeIOs. This exposed the memory leak that @samreid explained above to all sims, even in phet brand.
> 
> Re his comment:
I think that there is likely other places where we can decrease memory consumption, seeing as 150% is still a large size increase to all sims, and likely that is from things like default parameters that @samreid was able to factor out some.

**Comment by samreid** [comment]
My summary from https://github.com/phetsims/unit-rates/issues/207#issuecomment-437248201

> The changes I made were predominantly about factoring out instantiated parametric types.  For instance, https://github.com/phetsims/axon/commit/4a9762e882ea9862af96fdf0e736754e6e6c35d8 factors out `EmitterIO( [] )` instead of creating an equivalent but different one for each `Emitter`.  I cannot say for certain that this was "the source of the memory increase", but it seemed like a safe and straightforward way to significantly reduce the memory footprint.  We can probably reduce size further by eliminating closures in common code, or by other strategies.

@pixelzoom replied:

> And yes, I've read #207 (comment) and #207 (comment), but I don't understand.

Perhaps a short call would be very helpful? I'll be on slack.

**Comment by pixelzoom** [comment]
Discussed with @samreid via Slack.

This has likely been a problem in brand=phet-io for a long time, and was not noticed due to insufficient memory testing.  It didn't manifest previously in Unit Rates, because that sim has not been instrumented.   After IO types were moved to tandem, they were no longer stubs, and therefore contributed to the memory footprint of all brands.

Example of the problem in BooleanProperty.  Previously in the constructor, every new instance received a new instance of BooleanIO.

```js
function BooleanProperty( value, options )
  ... 
  options.phetioType = BooleanIO();
  ...
}
```

This fix (which is what most of the above commits are doing) reuses 1 instance of BooleanIO for all instances of BooleanPropertyIO.

```js
var BooleanPropertyIO = PropertyIO( BooleanIO )

function BooleanProperty( value, options )
  ... 
  options.phetioType = BooleanPropertyIO;
  ...
}
```

**Comment by samreid** [comment]
Another 0.5MB saved in the preceding commit.

**Comment by samreid** [comment]
We could reduce PhET-iO memory footprint by eliminating the wrapper instances (aka `PhetioObject.phetioWrapper`).  This wouldn't help PhET brand though.

**Comment by samreid** [comment]
In https://github.com/phetsims/graphing-quadratics/issues/50#issuecomment-438877837 @pixelzoom reported:

> For comparison, the latest `brand=phet` memory tests are in https://github.com/phetsims/graphing-quadratics/issues/106 (~41MB startup, ~52MB stable).

> Test results for `brand=phet-io`:

> * [1.0.0-dev.46](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.46/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone) with `?standalone&fuzz`
* Chrome 70.0.3538.102
* macOS 10.11.6 on MacBook Pro

| Minutes | Heap Size (MB) |
| ---: | ---: |
| 0 |  43.9 |
| 5 |  52.2 |
| 10 | 53.6 |
| 15 | 54.6  |
| 20 | 54.7 |
| 25 |  55.4 |
| 30 |  55.5 |
| 45 |  55.6 |

> This looks fine.  PhET-iO appears to add < 4MB of overhead to `brand=phet`, and that seems reasonable. Closing.

@pixelzoom anything else to do for this issue?

**Comment by pixelzoom** [comment]
Seems like this issue is resolved. Closing.
