### ISSUE TITLE
printMissingTandems (a) should be prefixed with phetio (?) and (b) should print a bit nicer to the console.

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#73]
From https://github.com/phetsims/phet-io/issues/1369#issuecomment-426740777

**Comment by zepumph** [comment]
related to https://github.com/phetsims/phet-io/issues/1384

**Comment by samreid** [comment]
@zepumph upgraded the console output in https://github.com/phetsims/phet-io/issues/1384, all that is left for this issue is to change printMissingTandems to phetioPrintMissingTandems.

**Comment by samreid** [comment]
Name changed in the preceding commit.  @zepumph anything else for this issue?

**Comment by zepumph** [comment]
Nope looks good thanks
