### ISSUE TITLE
Should not be able to have a '.' in a createTandem arg

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#74]
For example, from the console:

```
phet.tandem.Tandem.rootTandem.createTandem( 'hello.dude')
-->Tandem {phetioID: "faradaysLaw.hello.dude", required: true, supplied: true}
```

Let's have that error out.

**Comment by zepumph** [comment]
Tagging @samreid 


@chrisklus, is this something you want to take a look at? I was thinking an assertion in `Tandem.js@createTandem`

**Comment by samreid** [comment]
Related or duplicate of https://github.com/phetsims/tandem/issues/24

**Comment by zepumph** [comment]
Right!
