### ISSUE TITLE
Pass type to ObjectIO for general type checking.

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#75]
This could alleviate the need to call `assertInstanceOf` in every TypeIO. Instead we could just call it in ObjectIO once. I'm not sure if we could get away with the same things for toStateObject and FromStateObject, but maybe we could assign the type as a property on the TypeIO (not instantiated) so that `toStateObject` could look something like this for Vector2IO:
```js   
  
    /**
     * Encodes a Vector2 instance to a state.
     * @param {Vector2} vector2
     * @returns {Object}
     */
    toStateObject: function( vector2 ) {
      assert && assertInstanceOf( vector2, Vector2IO.type );
      return vector2.toStateObject();
    },
```

`type` is pretty overloaded, but we could come up with something.

**Comment by zepumph** [comment]
@samreid assigning over to you, let us know if you want help, or want to delegate to one of us.

**Comment by samreid** [comment]
Validation is now automatic in the ObjectIO constructor.  Validation must still be duplicated for the static methods.  @zepumph can this issue be closed?
