### ISSUE TITLE
Use an Enumeration for `phetioEventType` option

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#76]
Use an Enumeration for `phetioEventType` option.

**Comment by zepumph** [comment]
@chrisklus I'm wondering if you are interesting in taking a stab at this one. I am happy to pair with you on it. 

Something like 
```
{
 phetioEventType: PhetioObject.EventType.MODEL
}
```

**Comment by chrisklus** [comment]
@zepumph helped me out quite a bit with this, @samreid could you review?

**Comment by samreid** [comment]
Looks great, thanks!  We will finish in https://github.com/phetsims/phet-io/issues/1427, closing this one.
