### ISSUE TITLE
Assertion failed: createTandem cannot accept dots

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#85]
From https://github.com/phetsims/phet-io/issues/1442.

While reviewing https://github.com/phetsims/molarity/issues/54 I tried to load BLL, shake some particles into the solution on the first screen, and then before particles have dissolved, launch the template. It looks like the "create" function is trying to make a Tandem like:

`new Tandem(null, "beersLawLab.concentrationScreen.model.shakerParticles.shakerParticle.element_31")`

@samreid this may be a good time to try to work out the issues behind remove/createChildInstance.

**Comment by zepumph** [comment]
I can't even reproduce the above error because I first get and assertion like `should have type: ShakerParticleIO in allTypes`, when I first shake out particles.

This certainly has to do with https://github.com/phetsims/phet-io/issues/1442.

**Comment by samreid** [comment]
Beer's Law Lab is currently working well in the state wrapper, closing.
