### ISSUE TITLE
baseline and overrides could be better handled in PhetioObject

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#86]
From phetsims/phet-io#1440

There are few improvements that could be made from that issue:

* It is odd/confusing that PhetioObject.getMetadata() has an optional argument. This is to support getting the baseline metadata before the object is constructed, but maybe there is a better way to accomplish it.
* Do we want to store the baseline metadata on each PhetioObject? Right now it is somewhat ethereal, except for phetioFeaturedBaseline
* A TODO in PhetioObject:
```
// TODO: Store "baseline" and "overrides" on the PhetioObject so that assertions during the instantiation of the
// TODO: instance don't need to be as fragile/order dependent, see https://github.com/phetsims/phet-io/issues/1440
```

**Comment by zepumph** [comment]
>It is odd/confusing that PhetioObject.getMetadata() has an optional argument. This is to support getting the baseline metadata before the object is constructed, but maybe there is a better way to accomplish it.

@samreid and I discussed this. There were a few solutions thrown around, but none felt right
* Move the field declarations above the baseline/override logic. This puts PhetioObject in an incomplete state for 100 lines of code, which feels like a smell
* factoring out the setting of all instance fields to a function, and doing that before and then also for the overrides, which has the same issue as the previous bullet.
* Factor out the PHetioObject "metadata" as a single object, and nest all of the values under that, and preallocate that object in the constructor so you don't have to call "getMetadata()" at all. That allocates too many objects, and is also weird to move phetioObject.phetioState -> phetioObject.metadata.phetioState.

I ended up keeping it as is, because alternatives don't feel as good. We'll keep thinking about it.

**Comment by zepumph** [comment]
>Do we want to store the baseline metadata on each PhetioObject? Right now it is somewhat ethereal, except for phetioFeaturedBaseline

This may not be possible because of allocation size for every PhetioObject. Maybe we can convince ourselves otherwise.

**Comment by samreid** [comment]
@zepumph and I visited PhetioObject and its startup and metadata sequence as part of https://github.com/phetsims/tandem/issues/224.  I feel like we covered some and maybe all of this issue.  @zepumph what do you say?

**Comment by zepumph** [comment]
The overrides are global, but the baseline for each object is already on PhetioObject. I feel like this issue is largely outdated

>It is odd/confusing that PhetioObject.getMetadata() has an optional argument. This is to support getting the baseline metadata 
before the object is constructed, but maybe there is a better way to accomplish it.

This is a bit of a bummer, but I don't see a way that we could have getMetadata hard coded to pull from PhetioObject keys. I know we have thought about this before, and I don't see a solution worth pursuing or spending time on. 

>Do we want to store the baseline metadata on each PhetioObject? Right now it is somewhat ethereal, except for phetioFeaturedBaseline

This is done.

>There is a todo...

This is gone.


I'm ready to close. Over to @samreid. Anything else here?

**Comment by samreid** [comment]
I think it's ready to close, thanks!
