### ISSUE TITLE
Should we validate phetioType when it comes from baseOptions?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#88]
When initializing a phet-io object, we run this code:

https://github.com/phetsims/tandem/blob/6b341e063536d344a04f064c61d3d4dea5e76630/js/PhetioObject.js#L169-L194

This is testing options BEFORE the baseOptions have been mixed into them. So sometimes we don't have a phetioType in the options. Shouldn't we be calling this code on all phetioTypes? Perhaps we could factor this code out to a method called `validatePhetioType`, and we can call it conditionally if a phetioType is provided through options, and if not test the phetioType via the baseConfig too.

**Comment by zepumph** [comment]
@chrisklus, over in https://github.com/phetsims/tandem/issues/141 you were working right around here, do you mind adding this one to your work. Basically I think all that needs to be done is to move the merge above all the assertions about `phetioType`, and then to test.

**Comment by chrisklus** [comment]
I think this is already done since we now just use the `isIOType` check in PhetioObject, and it happens after the merge:

```js
...
validate( options.tandem, { valueType: Tandem } );

options = merge( {}, DEFAULTS, baseOptions, options );

const booleanValidator = { valueType: 'boolean' };

// validate options before assigning to properties
validate( options.phetioType, { isValidValue: ObjectIO.isIOType } );
...
```

**Comment by zepumph** [comment]
1. can you factor out `booleanValidator` to be a constant.
2. I think that this is good. Currently we aren't validating the `baseOptions.phetioType` when there is an `options.phetioType`. I do not think we need to, but wanted to note the limitation (which is general to how extend/merge works). Ready to close after (1).

**Comment by chrisklus** [comment]
Thanks @zepumph. (1) was addressed in the commit above, closing.
