### ISSUE TITLE
setting phetioReadOnly via Studio fails with "api mismatches"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#89]
There's a problem with setting a Node to `phetioReadOnly: true` via Studio.  I encountered this in phetsims/graphing-quadratics#112, and discussed with @zepumph on Zoom.

Here's an example to demonstrate the problem.  I wanted to remove `phetioReadOnly: true` NoRealRootsNode.js and set it via Studio.

Before removing from the code, here's what the relevant portion of baseline.js looks like.  While the code sets `phetioReadOnly: true` on `noRealRootsNode`, that value is apparently propagated to its related PhetioObject Properties.   (Whether that's the correct thing to do is probably the first thing to consider.)

```
    "graphingQuadratics.standardFormScreen.view.noRealRootsNode": {
      "phetioReadOnly": true,
      ...
    },
    "graphingQuadratics.standardFormScreen.view.noRealRootsNode.opacityProperty": {
      "phetioReadOnly": true
      ...
    },
    "graphingQuadratics.standardFormScreen.view.noRealRootsNode.pickableProperty": {
      "phetioReadOnly": true
      ...
    },
    "graphingQuadratics.standardFormScreen.view.noRealRootsNode.visibleProperty": {
      "phetioReadOnly": true
      ...
    },
```

After removing from the code and running `grunt update`, all of the `true` values in the above baseline.js are changed to `false`.

Next steps are:
* load this into Studio
* select "All" radio button for PhET-iO Elements
* navigate to `graphingQuadratics.standardFormScreen.view.noRealRootsNode`
* check the "Read Only" checkbox
* copy the console output and paste into overrides.js
* refresh Studio

This results in this error:

```
Assertion failed: api mismatches present:

graphingQuadratics.standardFormScreen.view.noRealRootsNode.visibleProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
graphingQuadratics.standardFormScreen.view.noRealRootsNode.pickableProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
graphingQuadratics.standardFormScreen.view.noRealRootsNode.opacityProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
```

Diff'ing overrides.js, the problem becomes apparent.  There are no entries for the PhetioObject Properties associated with `noRealRootsNode`.    And if `phetioReadOnly` needs to be propagated to those Properties, we should be very careful not to simply duplicate that logic in Studio.

```
  "graphingQuadratics.standardFormScreen.view.noRealRootsNode": {
    "phetioReadOnly": true
  },
```

**Comment by pixelzoom** [comment]
This blocked further work on phetsims/graphing-quadratics#112, which I've been told is my top priority to complete by Friday 6/14/19.   So labeling this issue  with top priority.  If it can't be resolved by 6/14, then feel free to complete this part of phetsims/graphing-quadratics#112.

**Comment by zepumph** [comment]
The problem is largely that a metadata value that is determined via overrides (for the "no roots" `Node`) then effects the baseline value of a subproperty, (like the Node's visibleProperty) and so then the baseline of the sub property is "tainted" because the override changed it.

I added a bug fix above. It isn't the root cause of this issue, but it was responsible for giving me some weird logic as I tried to debug.

This doesn't seem like a simple bug fix to me. I would love help with this with @samreid and @chrisklus.

**Comment by samreid** [comment]
I put some notes and a patch in the slack channel.  Will continue investigating later.

**Comment by samreid** [comment]
@chrisklus and I fixed the problem in the preceding commits.  Now the process of using studio to specify the values will work without throwing API mismatch errors.  

> that value is apparently propagated to its related PhetioObject Properties. (Whether that's the correct thing to do is probably the first thing to consider.)

This solution propagates the baseline value from the Node to the nested NodeIO Properties.  The problem with the previous solution was that it propagated the overridden Node value to the NodeIO baselines.  One consequence of the selected solution is that `phetioReadOnly` must be specified separately in studio for all 4 elements (the node, the visibleProperty, the opacityProperty and the pickableProperty).  But we figured that is in-line with the studio/overrides way of thinking.

Also, here is a patch for the Graphing Quadratics changes if you wish to use them.

<details>

```

Index: js/phet-io/graphing-quadratics-phet-io-elements-baseline.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/phet-io/graphing-quadratics-phet-io-elements-baseline.js	(revision f6b28a8b29a7a9e60f93947da610c42d77f4c81a)
+++ js/phet-io/graphing-quadratics-phet-io-elements-baseline.js	(date 1560309596000)
@@ -9192,7 +9192,7 @@
       "phetioFeatured": false,
       "phetioHighFrequency": false,
       "phetioPlayback": false,
-      "phetioReadOnly": true,
+      "phetioReadOnly": false,
       "phetioState": false,
       "phetioStudioControl": true,
       "phetioTypeName": "NodeIO"
@@ -9203,7 +9203,7 @@
       "phetioFeatured": false,
       "phetioHighFrequency": false,
       "phetioPlayback": false,
-      "phetioReadOnly": true,
+      "phetioReadOnly": false,
       "phetioState": true,
       "phetioStudioControl": true,
       "phetioTypeName": "NumberPropertyIO"
@@ -9214,7 +9214,7 @@
       "phetioFeatured": false,
       "phetioHighFrequency": false,
       "phetioPlayback": false,
-      "phetioReadOnly": true,
+      "phetioReadOnly": false,
       "phetioState": true,
       "phetioStudioControl": true,
       "phetioTypeName": "PropertyIO.<NullableIO.<BooleanIO>>"
@@ -9225,7 +9225,7 @@
       "phetioFeatured": false,
       "phetioHighFrequency": false,
       "phetioPlayback": false,
-      "phetioReadOnly": true,
+      "phetioReadOnly": false,
       "phetioState": true,
       "phetioStudioControl": true,
       "phetioTypeName": "PropertyIO.<BooleanIO>"
Index: js/phet-io/graphing-quadratics-phet-io-elements-overrides.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/phet-io/graphing-quadratics-phet-io-elements-overrides.js	(revision f6b28a8b29a7a9e60f93947da610c42d77f4c81a)
+++ js/phet-io/graphing-quadratics-phet-io-elements-overrides.js	(date 1560309692000)
@@ -1,6 +1,5 @@
 /* eslint-disable */
-window.phet.phetio.phetioElementsOverrides =
-{
+window.phet.phetio.phetioElementsOverrides = {
   "graphingQuadratics.exploreScreen.model.aProperty": {
     "phetioFeatured": true
   },
@@ -247,6 +246,18 @@
   "graphingQuadratics.standardFormScreen.view.leftPointToolNode.visibleProperty": {
     "phetioFeatured": true
   },
+  "graphingQuadratics.standardFormScreen.view.noRealRootsNode": {
+    "phetioReadOnly": true
+  },
+  "graphingQuadratics.standardFormScreen.view.noRealRootsNode.opacityProperty": {
+    "phetioReadOnly": true
+  },
+  "graphingQuadratics.standardFormScreen.view.noRealRootsNode.pickableProperty": {
+    "phetioReadOnly": true
+  },
+  "graphingQuadratics.standardFormScreen.view.noRealRootsNode.visibleProperty": {
+    "phetioReadOnly": true
+  },
   "graphingQuadratics.standardFormScreen.view.rightPointToolNode.visibleProperty": {
     "phetioFeatured": true
   },
Index: js/standardform/view/NoRealRootsNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/standardform/view/NoRealRootsNode.js	(revision f6b28a8b29a7a9e60f93947da610c42d77f4c81a)
+++ js/standardform/view/NoRealRootsNode.js	(date 1560309582000)
@@ -45,9 +45,7 @@
 
         // phet-io
         tandem: Tandem.required,
-        phetioDocumentation: 'displays NO REAL ROOTS when the interactive quadratic has no real roots',
-        phetioReadOnly: true
-
+        phetioDocumentation: 'displays NO REAL ROOTS when the interactive quadratic has no real roots'
       }, options );
 
       const textNode = new Text( noRealRootsString, {

```

</details>

@pixelzoom can you please take a look?

**Comment by pixelzoom** [comment]
Thanks for the fix.  I didn't end up using the patch, since NoRealRootsNode wasn't the only case in GQ, just an example.

> One consequence of the selected solution is that `phetioReadOnly` must be specified separately in studio for all 4 elements 

If additional Properties are ever added to PhetioObject, won't this create a bit of a problem?

In the case of GQ, the goal was to prevent access a Node's `visibleProperty`, since it's intended to be controlled via a view-specific Property.   For example, if you want to show/hide the vertex point o the graph, you should be setting `viewProperties.vertexVisibleProperty`, not the Node's `visibleProperty`.   So I moved the `phetioReadOnly: true` from the Node to its `visibleProperty`, and didn't have to deal with the other PhetioObject Properties.

**Comment by zepumph** [comment]
>If additional Properties are ever added to PhetioObject, won't this create a bit of a problem?


I think this is asking, for example, if NodeIO created another sub Property that needed fields passed to it,  won't it be problematic to pass these to that new Property. I don't think it will, it is just a manual process to remember what to use.

It may also be asking, "what if we add another option to PhetioObject that needs to be propagated like this.?" Again I think this is not too dangerous, it is just a manual process to remember to support this correctly. As we found in GQ it errors out pretty loudly if you get it wrong (albeit with a vague assertion message).

Just like `phetioComponentOptions`. I think we aren't yet totally sure what the scope of this feature will be. I feel alright about keeping these two extra properties on PhetioObject for now, and we can reevaluate this strategy if we find that we are adding many more of the baseline metadata values than we want. Also note that https://github.com/phetsims/tandem/issues/89 came out of this review, because I'm unsure about how we should handle the initial definition of these booleans (perhaps setting them to `null`).

Back to you to close if you would like. Anything else here?

**Comment by samreid** [comment]
This strategy seems appropriate for now.  I'm also uncertain about whether in the future we will need a way to propagate overrides the way we propagate baseline values, but this seems a clear and workable plan for now.
