### ISSUE TITLE
Rename ObjectIO.instance -> ObjectIO.phetioObject

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#91]
from https://github.com/phetsims/phet-io/issues/1501. I think this will be more clear.

**Comment by samreid** [comment]
Renamed in above commits, @chrisklus or @zepumph can you please review?

**Comment by chrisklus** [comment]
@samreid your changes look good and I don't any other similar uses of 'instance'. Ready to close if you are.

**Comment by samreid** [comment]
Thanks, closing
