### ISSUE TITLE
ObjectIO.toStateObject to only support Object?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tandem#93]
In https://github.com/phetsims/phet-io/issues/1516 we tried adding an assertion to ObjectIO.toStateObject like so:
```
      // assert && assert( o instanceof Object, 'Should be serializing an Object' );
```

but there were some CT failures (no details on those right now sorry).

I think it would be nice to understand this more, and either find a way to add this in, or document why it doesn't work. I feel like we may have tried this a year ago or so, but clearly it wasn't documented!

This doesn't need to block GQIO oneone.

**Comment by zepumph** [comment]
I think the best way forward is to remove that assertion. ObjectIO is not for serializing type 'object', but instead serves as the root of the hierarchy. For some time we have allowed anything to serialize as itself in ObjectIO.toStateObject. I think that it fine and makes sense. 

>but the 2nd case is ObjectIO which forbids string.

It only forbids it if we add back in that assertion. 

For this issue I think it would be best to change ObjectIO.validator to be more flexible. What do you think?

**Comment by samreid** [comment]
I removed the commented out assertion, and generalized the validator to be:

```js
ObjectIO.validator = {
  isValidValue: value => {

    // It could be a number, string, Object, etc.
    return value !== undefined;
  }
};
```

Ready for review.
