### ISSUE TITLE
naming convention for Tandem static instances

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#95]
A naming convention question… `Tandem` has a number of static instances, named `Tandem.required`, `Tandem.globalTandem`, etc.  Since these are constants, should they be uppercase?  Ala `BeersLawSolution.COBALT_CHLORIDE`, etc.

**Comment by pixelzoom** [comment]
Regardless of case, there another problem with static instance names.  Some have a "Tandem" suffix (`rootTandem`, `generalTandem`, `globalTandem`)  while others do not (`required`, `optional`).   Let's pick one convention and use it consistently.  I don't have a preference.

**Comment by zepumph** [comment]
Here is a proposal:
```
Tandem.GENERAL
Tandem.ROOT
Tandem.GLOBAL
Tandem.OPTIONAL
Tandem.REQUIRED
```

@samreid any objections?

**Comment by samreid** [comment]
Looks great to me!

**Comment by zepumph** [comment]
I'll take this one on

**Comment by zepumph** [comment]
@chrisklus volunteered to take this on. Thanks Chris!

**Comment by pixelzoom** [comment]
@jbphet and I are both instrumenting sims.  I'm finding myself added lots of `Tandem.required`, which should be renamed to `Tandem.REQUIRED`.   @chrisklus should the priority of this issue be raised?

**Comment by zepumph** [comment]
I went ahead and implemented this, @chrisklus will you please review.

**Comment by chrisklus** [comment]
Whoops, sorry I let this slip. Thanks @zepumph. Changes look good and I found no missing cases. Ready to close.

**Comment by zepumph** [comment]
Thank you!
