### ISSUE TITLE
Tandem.optOut

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tandem#97]
When using a common-code component that requires a Tandem, there is currently no convention for how to specify otherwise. 

This came up in Gas Properties, where I used `SCENERY_PHET/GaugeNode` in the creation of a Screen icon.   We clearly don't want it to be instrumented, but it requires a Tandem.

Another example is a set of developer-only controls (e.g. Checkboxes) that we don't want to instrument. 

`tandem: null` and `tandem: Tandem.optional` would both probably work.  But we'd have no way to search for cases where we are specifying "I don't want this instrumented". 

After discussion on Slack,  we decided to add the following static instance to Tandem:

```js
Tandem.optOut = Tandem.required;
```

**Comment by pixelzoom** [comment]
@zepumph please review.

**Comment by zepumph** [comment]
That looks excellent. Thanks!
