### ISSUE TITLE
Redundant phet-io overrides should throw a validation error

### ISSUE THREAD

**Issue by samreid** [phetsims/tandem#98]
If the phet-io override file specifies the same value as the baseline file, I believe that should be a validation error.  @zepumph do you agree and do you know if we currently check for that?

**Comment by zepumph** [comment]
Yes indeed! Rule EIGHT!!!

>8. Any schema entries in the overrides file must be different from its baseline counterpart

**Comment by samreid** [comment]
Thanks, it seems that is checked in phetioAPIValidation, closing.
